comet-ml/opik

.github/workflows/publish_helm_chart.yaml
deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/README.md.gotmpl

update application version when publishing helm chart

---

.github/workflows/release.yaml

Fix updating version on  main when creating release

---

apps/opik-backend/entrypoint.sh

add newrelic agent

---

apps/opik-backend/config.yml

[NA] Add log level env vars

---

apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/InputOutputTab.tsx

OPIK-43 [New feature] Add support for displaying images if they are in the input attribute

---

sdks/python/src/opik/_logging.py
sdks/python/src/opik/decorator/base_track_decorator.py
sdks/python/src/opik/plugins/pytest/decorator.py
sdks/python/src/opik/plugins/pytest/hooks.py
sdks/python/src/opik/plugins/pytest/summary.py
sdks/python/src/opik/url_helpers.py
sdks/python/tests/unit/test_logging.py

Pytest integration now prints a small summary for LLM tests (if there was at least one)

[OPIK-41] Show the link to UI in pytest integration

---

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemDAO.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/BulkOperationsConfig.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/OpikConfiguration.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/DatabaseAnalyticsModule.java
apps/opik-backend/src/main/java/com/comet/opik/utils/TemplateUtils.java

- Fix the issue with the configuration
- Avoid full table scan on insert query
Resolves #

[NA] Bulk insert improvements

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/deployment.yaml
deployment/helm_chart/opik/templates/hpa.yaml
deployment/helm_chart/opik/values.yaml

add replicaCount and hpa for opik

---

apps/opik-frontend/src/components/shared/CodeHighlighter/CodeHighlighter.tsx
apps/opik-frontend/src/components/shared/SyntaxHighlighter/SyntaxHighlighter.tsx
apps/opik-frontend/src/components/shared/TooltipWrapper/TooltipWrapper.tsx

- fix styles for the code editor
- fix styles for the hotkey tooltip
Resolves #

[NA] Style adjustments for code editor and hotkey tooltip

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/clickhouse-operator-install-bundle.yaml
deployment/helm_chart/opik/values.yaml

set log level for clickhouse

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml
deployment/helm_chart/opik/templates/clickhouseinstallation.yaml
deployment/helm_chart/opik/values.yaml

add clickhouse backup
fix resources for clickhouse

add clickhouse backup

---

deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml
deployment/helm_chart/opik/values.yaml

clickhouse backup fix

---

apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000001_init_script.sql

[NA] Remove creation time from sort key

---

.github/workflows/deploy_docs.yaml

* [DEV-2310](https://comet-ml.atlassian.net/browse/DEV-2310)
[DEV-2310]: https://comet-ml.atlassian.net/browse/DEV-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-2310] move opik doc to dedicated s3 location

---

.github/workflows/documentation_cookbook_tests.yml

Update cookbook test Github action

---

apps/opik-frontend/src/plugins/comet/UserMenu.tsx

OPIK-78 [UX improvements] Add link to QuickStart in user menu

---

.github/workflows/build_and_push_docker.yaml
.github/workflows/build_apps.yml
build_and_run.sh
deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/README.md.gotmpl
deployment/helm_chart/opik/values.yaml

updates for helm chart

---

apps/opik-frontend/index.html
apps/opik-frontend/public/config.js
apps/opik-frontend/src/api/datasets/useExperimentsList.ts
apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/AddExperimentToCompareDialog.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPage.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/shared/LoadableSelectBox/LoadableSelectBox.tsx
apps/opik-frontend/src/plugins/comet/init.tsx
apps/opik-frontend/src/plugins/comet/utils.ts

Fix wording in some messages
Reset experiments count in the side menu when changing the workspace
Update the way the config file is loaded to the cloud version
Resolves #

[NO JIRA]  Fix small  issues found during release

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/README.md.gotmpl
deployment/helm_chart/opik/templates/clickhouseinstallation.yaml

fix for clickhouse loadbalancer

---

apps/opik-frontend/src/api/feedback-definitions/useFeedbackDefinitionDeleteMutation.ts
apps/opik-frontend/src/api/feedback-definitions/useFeedbackDefinitionUpdateMutation.ts
apps/opik-frontend/src/components/pages/FeedbackDefinitionsPage/FeedbackDefinitionsPage.tsx
apps/opik-frontend/src/components/pages/FeedbackDefinitionsPage/FeedbackDefinitionsRowActionsCell.tsx
apps/opik-frontend/src/components/shared/AddEditFeedbackDefinitionDialog/AddEditFeedbackDefinitionDialog.tsx
apps/opik-frontend/src/components/shared/AddEditFeedbackDefinitionDialog/FeedbackDefinitionDetails/CategoricalFeedbackDefinitionDetails.tsx
apps/opik-frontend/src/components/shared/AddEditFeedbackDefinitionDialog/FeedbackDefinitionDetails/NumericalFeedbackDefinitionDetails.tsx
apps/opik-frontend/src/components/shared/AddEditFeedbackDefinitionDialog/FeedbackDefinitionDetails/index.tsx
apps/opik-frontend/src/components/shared/FeedbackScoresEditor/AddFeedbackScorePopover.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceAnnotateViewer/AnnotateRow.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceAnnotateViewer/TraceAnnotateViewer.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDetailsPanel.tsx

OPIK-81 [UX improvement] Add ability to edit feedback score definitions
Resolves #

OPIK-80 [UX improvement] Add ability to delete feedback score definition

---

apps/opik-frontend/src/components/shared/CodeHighlighter/CodeHighlighter.tsx
apps/opik-frontend/src/components/shared/SyntaxHighlighter/SyntaxHighlighter.tsx

OPIK-83 [UX improvements] DatasetItems should not be editable from the UI

---

.github/workflows/build_apps.yml
.pre-commit-config.yaml
deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/configmap-frontend-nginx.yaml
deployment/helm_chart/opik/values.yaml

* [DEV-2297](https://comet-ml.atlassian.net/browse/DEV-2297)
[DEV-2297]: https://comet-ml.atlassian.net/browse/DEV-2297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-2297] add throttling features and tune nginx for opik

---

apps/opik-frontend/src/components/layout/Breadcrumbs/Breadcrumbs.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/TraceDataViewer.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/treeRenderers.tsx

- Add feedback scores to the data view
- Make the last breadcrumb item not clickable
Resolves #

[NO JIRA] Add feedback scores to data view

---

sdks/python/src/opik/api_objects/span.py
sdks/python/src/opik/api_objects/trace.py
sdks/python/src/opik/evaluation/metrics/__init__.py
sdks/python/src/opik/evaluation/metrics/base_metric.py

Fix linter issues after docstring updates

Fix linter issues

---

build_and_run.sh

[OPIK-96](https://comet-ml.atlassian.net/browse/OPIK-96)
[OPIK-96]: https://comet-ml.atlassian.net/browse/OPIK-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
* added `LOCAL_FE_PORT` required for backend
* added `LOCAL_FE_HOST` to allow fully external FE location (`LOCAL_FE_HOST=external.host.com `LOCAL_FE_PORT=8080 ./build_and_run.sh --local-fe`)
* added waiting for pods to avoid situation with pod slow-starting and failed port-forward

[OPIK-96] add fixed for build and run

---

.github/workflows/publish_helm_chart.yaml

update version for azure/setup-helm

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsDetails.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPage.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ConfigurationTab/CompareConfigCell.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ConfigurationTab/ConfigurationTab.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx
apps/opik-frontend/src/components/shared/DataTableNoData/DataTableNoData.tsx

[OPIK-91] [UX improvements] Implement the Experiment configuration section in the compare page

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/ConfigurationTab/CompareConfigCell.tsx

Add pre-line text wrap to compare experiments config

---

sdks/python/src/opik/api_objects/opik_client.py
sdks/python/tests/e2e/conftest.py

Fix experiment_config error message

---

sdks/python/src/opik/opik_configure.py

Small change to run CI

---

sdks/python/src/opik/api_objects/opik_client.py

Fix config creation in Opik

---

apps/opik-frontend/src/api/datasets/useExperimentItemBatchDeleteMutation.ts
apps/opik-frontend/src/api/traces/useTraceBatchDeleteMutation.ts
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsViewer.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesActionsButton.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesPage.tsx
apps/opik-frontend/src/components/shared/NoData/NoData.tsx

[OPIK-24] [UX improvements] Delete button in Actions menu when selecting multiple traces

---

apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsFiltersButton.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesPage.tsx
apps/opik-frontend/src/components/shared/FiltersButton/ColumnSelector.tsx
apps/opik-frontend/src/components/shared/FiltersButton/OperatorSelector.tsx
apps/opik-frontend/src/components/shared/LoadableSelectBox/LoadableSelectBox.tsx
apps/opik-frontend/src/components/shared/NewExperimentButton/NewExperimentButton.tsx

[OPIK-92] [UX Improvements] Add filters to Experiment page

---

apps/opik-documentation/documentation/docs/tracing/integrations/ollama.md

Added integration guide when using the `ollama` python package

Ollama integration docs

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsDetails.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/shared/DataTableCells/ResourceCell.tsx
apps/opik-frontend/src/components/shared/ResourceLink/ResourceLink.tsx

[OPIK-126] [UX Improvements] Add label for experiments that use a deleted dataset

---

apps/opik-frontend/src/components/shared/FiltersButton/FiltersButton.tsx

[OPIK-129] [UX Improvements] Show filter item by default when clicking on Filters

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/AddExperimentToCompareDialog.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsActionsButton.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/FilterExperimentsToCompareDialog.tsx

[OPIK-125] [UX Improvements] Inform user when trying to compare experiments that use different datasets

---

apps/opik-frontend/src/components/pages/ExperimentsPage/FilterExperimentsToCompareDialog.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx
apps/opik-frontend/src/components/shared/DataTableCells/CellWrapper.tsx
apps/opik-frontend/src/components/shared/DataTableCells/TextCell.tsx
apps/opik-frontend/src/components/shared/DataTableHeaders/TypeHeader.tsx
apps/opik-frontend/src/components/shared/NewExperimentButton/NewExperimentButton.tsx
apps/opik-frontend/src/components/shared/TooltipWrapper/TooltipWrapper.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/FeedbackScoreRowDeleteCell.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/FeedbackScoreTab.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/InputOutputTab.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/MatadataTab.tsx

OPIK-123 [UX Improvements] Align number columns to the right
[OPIK-137] [UX Improvements] Add Last updated column to Projects table
[OPIK-141] [UX Improvements] Display tooltips faster
[OPIK-143] [UX Improvements] Move Delete option out of submenu in Feedback scores tab
[OPIK-139] [UX Improvements] Add Token usage info in Metadata tab
Resolves #
[OPIK-137]: https://comet-ml.atlassian.net/browse/OPIK-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OPIK-141]: https://comet-ml.atlassian.net/browse/OPIK-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OPIK-143]: https://comet-ml.atlassian.net/browse/OPIK-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …

OPIK-123 [UX Improvements] Align number columns to the right

---

.github/ISSUE_TEMPLATE/feature_request.yaml

Added more information to the feature request template to decrease the chance of asking the same questions to the user.

[NA] Update feature_request.yaml

---

CONTRIBUTING.md

[OPIK-84] Add missing details to contributing md

---

README.md

Fix broken integrations table in README

Fix broken integrations table in README

---

.github/workflows/sdk-e2e-tests.yaml

build opik server while runing it for tests

---

.github/workflows/sdk-e2e-tests.yaml
.github/workflows/test_installer.yml
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/TestDropwizardAppExtensionUtils.java

[OPIK-130] Disable usage bi event in ci

---

apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDetailsPanel.tsx

[OPIK-183] [FE] Adding/deleting tags from trace panel on compare experiment page doesn't work

---

sdks/python/setup.py

Remove un-necessary dependency from the Python SDK

Remove un-necessary dependency from the Python SDK

---

apps/opik-frontend/e2e/pages/DatasetItemsPage.ts
apps/opik-frontend/e2e/pages/DatasetsPage.ts
apps/opik-frontend/e2e/pages/FeedbackDefinitionsPage.ts
apps/opik-frontend/e2e/pages/ProjectsPage.ts
apps/opik-frontend/e2e/pages/TracesPage.ts
apps/opik-frontend/e2e/pages/components/Columns.ts
apps/opik-frontend/e2e/pages/components/Filters.ts
apps/opik-frontend/e2e/pages/components/Table.ts
apps/opik-frontend/e2e/test-data/trace.ts
apps/opik-frontend/e2e/tests/datasets/dataset-items-page.spec.ts
apps/opik-frontend/e2e/tests/datasets/datasets-page.spec.ts
apps/opik-frontend/e2e/tests/feedback-definitions/feedback-definition.spec.ts
apps/opik-frontend/e2e/tests/projects/projects-page.spec.ts
apps/opik-frontend/e2e/tests/traces/trace-panel.spec.ts
apps/opik-frontend/e2e/tests/traces/traces-filters.spec.ts
apps/opik-frontend/e2e/tests/traces/traces-table.spec.ts
apps/opik-frontend/src/components/shared/FiltersButton/ColumnSelector.tsx
apps/opik-frontend/src/components/shared/FiltersButton/OperatorSelector.tsx
apps/opik-frontend/src/components/shared/FiltersButton/rows/DictionaryRow.tsx
apps/opik-frontend/src/components/shared/FiltersButton/rows/ListRow.tsx
apps/opik-frontend/src/components/shared/FiltersButton/rows/NumberRow.tsx
apps/opik-frontend/src/components/shared/FiltersButton/rows/StringRow.tsx
apps/opik-frontend/src/components/shared/SelectBox/SelectBox.tsx

Add e2e test coverage for filters on the traces page
Resolves #

[OPIK-155] [FE] Add E2E test coverage for traces filters

---

apps/opik-documentation/documentation/docs/faq.md
apps/opik-documentation/documentation/sidebars.ts

Add rate limits documentation

---

apps/opik-frontend/e2e/pages/components/Table.ts
apps/opik-frontend/e2e/test-data/trace.ts
apps/opik-frontend/e2e/tests/traces/feedback-score.spec.ts
apps/opik-frontend/e2e/tests/traces/trace-panel.spec.ts
apps/opik-frontend/e2e/tests/traces/traces-table.spec.ts

Add coverage for Traces/LLM Calls table cells visualization
Resolves #

[OPIK-155] [FE] Add E2E test coverage for traces/spans table visibility

---

apps/opik-frontend/src/api/datasets/useExperimentBatchDeleteMutation.ts
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentRowActionsCell.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsActionsButton.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/AddToDataset/AddToDatasetDialog.tsx

[OPIK-158] Allow users to delete experiments

---

apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx
apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/AddExperimentDialog.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/FeedbackDefinitionsPage/FeedbackDefinitionsPage.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesPage.tsx
apps/opik-frontend/src/components/shared/DataTableNoData/DataTableNoData.tsx
apps/opik-frontend/src/lib/utils.ts

[OPIK-207] [UX Improvements] Add docs link to Traces empty state

---

apps/opik-frontend/src/components/shared/FeedbackScoreTag/FeedbackScoreTag.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/FeedbackScoreValueCell.tsx

[OPIK-208] [UX Improvements] Make score reasons easier to compare

---

apps/opik-frontend/src/lib/utils.ts

[OPIK-207] [UX Improvements] Fix docs link in cloud

---

apps/opik-documentation/documentation/src/theme/DocItem/Content/index.tsx

Fix issues in notebook links on docs when URL has trailing `\`

Fix doc links

---

apps/opik-frontend/src/api/datasets/useCompareExperimentsList.ts
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx

OPIK-257 [FE] Add filter button to experiments compare page

---

apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx

[OPIK-260] [FE] Show by default updated_at column in Projects table

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/clickhouse-operator-install-bundle.yaml
deployment/helm_chart/opik/templates/clickhouseinstallation.yaml
deployment/helm_chart/opik/values.yaml

add service monitoring for clickhouse

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/AuthFilter.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/AuthService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/AuthTestUtils.java
apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/AuthServiceImplTest.java

see full details in ticket. 
for remote auth request were adding path to know which flow user is arriving from in the remote service 
Resolves #
added to remote auth tests. validated in wiremock

[OPIK-268] add path to remote auth request

---

deployment/helm_chart/opik/templates/clickhouseinstallation.yaml

Add permissions for opikmonitoring user in clickhouse

---

build_and_run.sh

fix local installation

---

apps/opik-frontend/src/components/layout/PartialPageLayout/PartialPageLayout.tsx
apps/opik-frontend/src/components/layout/WorkspaceGuard/WorkspaceGuard.tsx
apps/opik-frontend/src/plugins/comet/WorkspacePreloader.tsx
apps/opik-frontend/src/plugins/comet/types.ts
apps/opik-frontend/src/router.tsx

- Add trace limit reached warning
Resolves #

[CM-11588] Add support to trace limit reached warning

---

deployment/docker-compose/README.md

File extension didn't match and not running in detached mode.
N/A
Run the updated command successfully.
N/A

NO-JIRA: Fix docker-compose README.md

---

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java

OPIK-218
- Automated test for no migrated deprecated fields

[OPIK-218] Add deprecated fields to data field when data not migrated

---

apps/opik-frontend/src/components/layout/Breadcrumbs/Breadcrumbs.tsx

Resolves # OPIK-254
Manually
NA

[OPIK-254] [FE] Home breadcrumb redirect to the default workspace

---

apps/opik-documentation/documentation/docs/cookbook/watsonx.ipynb
apps/opik-documentation/documentation/docs/cookbook/watsonx.md
apps/opik-documentation/documentation/docs/tracing/integrations/watsonx.md

Updated WatsonX docs with links for watsonx API keys

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx
apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx

[OPIK-242] Show 'string' type icon for custom columns

---

apps/opik-frontend/src/components/ui/accordion.tsx

[OPIK-230] [UX improvements] Improve accordion sections to ensure expand discoverability

---

apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx
apps/opik-frontend/src/components/shared/ResizableSidePanel/ResizableSidePanel.tsx

[OPIK-243] [UX improvements] Unify icons to create clear patterns

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPage.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentFeedbackScoresTab/ExperimentFeedbackScoresTab.tsx

[OPIK-248] [UX improvements] Add new feedback scores tab in experiment comparison

---

apps/opik-documentation/documentation/docs/tracing/log_traces.mdx

This PR adds some documentation for the `@track(flush=True)` setting.

Added documentation for @track(flush=True)

---

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java
apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterStrategy.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java

Fixing errors regarding dictionary filter and some JSON path issues are actually related to Clickhouse bugs. Please see https://github.com/ClickHouse/ClickHouse/issues/60907
Apart from that, we are now handling errors to avoid a bad user experience.
OPIK-264

[OPIK-264] Fix 500 issues with dictionary filter

---

apps/opik-frontend/src/lib/utils.ts
apps/opik-frontend/src/plugins/comet/UserMenu.tsx

All documentation links point to the production website
Resolves #

[OPIK-296] [FE] All links to documentation should point to production documentation

---

apps/opik-frontend/package-lock.json
apps/opik-frontend/package.json
apps/opik-frontend/src/components/pages/TracesPage/TracesActionsButton.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesPage.tsx

Add project name as a part of exported CSV file name
Resolves # 464

[ISSUE-464] Add project name as a part of exported CSV file name

---

.github/workflows/sanity.yml

- Change name of the E2E sanity tests
Resolves #

Rename E2E sanity tests workflow

---

apps/opik-frontend/package-lock.json
apps/opik-frontend/package.json
apps/opik-frontend/patches/js-yaml+4.1.0.patch

Issue #475 Input/ Output YAML preview in sidebar, not looks good in case it contains

---

apps/opik-documentation/documentation/docs/changelog.md

Changelog update

---

apps/opik-documentation/documentation/docs/quickstart.mdx

Added missing track imports so example code would run.

[Docs] Added missing track imports

---

apps/opik-documentation/documentation/docs/quickstart.mdx
apps/opik-documentation/documentation/docs/roadmap.md

Updated roadmap

---

sdks/python/src/opik/configurator/configure.py

Update error message when `opik.configure` is run in a non-interactive mode

Update error message

---

deployment/helm_chart/opik/templates/deployment.yaml

add option to configure additional containers in opik pods

---

apps/opik-frontend/src/api/feedback/useProvideFeedbackMutation.ts
apps/opik-frontend/src/components/layout/SideBar/FeedbackDialog/ProvideFeedbackDialog.tsx
apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx
apps/opik-frontend/src/constants/app.ts
apps/opik-frontend/src/plugins/comet/UserMenu.tsx

* Added a provide feedback button to the UI
Resolves #

[OPIK-291] [FE]: add provide a feedback modal in the UI;

---

apps/opik-documentation/documentation/docs/quickstart.mdx
apps/opik-documentation/documentation/docs/tracing/log_traces.mdx

Fixed a small typo in docs;
Resolves #

[NA]: fix a typo of `users` in docs;

---

apps/opik-backend/entrypoint.sh

[NA] Fix OpenTelemtry service name setup

---

apps/opik-backend/src/main/java/com/comet/opik/api/Dataset.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemSummary.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java

Add number of dataset items in dataset page to be shown on UI
OPIK-167
Added corresponding check in integration tests

[OPIK-167] Add number of dataset items in dataset page

---

sdks/python/setup.py
sdks/python/src/opik/cli.py
sdks/python/src/opik/configurator/interactive_helpers.py

Due to issues observed in Google Colab, we decided to remove the Questionary library.
Tested manually in command line with `opik configure`

OPIK-157 Error when installing Opik from Colab (remove questionary dependency)

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Update issue template

---

.github/workflows/build_apps.yml
apps/opik-backend/Dockerfile
apps/opik-backend/install_rds_cert.sh

[OPIK-367] add RDS Certificate Authority Bundle to opik-backend image

---

apps/opik-backend/Dockerfile

use global cert

---

apps/opik-backend/src/main/java/com/comet/opik/api/Page.java
apps/opik-backend/src/main/java/com/comet/opik/api/Project.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/Direction.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortableFields.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortingFactory.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortingFactoryProjects.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortingField.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/sorting/SortingQueryBuilder.java
apps/opik-backend/src/main/java/com/comet/opik/utils/JsonUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
apps/opik-backend/src/test/resources/config-test.yml

This tickets adds sorting capabilities to the projects resource.
OPIK-265
Added 2 E2E tests and tested locally.

[OPIK-265] Projects list sorting

---

apps/opik-documentation/documentation/docs/cookbook/quickstart_notebook.ipynb

Update Quickstart notebook to not requires an external API Key

Update Quickstart notebook to not requires an external API Key

---

apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000005_add_prompt_version_to_experiments.sql

Add the experiment prompt version link to database
OPIK-321

[OPIK-321] Add experiment prompt version link

---

apps/opik-frontend/src/components/pages/DatasetItemsPage/AddEditDatasetItemDialog.tsx
apps/opik-frontend/src/hooks/useCodemirrorTheme.tsx

OPIK-377 Remove line highlighting in code blocks

---

apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsActionsPanel.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesActionsPanel.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesPage.tsx

[OPIK-273] [UX improvements] Remove Actions top-level button

---

apps/opik-frontend/src/components/shared/DataTable/DataTableColumnResizer.tsx

[OPIK-379] Introduce separator in table header

---

apps/opik-backend/src/main/java/com/comet/opik/api/BiInformationResponse.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/internal/UsageResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/internal/UsageResourceTest.java

Add endpoints for BI events data which will be consumed on a daily basis by E
Resolves #OPIK-320

[OPIK-320] Endpoints for BI events data

---

apps/opik-frontend/src/api/projects/useProjectByName.ts
apps/opik-frontend/src/components/redirect/RedirectProjects.tsx
apps/opik-frontend/src/router.tsx

A link: `/opik/aadereiko/redirect/projects?name=1`
Resolves #

[OPIK-325]: add link to project page

---

apps/opik-backend/src/main/java/com/comet/opik/api/Experiment.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java
apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000006_add_prompt_id_to_experiments.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/internal/UsageResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java

Add prompt id to experiments
OPIK-321

[OPIK-321] Add prompt id to experiments

---

apps/opik-frontend/patches/js-yaml+4.1.0.patch

[ISSUE-522] [Bug]: YAML is not correctly formatted for some strings

---

apps/opik-frontend/package-lock.json
apps/opik-frontend/package.json

- FE `happy-dom` version has a security vulnerability (upgraded)
Resolves #

Upgrade `happy-dom` version to fix vulnerability issues

---

apps/opik-frontend/src/components/pages/ExperimentsPage/charts/ExperimentChartContainer.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/charts/ExperimentChartTooltipContent.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/charts/ExperimentsChartsWrapper.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/table.tsx

- resolve issues after feedback
Resolves #

[OPIK-239] [UX improvements] Add charts of experiment table

---

apps/opik-backend/src/main/java/com/comet/opik/api/ProjectRetrieve.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java

Retrieve project by name
OPIK-389
- Retrieve project by name
- Sending empty name
- Sending null name

[OPIK-389] Retrieve project by name

---

apps/opik-documentation/documentation/docs/evaluation/manage_datasets.md

Fixed the recomment typo
Resolves #

[NA]: fix a recomment typo;

---

apps/opik-frontend/src/components/pages/ExperimentsPage/table.tsx

[ISSUE-612] [Bug]: Broken design in new Experiments page

---

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java

Add comment for future reference
NA

[NA] Add comment with reason why dataset items are not deleted

---

apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/PromptPage/ExperimentsTab/ExperimentsTab.tsx
apps/opik-frontend/src/components/shared/DataTablePagination/DataTablePagination.tsx
apps/opik-frontend/src/hooks/useGroupedExperimentsList.ts

- fix review comment
- add Prompt cell to Experiments Page
Resolves #

[OPIK-350] [Prompts Library][FE] Prompts details: Experiments tab

---

deployment/docker-compose/docker-compose.override.yaml
deployment/docker-compose/docker-compose.yaml

update docker-compose to use volumes

---

CONTRIBUTING.md

OPIK-330
- Add guidelines to migrations

[OPIK-330] Add guidelines to migrations

---

apps/opik-frontend/src/components/pages/QuickstartPage/Quickstart.tsx
apps/opik-frontend/src/plugins/comet/QuickstartPage.tsx
apps/opik-frontend/src/plugins/comet/types.ts

SageMaker integration:
Resolves #

[CM-11750] Remove colab links from the quickstart in the sagemaker integration

---

apps/opik-frontend/src/api/datasets/useDatasetItemByName.ts
apps/opik-frontend/src/components/redirect/RedirectDatasets.tsx
apps/opik-frontend/src/router.tsx

[OPIK-391]: [FE] add a redirect support to datasets;

---

.github/workflows/deploy_docs.yaml
apps/opik-documentation/documentation/docusaurus.config.ts
apps/opik-documentation/documentation/package-lock.json
apps/opik-documentation/documentation/package.json
apps/opik-documentation/documentation/src/theme/Root.tsx

Adding Segment to documentation

---

apps/opik-backend/Dockerfile

update base image for be

---

apps/opik-documentation/documentation/package-lock.json
apps/opik-documentation/documentation/package.json
apps/opik-frontend/package-lock.json

- Upgrade dependencies which have vulnerabilities issues
Resolves #

Upgrade FrontEnd dependencies

---

sdks/python/src/opik/api_objects/opik_client.py
sdks/python/src/opik/url_helpers.py

* Creating a dataset now has a message;
* Don't merge it before the FE https://github.com/comet-ml/opik/pull/642 ;
Resolves #

[OPIK-192]: [SDK] add a link to create dataset

---

apps/opik-frontend/src/api/datasets/useCompareExperimentsList.ts
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsPanel.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx

[OPIK-429] [FE] Truncate base64 images in experiment/dataset items table

---

apps/opik-documentation/documentation/docs/cookbook/anthropic.md
apps/opik-documentation/documentation/docs/tracing/integrations/langgraph.md
apps/opik-documentation/documentation/docs/tracing/log_multimodal_traces.md
apps/opik-documentation/documentation/docs/tracing/log_traces.mdx

Fix broken links

---

apps/opik-documentation/python-sdk-docs/requirements.txt

Fix broken SDK docs

---

README.md

I noticed a minor grammar error in the README file.
No issue

[NA] fix wrong grammar in README

---

apps/opik-frontend/src/components/App.tsx
apps/opik-frontend/src/components/shared/DataTableCells/FeedbackScoresCell.tsx
apps/opik-frontend/src/hooks/useCustomScrollbarClass.ts
apps/opik-frontend/src/main.scss

Chrome on Windows
Firefox on Windows
Resolves #

[NA]Add custom scrollbar styles for widows OSs

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentAddHeader.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsHeader.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsPanel.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsViewer.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/DataTab/DataTab.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/FeedbackScoresTab/ExperimentHeader.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/FeedbackScoresTab/FeedbackScoreCell.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/FeedbackScoresTab/FeedbackScoresTab.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/OutputTab/ExperimentDataset.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/OutputTab/ExperimentDatasetItems.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/OutputTab/OutputTab.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentFeedbackScoresTab/ExperimentFeedbackScoresTab.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/helpers.ts
apps/opik-frontend/src/components/shared/FeedbackScoresEditor/FeedbackScoresEditor.tsx
apps/opik-frontend/src/components/ui/resizable.tsx

[OPIK-438]: experiment sidebar restyle

---

apps/opik-frontend/src/api/traces/useTraceFeedbackScoreDeleteMutation.ts
apps/opik-frontend/src/api/traces/useTraceFeedbackScoreSetMutation.ts
apps/opik-frontend/src/lib/feedback-scores.tsx

Add request cancelation before making an optimistic update
Resolves #

[OPIK-448]  [FE] UI on editing feedback score is slow

---

apps/opik-backend/src/main/java/com/comet/opik/api/metrics/MetricType.java
apps/opik-backend/src/main/java/com/comet/opik/api/metrics/ProjectMetricResponse.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java

This PR finalizes the work on the project metrics. It includes:
- Tokens usage metric
- Cover edge cases
- Some refactors
OPIK-395
E2E tests covering the new functionality.
Ran the queries against production to confirm efficiency.

[OPIK-395] Project Metrics - add tokens usage

---

apps/opik-frontend/src/components/shared/DataTableHeaders/HeaderStatistic.tsx

[OPIK-398] Adjust padding in statistic headers

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortableFields.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortingFactoryDatasets.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceIntegrationTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java

Add sorting in order to have an ability to list datasets sorted by last created experiment
Resolves #OPIK-408
Added corresponding integration test
https://www.notion.so/cometml/Experiments-dashboard-1277124010a380ff8d4ecfc4cb5f72f6#1277124010a38063876dd5268c3b9ee1

[OPIK-408] List datasets sorted by last created experiment

---

apps/opik-documentation/documentation/docs/cookbook/ragas.md
apps/opik-documentation/documentation/docs/evaluation/metrics/custom_model.md
apps/opik-documentation/documentation/docs/reference/rest_api/get-span-stats.api.mdx
apps/opik-documentation/documentation/docs/reference/rest_api/get-trace-stats.api.mdx
apps/opik-documentation/documentation/docs/reference/rest_api/sidebar.ts
apps/opik-documentation/python-sdk-docs/source/Objects/LiteLLMChatModel.rst
apps/opik-documentation/python-sdk-docs/source/index.rst

Updated docs

---

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java

Update span cost during span update
Resolves #OPIK-478
Added corresponding integration tests
https://www.notion.so/cometml/Opik-Span-Cost-tracking-13c7124010a380a7ad36ced128a26dc7

[OPIK-478] Update span cost during span update

---

apps/opik-backend/src/main/java/com/comet/opik/domain/cost/ModelPrice.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java

NPE during span cost calculation
https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/MTgzOTEyNXxFWFR8U0VSVklDRXwxNTMwNTEwMjM2OTgxMzI0NjAy?account=1839125&duration=259200000&state=31869185-0cf6-bc53-c4ab-536cc2fcaec0
Resolves #OPIK-488
Added corresponding integration test

[OPIK-488] Fix NPE during span cost calculation

---

apps/opik-frontend/src/api/datasets/useDatasetsList.ts
apps/opik-frontend/src/hooks/useGroupedExperimentsList.ts

Groups list is sorted by last created experiments
Resolves #

[OPIK-409] [FE][Experiments page][Grouping and charts] Implement sorting of groups by last created experiment

---

.github/workflows/frontend_linter.yml
.github/workflows/lib-integration-tests-runner.yml
.github/workflows/python_sdk_linter.yml
.github/workflows/python_sdk_unit_tests.yml

[NA] update all relevant workflows to run on main

---

apps/opik-frontend/src/components/pages/TracesPage/AddToDataset/ExportToButton.tsx
apps/opik-frontend/src/components/pages/TracesPage/ExportToButton.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesActionsPanel.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx

[OPIK-492] [FR]: Export traces as JSON instead of CSV

---

apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java

Allow users to delete default project
Resolves #OPIK-451
Resolves #638 
Updated corresponding tests

[OPIK-451] Allow users to delete default project

---

apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricChart/MetricChart.tsx

Added hours for daily metrics
Resolves #

[OPIK-340]: add time for daily metrics;

---

apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx
apps/opik-frontend/src/components/shared/DataTableCells/CellWrapper.tsx
apps/opik-frontend/src/components/shared/DataTableCells/CostCell.tsx
apps/opik-frontend/src/components/shared/DataTableHeaders/TypeHeader.tsx
apps/opik-frontend/src/components/shared/FiltersButton/FilterRow.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/TraceDataViewer.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/treeRenderers.tsx
apps/opik-frontend/src/constants/filters.ts
apps/opik-frontend/src/lib/money.ts
apps/opik-frontend/src/types/shared.ts
apps/opik-frontend/src/types/traces.ts

The PR itself is ready but it waits for the bug fix of https://comet-ml.atlassian.net/browse/OPIK-502
Resolves #

[OPIK-440]: add estimated cost to traces / spans;

---

apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Fix filtering error for trace stats
Updated integration test

[OPIK-502] Fix filtering error for trace stats

---

apps/opik-backend/src/main/java/com/comet/opik/api/BatchDelete.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/FeedbackDefinitionResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/BatchDeleteUtils.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackDefinitionDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackDefinitionService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FeedbackDefinitionResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

This PR adds batch deleting capabilities to the following resources:
- Projects
- Datasets
- Feedback definitions
OPIK-368
Added E2E test to cover the new endpoints

[OPIK-368] add batch delete

---

apps/opik-frontend/src/lib/date.ts

[OPIK-463] Incorrect "Most recent experiment" date in Datasets table

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsDetails.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/CompareExperimentsFeedbackScoreCell.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/CompareExperimentsNameCell.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/CompareExperimentsOutputCell.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/VerticallySplitCellWrapper.tsx
apps/opik-frontend/src/components/pages/ExperimentsShared/table.tsx
apps/opik-frontend/src/components/shared/DataTable/utils.tsx
apps/opik-frontend/src/components/shared/DataTableCells/CellWrapper.tsx
apps/opik-frontend/src/components/shared/DataTableHeaders/HeaderWrapper.tsx
apps/opik-frontend/src/components/ui/table.tsx

[OPIK-512] Reduce table paddings

---

apps/opik-frontend/src/components/shared/DataTableHeaders/TypeHeader.tsx

Reverse sorting arrow 
Resolves #

[OPIK-506] [UX improvements] Sort date columns by date

---

apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/PromptService.java

[NA] fix typo

---

apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java

After discovering issues with usage cost last week I wanted to verify there is no effect on project metrics.

[NA] add coverage for empty usage

---

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/DatasetResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java

Reproduce the issue with test and make it pass.
OPIK-153
E2E that covers the reported issue (getById) and additional E2E test to cover the find functionality.

[OPIK-153] fix get experiment with deleted dataset

---

apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx
apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/FeedbackDefinitionsPage/FeedbackDefinitionsPage.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx
apps/opik-frontend/src/components/pages/PromptPage/CommitsTab/CommitsTab.tsx
apps/opik-frontend/src/components/pages/PromptPage/ExperimentsTab/ExperimentsTab.tsx
apps/opik-frontend/src/components/pages/PromptsPage/PromptsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/FeedbackScoreTab.tsx

[OPIK-430] Display created_by when available

---

apps/opik-frontend/e2e/pages/components/Filters.ts
apps/opik-frontend/e2e/tests/projects/projects-page.spec.ts
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectRowActionsCell.tsx
apps/opik-frontend/src/constants/projects.ts

[OPIK-466] [FE] Allow users to delete the Default project

---

apps/opik-frontend/src/components/shared/ApiKeyInput/ApiKeyInput.tsx
apps/opik-frontend/src/lib/utils.ts
apps/opik-frontend/src/plugins/comet/UserMenu.tsx

[OPIK-507] Mask users API keys

---

apps/opik-frontend/src/api/datasets/useDatasetBatchDeleteMutation.ts
apps/opik-frontend/src/api/datasets/useDatasetItemBatchDeleteMutation.ts
apps/opik-frontend/src/api/feedback-definitions/useFeedbackDefinitionBatchDeleteMutation.ts
apps/opik-frontend/src/api/projects/useProjectBatchDeleteMutation.ts
apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsActionsPanel.tsx
apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx
apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsActionsPanel.tsx
apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx
apps/opik-frontend/src/components/pages/FeedbackDefinitionsPage/FeedbackDefinitionsActionsPanel.tsx
apps/opik-frontend/src/components/pages/FeedbackDefinitionsPage/FeedbackDefinitionsPage.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsActionsPanel.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx

[OPIK-374] Add bulk actions to all tables

---

apps/opik-frontend/src/api/prompts/usePromptBatchDeleteMutation.ts
apps/opik-frontend/src/components/pages/PromptsPage/PromptsActionsPanel.tsx
apps/opik-frontend/src/components/pages/PromptsPage/PromptsPage.tsx

[OPIK-374] Add batch actions to prompts table

---

apps/opik-documentation/documentation/rest_api/opik.yaml
sdks/code_generation/fern/openapi/openapi.yaml
sdks/python/src/opik/rest_api/prompts/client.py
sdks/typescript/src/opik/rest_api/api/resources/prompts/client/Client.d.ts
sdks/typescript/src/opik/rest_api/api/resources/prompts/client/Client.js

This adds OpenAPI spec and updates relevant clients after merging #806 
OPIK-523

[OPIK-523] add OpenAPI spec and update relevant clients

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/bi/DailyUsageReportJob.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/bi/OpikGuiceyLifecycleEventListener.java

There is a weird behavior in a Cloud environment where the job runs every hour instead of Midnight. I couldn't reproduce it locally, but the task should be disabled in the cloud.  This PR attempts to fix the disable flag of the Job
OPIK-473

[OPIK-473] Fix enabled flag

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java

In a particular edge case that we still couldn't reproduce, we are getting a null pointer when assigning the project ID to the spans. I'm adding a few logs to collect more info.
OPIK-416

[OPIK-416] Add logs to understand issue

---

apps/opik-backend/src/main/java/com/comet/opik/api/Project.java
apps/opik-backend/src/main/java/com/comet/opik/api/ProjectUpdate.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java

Allow empty string as project description

[OPIK-541] Allow empty string as project description

---

apps/opik-backend/src/main/java/com/comet/opik/OpikApplication.java
apps/opik-backend/src/main/java/com/comet/opik/api/error/JsonInvalidFormatExceptionMapper.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java

Return detailed error message for json deserialization exceptions
Added corresponding integration test

[OPIK-532] Return detailed error message for json deserialization exceptions

---

sdks/python/src/opik/id_helpers.py

Add basic UUIDv4 to UUIDv7 conversion code to be used by integrations

Add basic UUID4 to UUID7 conversion code

---

apps/opik-documentation/documentation/dev_script.sh
apps/opik-documentation/documentation/docs/changelog.md
apps/opik-documentation/documentation/docs/tracing/sdk_configuration.mdx

Updated docs with SSL updates

---

apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Additional tests as a follow up for OPIK-486

[OPIK-486] Additional tests

---

sdks/python/src/opik/integrations/langchain/base_llm_patcher.py
sdks/python/src/opik/integrations/langchain/openai_run_helpers.py
sdks/python/src/opik/integrations/langchain/opik_tracer.py
sdks/python/tests/library_integration/langchain/test_langchain.py

Send `provider` and `model` names with span data
Manually tested

OPIK-519 [SDK] Langchain integration: cost tracking for openai calls

---

apps/opik-frontend/.eslintrc
apps/opik-frontend/package-lock.json
apps/opik-frontend/package.json
apps/opik-frontend/src/components/shared/MermaidDiagram/MermaidDiagram.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/AgentGraphTab.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/TraceDataViewer.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDetailsPanel.tsx
apps/opik-frontend/src/constants/traces.ts
apps/opik-frontend/src/types/traces.ts

[OPIK-551] Display agent graph in Trace sidebar

---

apps/opik-frontend/src/components/layout/Breadcrumbs/Breadcrumbs.tsx
apps/opik-frontend/src/components/pages/HomePage/GetStartedSection.tsx
apps/opik-frontend/src/components/pages/HomePage/HomePage.tsx
apps/opik-frontend/src/lib/utils.ts
apps/opik-frontend/src/router.tsx

[OPIK-564] Add homepage to breadcrumbs

---

apps/opik-documentation/documentation/package-lock.json
apps/opik-frontend/package-lock.json

- Upgrade dependencies due low/medium vulnerabilities
- https://github.com/comet-ml/opik/security/dependabot/26
- https://github.com/comet-ml/opik/security/dependabot/28
- https://github.com/comet-ml/opik/security/dependabot/27
Resolves #

Upgrade frontend dependencies (low/medium vulnerabilities)

---

apps/opik-frontend/src/components/layout/PageLayout/PageLayout.tsx
apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx
apps/opik-frontend/src/components/pages/HomePage/EvaluationSection.tsx

[OPIK-563] Add sections to the sidebar menu

---

apps/opik-frontend/Dockerfile

use specific base image for opik-frontend

---

apps/opik-frontend/src/components/shared/DataTableCells/IdCell.tsx
apps/opik-frontend/src/components/shared/DataTableCells/LinkCell.tsx

OPIK-602 [UX improvements] Allow IDs to grow when column is resized

---

apps/opik-documentation/python-sdk-docs/source/Objects/ExperimentItem.rst
apps/opik-documentation/python-sdk-docs/source/Objects/ExperimentItemContent.rst
apps/opik-documentation/python-sdk-docs/source/Objects/ExperimentItemReferences.rst
apps/opik-documentation/python-sdk-docs/source/index.rst

Update reference doc following #868\

Update reference doc following #868

---

apps/opik-frontend/src/components/pages/DatasetItemsPage/AddEditDatasetItemDialog.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx
apps/opik-frontend/src/components/shared/DataTableCells/ErrorCell.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/BaseTraceDataTypeIcon.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/ErrorTab.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/TraceDataViewer.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/treeRenderers.tsx
apps/opik-frontend/src/components/ui/alert.tsx
apps/opik-frontend/src/components/ui/tooltip.tsx
apps/opik-frontend/src/types/traces.ts

[OPIK-621] [Error tracking] [FE] Add Trace/Span error tracking support

---

apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/hooks/useGroupedExperimentsList.ts

[OPIK-576] [FR]: Consistent Experiments Dataset focus after page refresh or add refresh button (30s autorefresh is too long)

---

apps/opik-documentation/python-sdk-docs/requirements.txt

Add Haystack dependency to Python Reference docs

Added haystack dependency for Python reference docs

---

apps/opik-frontend/src/api/datasets/useExperimentBatchDeleteMutation.ts

[OPIK-635] [Experiments page] After deleting all experiments page shows empty state message for few seconds

---

README.md

[NA] Update FR tip in readme

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/LlmProviderApiKeyResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/LlmProviderApiKeyDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/LlmProviderApiKeyService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/LlmProviderApiKeyResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/LlmProviderApiKeyResourceTest.java

Delete LLM Provider Api key endpoint
Added integration test, checked manually with local deployment

[OPIK-627] Delete LLM Provider Api key endpoint

---

apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx
apps/opik-frontend/src/components/shared/DataTable/DataTable.tsx
apps/opik-frontend/src/components/shared/DataTableCells/DurationCell.tsx
apps/opik-frontend/src/components/shared/DataTableHeaders/HeaderStatistic.tsx
apps/opik-frontend/src/components/shared/DataTableHeaders/HeaderWrapper.tsx
apps/opik-frontend/src/components/shared/DataTableHeaders/TypeHeader.tsx
apps/opik-frontend/src/components/shared/FiltersButton/FilterRow.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/TraceDataViewer.tsx
apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.tsx
apps/opik-frontend/src/constants/filters.ts
apps/opik-frontend/src/constants/shared.ts
apps/opik-frontend/src/lib/filters.ts
apps/opik-frontend/src/lib/table.ts
apps/opik-frontend/src/lib/utils.ts
apps/opik-frontend/src/types/shared.ts
apps/opik-frontend/src/types/traces.ts

[OPIK-623] [FE] Add duration column to Traces/LLM Calls tables

---

apps/opik-documentation/documentation/src/theme/Root.tsx

Updating Dify APP name don't seems to works, so I duplicated the app with a better name instead.

Update Dify Chatbot id

---

apps/opik-backend/src/main/java/com/comet/opik/api/Prompt.java
apps/opik-backend/src/main/java/com/comet/opik/api/PromptVersion.java
apps/opik-backend/src/main/java/com/comet/opik/api/ProviderApiKeyUpdate.java
apps/opik-backend/src/main/java/com/comet/opik/domain/PromptDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/PromptService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/PromptVersionDAO.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/PromptVersionColumnMapper.java
apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000007_add_change_description_metadata_to_prompt_version.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/PromptResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/podam/manufacturer/PromptVersionManufacturer.java

Add metadata and change_description fields to prompt_version

[OPIK-626] Add metadata and change_description to prompt_version

---

apps/opik-frontend/src/api/prompts/useCreatePromptVersionMutation.ts
apps/opik-frontend/src/api/prompts/usePromptCreateMutation.ts
apps/opik-frontend/src/components/pages/DatasetItemsPage/AddEditDatasetItemDialog.tsx
apps/opik-frontend/src/components/pages/PromptPage/CommitsTab/CommitsTab.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/EditPromptDialog.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/PromptTab.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/UseThisPromptDialog.tsx
apps/opik-frontend/src/components/pages/PromptsPage/AddEditPromptDialog.tsx
apps/opik-frontend/src/hooks/useBooleanTimeoutState.ts
apps/opik-frontend/src/types/prompts.ts

[OPIK-579] [FR]: add output formats as it own fields for prompts

---

apps/opik-frontend/src/components/pages/PromptPage/PromptTab/PromptTab.tsx

[OPIK-579] Change component to present metadata

---

apps/opik-backend/src/main/java/com/comet/opik/api/ProviderApiKey.java
apps/opik-backend/src/main/java/com/comet/opik/api/ProviderApiKeyUpdate.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/LlmProviderApiKeyResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/LlmProviderApiKeyDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/LlmProviderApiKeyService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/EncryptionUtils.java
apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000008_add_name_to_provider_api_key.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/LlmProviderApiKeyResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/LlmProviderApiKeyResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/podam/PodamFactoryUtils.java
apps/opik-backend/src/test/java/com/comet/opik/podam/manufacturer/ProviderApiKeyManufacturer.java
apps/opik-backend/src/test/java/com/comet/opik/podam/manufacturer/ProviderApiKeyUpdateManufacturer.java

Add fields to LLM Provider Api Key endpoints.
Return masked raw api key.
Added/updated corresponding integration tests

[OPIK-616] Add fields to LLM Provider Api Key endpoints

---

apps/opik-documentation/documentation/docs/tracing/log_traces.mdx

docs: update log_traces.mdx

---

apps/opik-documentation/documentation/docs/tracing/integrations/llama_index.md

Fix llamaIndex docs

---

apps/opik-documentation/documentation/docs/roadmap.md

Updated the roadmap documentation page

Update to Opik roadmap

---

apps/opik-documentation/documentation/docs/quickstart.mdx

This pull request includes the following updates:
1. **Fix Import Error**: Resolved an issue with the `track` decorator import by using the correct module.
2. **LangChain Updates**: Adjusted the LangChain usage to align with the latest version. 
- Switched from `LLMChain.run` to `LLMChain.invoke`.
- Utilized the `|` pipe operator for chain creation.
3. **Bug Fix**: Corrected the OpenAI client call to ensure compatibility with the updated syntax.
1. Verified the imports load without error.
2. Tested the `generate_response` function to confirm that the OpenAI client call produces the expected outputs.
3. Validated LangChain updates:
- Ensured the `LLMChain.invoke` method works as intended.
- Confirmed the `|` operator properly links the prompt and chain.

[Docs]: Update quickstart.mdx

---

apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java

This fixes an NPE in the find projects logic.
OPIK-709
Added a test that covers the new logic.

[OPIK-709] fix NPE in find projects

---

apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluator.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorModel.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/LlmAsJudgeAutomationRuleEvaluatorModel.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

[NA] apply spotless

---

apps/opik-backend/src/main/java/com/comet/opik/OpikApplication.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/EncryptionUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/TestDropwizardAppExtensionUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/TestHttpClientUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/internal/UsageResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ChatCompletionsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FeedbackDefinitionResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/PromptResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/RemoveAuthServiceTest.java
apps/opik-backend/src/test/java/com/comet/opik/infrastructure/aws/rds/MysqlRdsIamE2eTest.java
apps/opik-backend/src/test/java/com/comet/opik/utils/PaginationUtilsTest.java

[NA] Fix test visibility

---

apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentItemSearchCriteria.java
apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentItemStreamRequest.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemResultMapper.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemMapper.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreMapper.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/AssertionUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java

StreamExperimentItems endpoint return full content for experiment items
Covered by integration test

[OPIK-580] StreamExperimentItems endpoint return full content for experiment items

---

.github/workflows/documentation_codeblock_tests.yml
apps/opik-documentation/documentation/requirements.txt
apps/opik-documentation/documentation/sidebars.ts

Update Github actions for codeblock tests

Update github actions

---

tests_end_to_end/page_objects/PromptPage.py

Name of edit prompt button changed to "Create new commit", reflecting this in tests

edit prompt button name

---

.github/workflows/backend_formatting_check.yml
CONTRIBUTING.md
apps/opik-backend/src/main/java/com/comet/opik/api/error/CannotDeleteProjectException.java

Enforced Java backend code formatting on our CI, both PRs and main. 
A new workflow will fail if code isn't properly formatted.
Added documentation to let users know how to format the code automatically.
N/A
Tested in this PR. See previous commits:
- Error case.
- Success case.
- https://github.com/diffplug/spotless

NO-JIRA: Add Spotless backend formatting workflow

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/redis/RedissonLockService.java

More accurate logs for `RedissonLockService`.
N/A
Verified by running `RedissonLockServiceIntegrationTest`.
N/A

NO-JIRA: Update locking service logs

---

apps/opik-frontend/src/api/datasets/useDatasetCreateMutation.ts
apps/opik-frontend/src/api/projects/useProjectCreateMutation.ts
apps/opik-frontend/src/components/pages/ProjectsPage/AddEditProjectDialog.tsx
apps/opik-frontend/src/lib/utils.ts

Automatic redirection to project page after successful creation
Resolves #

[OPIK-737] redirect to project page after successful creation

---

apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/PlaygroundOutputActions.tsx
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/useActionButtonActions.ts
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPage.tsx
apps/opik-frontend/src/components/shared/LoadableSelectBox/LoadableSelectBox.tsx
apps/opik-frontend/src/components/shared/LoadableSelectBox/NoOptions.tsx
apps/opik-frontend/src/components/shared/SliderInputControl/SliderInputControl.tsx
apps/opik-frontend/src/store/PlaygroundStore.ts

[OPIK-655]: dataset playground fixes

---

apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/PlaygroundOutputActions.tsx
apps/opik-frontend/src/components/shared/LoadableSelectBox/LoadableSelectBox.tsx

[OPIK-655]: add truncate;

---

apps/opik-documentation/documentation/docs/changelog.md

Updated changelog

---

apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/PlaygroundOutputActions.tsx
apps/opik-frontend/src/components/shared/TooltipWrapper/TooltipWrapper.tsx

[OPIK-742]: open an error tooltip for a disabled run button;

---

apps/opik-frontend/src/api/datasets/useDatasetUpdateMutation.ts
apps/opik-frontend/src/components/pages/DatasetsPage/AddEditDatasetDialog.tsx
apps/opik-frontend/src/components/pages/DatasetsPage/DatasetRowActionsCell.tsx
apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/AddToDataset/AddToDatasetDialog.tsx

OPIK-775 [FE] Add ability to edit dataset description from UI

---

sdks/python/src/opik/api_objects/opik_client.py
sdks/python/src/opik/config.py
sdks/python/src/opik/logging_messages.py
sdks/python/src/opik/message_processing/message_processors.py

This PRs adds some informative error messages when obvious misconfigurations are detected by the opik library.
In addition traceback is no longer showed in background message processor when it catches a rest `ApiError`

[NA] Add misconfiguration check to Opik.__init__

---

apps/opik-frontend/src/components/pages/TracesPage/AddToDataset/AddToDatasetDialog.tsx

Modified validation, accepted everything except `undefined`
Resolves #

[OPIK-799] Can't add trace to dataset

---

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Fix project not found illegal state

[OPIK-781] Fix project not found illegal state

---

deployment/helm_chart/opik/Chart.lock
deployment/helm_chart/opik/Chart.yaml
deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml
deployment/helm_chart/opik/templates/clickhouseinstallation.yaml
deployment/helm_chart/opik/values.yaml

Add condition for clickhouse installation in order to support an option to use external clickhouse
Resolves #

OPIK-802: add an option to use external clickhouse

---

CONTRIBUTING.md
sdks/python/README.md

Added the first version of python coding guidelines page.

Contribution guide

---

apps/opik-documentation/documentation/docs/cookbook/ragas.ipynb

Fix Ragas notebook hanging issue

Update Ragas notebook

---

apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Anthropic.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Bedrock.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/DSPy.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/FunctionDecorators.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Gemini.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Groq.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Haystack.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/LangChain.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/LangGraph.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/LiteLLM.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/LlamaIndex.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/OpenAI.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Ragas.py

Add smaller code snippets for the quickstart page

---

apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/useActionButtonActions.ts
apps/opik-frontend/src/lib/batches.ts

https://github.com/comet-ml/opik/pull/1072
Resolves #

[OPIK-656]: improvements of experiment playground log pr's code;

---

apps/opik-frontend/src/api/playground/createLogPlaygroundProcessor.ts
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompts/PlaygroundPrompt.tsx
apps/opik-frontend/src/lib/playground.ts

[OPIK-656]: fix the bug when there is no dataset and avoid logging an experiment;

---

apps/opik-frontend/src/components/pages-shared/traces/TracesPathsAutocomplete/TracesPathsAutocomplete.tsx
apps/opik-frontend/src/lib/utils.ts

[OPIK-839] [FE] Remove not leaves nodes(subtrees) from the autocomplete component in the rules popup

---

apps/opik-backend/src/main/java/com/comet/opik/api/Comment.java
apps/opik-backend/src/main/java/com/comet/opik/api/Experiment.java
apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentItem.java
apps/opik-backend/src/main/java/com/comet/opik/api/Trace.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/CommentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/CommentService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java
apps/opik-backend/src/main/java/com/comet/opik/utils/ErrorUtils.java
apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000010_add_comments_table.sql
apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000011_add_comments_table.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

[OPIK-757] New endpoints for Comments

---

apps/opik-frontend/src/main.scss

-custom scroll hover for PC
Resolves #

[OPIK-785] custom scroll hover for PC

---

sdks/python/examples/demo_data_generator.py

- Add batching + flush to the demo project

Improve demo project script (flush + batching)

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsViewer.tsx

[OPIK-860] Add text to Open trace button on experiment sidebars

---

apps/opik-frontend/src/api/prompts/useCreatePromptVersionMutation.ts
apps/opik-frontend/src/components/pages/PromptPage/CommitsTab/CommitsTab.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/EditPromptDialog.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/PromptTab.tsx
apps/opik-frontend/src/types/prompts.ts

[OPIK-678] Add support for `change_description` field in the prompt commit

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/configmap-backend.yaml
deployment/helm_chart/opik/templates/deployment.yaml
deployment/helm_chart/opik/values.yaml

Fix Opik misconfiguration in the helm chart

---

apps/opik-frontend/src/api/datasets/useDatasetCreateMutation.ts
apps/opik-frontend/src/api/prompts/usePromptCreateMutation.ts
apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx
apps/opik-frontend/src/components/pages/PromptsPage/AddEditPromptDialog.tsx

- Added auto redirect to a prompt page after creating it 
- Added auto redirect to a dataset page after creating it 
Resolves #
- Manual testing
NA

[OPIK-820] [UX improvements] Add automatic redirection to 'Datasets'and 'Prompt library item pages

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/helpers.ts
apps/opik-frontend/src/components/pages/HomePage/ObservabilitySection.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx
apps/opik-frontend/src/components/shared/DataTableHeaders/HeaderStatistic.tsx
apps/opik-frontend/src/lib/utils.ts
apps/opik-frontend/src/types/datasets.ts
apps/opik-frontend/src/types/projects.ts
apps/opik-frontend/src/types/shared.ts
apps/opik-frontend/src/types/traces.ts

[OPIK-625] [FE] Add average values for duration, usage, and total cost estimation in project list table

---

sdks/python/setup.py

Removed "<0.28.0" version restriction

[FR] Relax httpx dependency restriction

---

apps/opik-frontend/src/components/pages/PromptPage/CommitsTab/CommitsActionsPanel.tsx
apps/opik-frontend/src/components/pages/PromptPage/CommitsTab/CommitsTab.tsx
apps/opik-frontend/src/components/pages/PromptPage/CommitsTab/ComparePromptVersionDialog.tsx
apps/opik-frontend/src/components/shared/SelectBox/SelectBox.tsx
apps/opik-frontend/src/types/shared.ts

[OPIK-862] Allow users to diff prompt commits

---

apps/opik-backend/src/main/java/com/comet/opik/OpikApplication.java
apps/opik-backend/src/main/java/com/comet/opik/api/error/JsonProcessingExceptionMapper.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/LlmProviderApiKeyResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/LlmProviderApiKeyResourceTest.java

Provide more informative error message for 400 unable to process json

[OPIK-897] Provide more informative error message for 400 unable to process json

---

apps/opik-frontend/src/components/pages-shared/onboarding/ConfigureEnvCode/ConfigureEnvCodeCore.tsx
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/IntegrationTemplate.tsx
apps/opik-frontend/src/constants/shared.ts
apps/opik-frontend/src/lib/utils.ts

- share config building logic
Resolves #

[OPIK-902] share config building logic

---

apps/opik-backend/src/main/resources/openapi_template.yml
apps/opik-documentation/documentation/rest_api/opik.yaml

Updated Rest API home page

---

apps/opik-documentation/documentation/docs/tracing/cost_tracking.md

Also mention that we now estimate cost for VertexAI text models too
Resolves #

Add docs for manual cost tracking

---

.github/workflows/build_apps.yml
apps/opik-backend/Dockerfile

[OPIK-954] use latest base image without vulnerabilities for opik-backend

---

.github/workflows/build_apps.yml

update build GH workflow

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceAnnotateViewer/AnnotateRow.tsx

- deselect score if field is empty or double-click
Resolves #

[OPIK-852] deselect score if field is empty or double-click

---

apps/opik-backend/src/main/java/com/comet/opik/api/AuthenticationErrorResponse.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/TestHttpClientUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/AutomationRuleEvaluatorResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AuthenticationResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FeedbackDefinitionResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/PromptResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/RemoteAuthServiceTest.java

Improve error messages for authentication

[OPIK-816 Improve error messages for authentication

---

apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/test/resources/config-test.yml

- Use final in all queries
- Add fallback query
OPIK-936
Tested Manually

OPIK-936: Use final in all queries and add correct fallback

---

apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluator.java
apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluatorUpdate.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceDeprecated.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/AutomationRuleEvaluatorResourceClientDeprecated.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/events/OnlineScoringEngineTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceDeprecatedTest.java
apps/opik-backend/src/test/java/com/comet/opik/domain/AutomationRuleEvaluatorServiceImplTest.java

Refactor AutomationRule endpoint to support workspace level

[OPIK-724] Refactor AutomationRule endpoint to support workspace level

---

apps/opik-documentation/documentation/docs/changelog.md
apps/opik-documentation/documentation/docs/evaluation/overview.mdx
apps/opik-documentation/documentation/docs/home.md
apps/opik-documentation/documentation/docs/quickstart.mdx
apps/opik-documentation/documentation/docs/tracing/log_traces.mdx

Added changelog and JS docs

---

apps/opik-frontend/src/components/pages-shared/onboarding/CodeExecutor/CodeExecutor.tsx
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/FrameworkIntegrationsContent.tsx
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/IntegrationTemplate.tsx
apps/opik-frontend/src/components/pages-shared/onboarding/QuickstartDialog/QuickstartDialog.tsx

[OPIK-982] fix dialogclose bug

---

.github/workflows/typescript_sdk_linter.yml
.github/workflows/typescript_sdk_unit_tests.yml
sdks/typescript/eslint.config.js
sdks/typescript/package-lock.json
sdks/typescript/package.json
sdks/typescript/src/opik/client/BatchQueue.ts
sdks/typescript/src/opik/decorators/track.ts
sdks/typescript/src/opik/integrations/vercel/exporter.ts
sdks/typescript/tests/track.test.ts

- Add GitHub actions for: ESLint + TypeScript types + Unit tests
- Fix ESLint errors/warnings

[OPIK-927] [TypeScript SDK] Add CI/CD flows

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringLlmAsJudgeScorer.java
apps/opik-backend/src/main/java/com/comet/opik/domain/llm/ChatCompletionService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/AutomationRuleEvaluatorResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/events/OnlineScoringEngineTest.java

Add more info to use facing error logs
OPIK-856

OPIK-856: Add more info to use facing error logs

---

.github/workflows/publish_typescript_sdk.yml
.github/workflows/typescript_sdk_unit_tests.yml
sdks/typescript/src/opik/client/BatchQueue.ts
sdks/typescript/src/opik/client/Client.ts
sdks/typescript/src/opik/client/SpanBatchQueue.ts
sdks/typescript/src/opik/client/SpanFeedbackScoresBatchQueue.ts
sdks/typescript/src/opik/client/TraceBatchQueue.ts
sdks/typescript/src/opik/client/TraceFeedbackScoresBatchQueue.ts
sdks/typescript/src/opik/tracer/Span.ts
sdks/typescript/src/opik/tracer/Trace.ts
sdks/typescript/tests/scores.test.ts

- Add `.score` methods in the `Trace` and `Span` (adding them automatically to the batch mechanism)
- Add publish TypeScript workflow
- Add a matrix of testing for different Node versions

[OPIK-929] [TypeScript SDK] Add feedback scores support

---

.github/workflows/end2end_suites.yml

Replace old runner image that will be not supported soon
Resolves #

Replace old runner image

---

.github/workflows/typescript_sdk_publish.yml
sdks/typescript/package-lock.json
sdks/typescript/package.json

- Fix `git push` step
- Rename according to the other workflows (TypeScript SDK) prefix + align config/message to other workflows
- Manually bumping TS SDK version due: https://github.com/comet-ml/opik/actions/runs/13284440074 fail

[OPIK-560] [TypeScript SDK] Improve publish workflow

---

apps/opik-frontend/src/api/traces/useCreateSpanCommentMutation.ts
apps/opik-frontend/src/api/traces/useCreateTraceCommentMutation.ts
apps/opik-frontend/src/api/traces/useSpanCommentsBatchDeleteMutation.ts
apps/opik-frontend/src/api/traces/useTraceCommentsBatchDeleteMutation.ts
apps/opik-frontend/src/api/traces/useUpdateSpanCommentMutation.ts
apps/opik-frontend/src/api/traces/useUpdateTraceCommentMutation.ts
apps/opik-frontend/src/types/comment.ts
apps/opik-frontend/src/types/traces.ts

- API integration to get/patch/delete/update trace/span comments
Resolves #

[OPIK-994] comments API integration

---

.github/workflows/documentation_image_optimizer.yml

Add workflow dispatch for image optimization

Add workflow dispatch for image optimization

---

sdks/python/src/opik/forwarding_server/app.py

Fix CORS proxy for Comet staging environment

Fix CORS proxy for Comet staging environment

---

apps/opik-documentation/documentation/fern/docs/tracing/sdk_configuration.mdx
apps/opik-documentation/python-sdk-docs/source/Objects/DistributedTraceHeadersDict.rst
apps/opik-documentation/python-sdk-docs/source/index.rst
sdks/python/src/opik/types.py

Update reference doc for recent changes

---

apps/opik-documentation/documentation/fern/docs.yml
apps/opik-documentation/documentation/fern/docs/reference/overview.mdx
apps/opik-documentation/documentation/fern/docs/reference/typescript-sdk/overview.mdx

Added Typescript docs

---

apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx

Save the state about pagination, search, and selection in the URL.
Resolves #

[OPIK-1034] [FR]: Fix the link in the project list pagination

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/deployment.yaml
deployment/helm_chart/opik/values.yaml

[DEV-2613] add option to disable data migration

---

apps/opik-documentation/documentation/fern/docs.yml

Added redirects for old reference docs url structure

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/values.yaml

[DEV-2613] add option disable data migration - fix typo

---

deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml

[OPIK-1057] add resources definition to clickhouse backup job

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/AuthService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RequestContext.java
apps/opik-backend/src/main/java/com/comet/opik/utils/AsyncUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AuthenticationResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceIntegrationTest.java
apps/opik-backend/src/test/java/com/comet/opik/domain/TraceServiceImplTest.java
apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/AuthServiceImplTest.java

Add support for default workspace

[OPIK-56] Add support for default workspace

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/OpenTelemetryResource.java

[NA] Fix compilation error

---

apps/opik-documentation/documentation/fern/docs.yml
apps/opik-documentation/documentation/fern/docs/tracing/opentelemetry/overview.mdx

Add first version of OTel documentation

Add first version of OTel documentation

---

sdks/python/src/opik/evaluation/engine/engine.py
sdks/python/src/opik/evaluation/evaluator.py
sdks/python/src/opik/evaluation/metrics/arguments_helpers.py
sdks/python/src/opik/evaluation/rest_operations.py
sdks/python/src/opik/evaluation/types.py
sdks/python/tests/library_integration/aisuite/requirements.txt
sdks/python/tests/library_integration/aisuite/test_aisuite.py
sdks/python/tests/unit/evaluation/metrics/test_arguments_helpers.py
sdks/python/tests/unit/evaluation/test_evaluate.py

The score key mapping actually works, but we decided to add a more detailed message about unused keys if an exception occurs
tests are added/updated

[OPIK-926] [SDK] Evaluate scoring_key_mapping don't seems to be working

---

apps/opik-backend/src/main/java/com/comet/opik/api/Trace.java
apps/opik-backend/src/main/java/com/comet/opik/api/TraceUpdate.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000014_add_thread_id_to_traces.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

OPIK-985: Add thread id to traces

---

apps/opik-frontend/src/api/traces/useCreateTraceCommentMutation.ts
apps/opik-frontend/src/api/traces/useTraceCommentsBatchDeleteMutation.ts
apps/opik-frontend/src/api/traces/useUpdateTraceCommentMutation.ts
apps/opik-frontend/src/components/layout/PageLayout/PageLayout.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/CommentsViewer/CommentsViewerCore.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceAnnotateViewer/AnnotateRow.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/TraceDataViewerActionsPanel.tsx
apps/opik-frontend/src/components/pages-shared/traces/UserComment/UserCommentHoverList.tsx
apps/opik-frontend/src/components/shared/FeedbackScoreTag/FeedbackScoreTag.tsx
apps/opik-frontend/src/components/ui/toggle.tsx
apps/opik-frontend/tailwind.config.ts

- small UI/UX improvements
Resolves #

[OPIK-827] comments UX improvements

---

apps/opik-documentation/documentation/fern/docs/tracing/export_data.mdx

This PR adds documentation for the new `AND` connector (#1270) in query searches from the Python SDK.
It also updates the surrounding query language docs.

Add documentation for AND in search queries

---

apps/opik-documentation/documentation/fern/docs/self-host/kubernetes.mdx

add configuration snippet for external clickhouse

---

apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Add Missing test to find traces by thread id

OPIK-985: Add thread id filter to find traces endpoint

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Add error logs to bug report.
Explicitly mentioned code snippets too.
N/A
- Reviewed in preview.
N/A

NO-JIRA: Add error logs to bug report

---

apps/opik-frontend/src/components/pages/HomePage/ObservabilitySection.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx

[OPIK-1115] add trace count column

---

apps/opik-documentation/documentation/fern/docs.yml
apps/opik-documentation/documentation/fern/docs/tracing/integrations/deepseek.mdx

Add DeepSeek integration doc

---

apps/opik-documentation/documentation/fern/docs.yml

Updated fern configuration

---

apps/opik-documentation/documentation/fern/docs.yml

Update Fern for SEO optimization

Updated custom domain

---

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/SpanResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Add cost calculation support for google_ai provider. Now we also use `provider` field for cost calculation

[OPIK-1085] Add cost calculation support for google_ai provider

---

deployment/helm_chart/opik/templates/clickhouseinstallation.yaml

[NA] expose more configuration options for clickhouse

---

sdks/python/src/opik/api_objects/experiment/helpers.py

Fixes #1392 - Makes a deep copy of the experiment_config object before editing it

Don't update the experiment_config object

---

apps/opik-backend/src/main/java/com/comet/opik/domain/CommentResultMapper.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemResultMapper.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java

Return comments in dataset item experiments items
Integration test

[OPIK-1097] Return comments in dataset item experiments items

---

apps/opik-backend/src/main/java/com/comet/opik/domain/RedirectService.java

Fix config for redirects
Checked with local deployment

[OPIK-1073] Fix config for redirects

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemResultMapper.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceTest.java

Update automation rule delete endpoint to not require project id query param
Integration test

[OPIK-1069] Update automation rule delete endpoint to not require project id query param

---

apps/opik-frontend/src/components/pages/ExperimentsShared/AddExperimentDialog.tsx

[RELATED ISSUE](https://github.com/comet-ml/opik/issues/1422)
Resolves #

[OPIK-1143] fix experiment code snippet

---

apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

OPIK-985: Fix the number of trace count

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceAnnotateViewer/AnnotateRow.tsx
apps/opik-frontend/src/components/pages-shared/traces/UserComment/UserCommentHoverList.tsx

[OPIK-1020] small improvements

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceAnnotateViewer/AnnotateRow.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/FeedbackScoreTab.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/CompareExperimentsFeedbackScoreCell.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesSpansTab.tsx
apps/opik-frontend/src/components/shared/DataTableCells/FeedbackScoreCell.tsx
apps/opik-frontend/src/components/shared/DataTableCells/FeedbackScoreNameCell.tsx
apps/opik-frontend/src/components/shared/FeedbackScoreTag/FeedbackScoreReasonTooltip.tsx

- design feedback improvements
Resolves #

[OPIK-1000] comments column improvements

---

apps/opik-frontend/src/components/shared/ResizableSidePanel/ResizableSidePanel.tsx

Add animation with 150 millisecond duration to the side panel component 
Resolves #

OPIK-1177 Add animation to sidebars

---

apps/opik-frontend/src/components/layout/SideBar/GitHubStarListItem/GitHubStarListItem.tsx

[OPIK-1151] GitHub 'Stars counter' button improvements

---

apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java

- OPIK-985: Add comment to clarify threads aggregations

OPIK-985: Add comment to clarify threads aggregations

---

deployment/helm_chart/opik/templates/clickhouseinstallation.yaml

add volume annotation option for clickhouse

---

apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000012_add_user_feedback_definition.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FeedbackDefinitionResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/AuthModuleNoAuthIntegrationTest.java

- Add user feedback definition

OPIK-1105: Add user feedback definition

---

sdks/python/src/opik/api_objects/trace/migration.py

This pull request is a fix for the original migration script.
New script in another branch https://github.com/comet-ml/opik/tree/OPIK-1153-data-migration
Fixes:
- Issue with reassigning parent span ids.
- Spans are no longer logged if their parent_span_id points to a non-existent object.

[OPIK-1153] [SDK] - Project data migration

---

apps/opik-frontend/src/components/shared/DataTableCells/LinkCell.tsx

- fix LinkCell if there is no ID specified
Resolves #

[OPIK-1112] [Chat] Implement thread sidebar

---

deployment/helm_chart/opik/templates/networkpolicies.yaml

fix helm chart

---

apps/opik-frontend/src/api/automations/useRuleCreateMutation.ts
apps/opik-frontend/src/api/automations/useRuleUpdateMutation.ts
apps/opik-frontend/src/api/automations/useRulesBatchDeleteMutation.ts
apps/opik-frontend/src/api/automations/useRulesList.ts
apps/opik-frontend/src/api/automations/useRulesLogsList.ts
apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx
apps/opik-frontend/src/components/pages-shared/automations/AddEditRuleDialog/AddEditRuleDialog.tsx
apps/opik-frontend/src/components/pages-shared/automations/AddEditRuleDialog/LLMJudgeRuleDetails.tsx
apps/opik-frontend/src/components/pages-shared/automations/AddEditRuleDialog/PythonCodeRuleDetails.tsx
apps/opik-frontend/src/components/pages-shared/automations/AddEditRuleDialog/schema.ts
apps/opik-frontend/src/components/pages-shared/automations/NoRulesPage.tsx
apps/opik-frontend/src/components/pages-shared/automations/ProjectsSelectBox.tsx
apps/opik-frontend/src/components/pages-shared/automations/RuleLogsCell.tsx
apps/opik-frontend/src/components/pages-shared/automations/RuleRowActionsCell.tsx
apps/opik-frontend/src/components/pages-shared/automations/RulesActionsPanel.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/FeedbackScoreTab.tsx
apps/opik-frontend/src/components/pages-shared/traces/TracesOrSpansPathsAutocomplete/TracesOrSpansPathsAutocomplete.tsx
apps/opik-frontend/src/components/pages/AutomationLogsPage/AutomationLogsPage.tsx
apps/opik-frontend/src/components/pages/ChatPage/ChatPage.tsx
apps/opik-frontend/src/components/pages/OnlineEvaluationPage/OnlineEvaluationPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/NoTracesPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/ThreadsTab/NoThreadsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesPage.tsx
apps/opik-frontend/src/components/shared/NoDataPage/NoDataPage.tsx
apps/opik-frontend/src/hooks/useTracesOrSpansList.ts
apps/opik-frontend/src/lib/feedback-scores.tsx
apps/opik-frontend/src/router.tsx
apps/opik-frontend/src/types/automations.ts

[OPIK-946] Add online evaluation rules at workspace level

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AuthenticationResource.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/AuthCredentialsCacheService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/AuthService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/CacheService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RequestContext.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/AuthTestUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AuthenticationResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/RemoteAuthServiceTest.java

Endpoint to return current workspace name
Covered with integration/unit tests

[OPIK-1184] Endpoint to return current workspace name

---

sdks/python/src/opik/api_objects/dataset/dataset.py
sdks/python/src/opik/evaluation/engine/engine.py
sdks/python/src/opik/evaluation/evaluator.py
sdks/python/tests/e2e/test_experiment.py

This Pull Request introduces support for filtering dataset items by their IDs in `evaluate()` and `evaluate_prompt()` methods.
Resolves #
https://github.com/comet-ml/opik/issues/1473
test added

[OPIK-1200] [SDK] [FR]: Experiment on select ID's of dataset

---

.github/workflows/release.yaml
deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml
deployment/helm_chart/opik/templates/clickhouseinstallation.yaml

- Fix and simplify github release creation
- configuration fix
Resolves #

[Opik-333] fix github release notes

---

apps/opik-frontend/src/components/shared/DebounceInput/DebounceInput.tsx
apps/opik-frontend/src/components/shared/FiltersButton/rows/TimeRow.tsx
apps/opik-frontend/src/components/shared/TimePicker/TimePicker.tsx
apps/opik-frontend/src/components/ui/time-picker-input.tsx
apps/opik-frontend/src/components/ui/time-picker-period-select.tsx
apps/opik-frontend/src/components/ui/time-picker-utils.ts
apps/opik-frontend/src/lib/date.ts
apps/opik-frontend/src/lib/filters.ts

[OPIK-1161] [FR] [FE]: Add a datetime filter on the FE

---

apps/opik-backend/src/main/java/com/comet/opik/api/ModelCostData.java
apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/cost/ModelPrice.java
apps/opik-backend/src/main/java/com/comet/opik/domain/cost/SpanCostCalculator.java
apps/opik-backend/src/main/resources/model_prices_and_context_window.json
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java

Add Anthropic cost calculation

[OPIK-1164] Add Anthropic cost calculation

---

apps/opik-backend/src/main/java/com/comet/opik/api/Span.java

NA: fix json view for spans page

---

apps/opik-backend/config.yml
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/RateLimitConfig.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RequestContext.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimitInterceptor.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimitResponseFilter.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimitService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimited.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/redis/RedisRateLimitService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/TestDropwizardAppExtensionUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/SpanResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/infrastructure/ratelimit/RateLimitE2ETest.java

- Add workspace level write operation rate limit 
- Improve rate limit message 
- Add rate limit to get span by id
Automated test for each scenario: 
- workspace limit bridged 
- get span by id limit bridged 
- message format

OPIK-1186: Add get and post limit at workspace level

---

tests_load/README.md
tests_load/tests/test_trace_span_ingestion.py
tests_load/tests/test_trace_span_retrieval.py

Added load test for search trace and spans.
Updated instructions.
Minor update for ingestion load test.
OPIK-1207
Manually run both load tests:
- Ingestion.
- Retrieval.
Against:
- Local with docker compose.
- Staging.
N/A

OPIK-1207: Add trace and span ingestion load test

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/CompareExperimentsOutputCell.tsx
apps/opik-frontend/src/components/shared/DataTableCells/CellTooltipWrapper.tsx
apps/opik-frontend/src/components/shared/DataTableCells/CodeCell.tsx
apps/opik-frontend/src/components/shared/DataTableCells/PrettyCell.tsx
apps/opik-frontend/src/components/shared/DataTableCells/TextCell.tsx
apps/opik-frontend/src/components/shared/FeedbackScoreTag/FeedbackScoreReasonTooltip.tsx
apps/opik-frontend/src/components/shared/TooltipWrapper/TooltipWrapper.tsx
apps/opik-frontend/src/components/ui/tooltip.tsx

[OPIK-1156] [FR] [FE]: Add a way to expand a table text field

---

apps/opik-documentation/documentation/fern/docs/faq.mdx

Ensured Opik Cloud rate limits documentation is up to date.
N/A
N/A
N/A

NO-JIRA: Update rate limits documentation

---

sdks/python/src/opik/integrations/anthropic/messages_create_decorator.py
sdks/python/src/opik/integrations/anthropic/opik_tracker.py
sdks/python/tests/library_integration/anthropic/test_anthropic.py

Fixed the bug when anthropic integration didn't send provider information.

[NA] Updated anthropic integration to include model and provider correctly

---

.github/workflows/build_and_push_docker.yaml

build both amd and arm docker images

---

.github/workflows/build_and_push_docker.yaml

Fix building latest images

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsActionsPanel.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx
apps/opik-frontend/src/components/shared/DataTable/utils.tsx
apps/opik-frontend/src/types/shared.ts

[OPIK-1231] [FR]: CSV Exports from the UI when Comparing Experiments

---

apps/opik-documentation/documentation/package-lock.json
apps/opik-documentation/documentation/package.json

I couldn't run the docs locally – it failed with command not found. I think there was a small mistake with the package name.
https://buildwithfern.com/learn/docs/getting-started/quickstart#use-the-fern-cli
Resolves #

Fix fern dependency for docs

---

apps/opik-documentation/documentation/fern/docs/tracing/cost_tracking.mdx

Update the example for setting the total cost

Update cost example

---

deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml
deployment/helm_chart/opik/templates/clickhouseinstallation.yaml
deployment/helm_chart/opik/templates/deployment.yaml

https://github.com/comet-ml/opik/issues/1533
Resolves #

add imagePullSecrets to clickhouse configuration

---

apps/opik-frontend/src/components/shared/DataTableCells/FeedbackScoreListCell.tsx

[OPIK-1021] add padding for feedback score cell

---

apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/charts/ExperimentChartContainer.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/charts/ExperimentChartContent.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/charts/ExperimentsChartsWrapper.tsx
apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricChart/MetricChart.tsx
apps/opik-frontend/src/hooks/useGroupedExperimentsList.ts

- change animation duration
- fix glitch on experiment page
- add loader for experiment charts
Resolves #

[OPIK-1039] chart animation improvements

---

apps/opik-frontend/src/components/pages-shared/llm/PromptModelSettings/PromptModelConfigs.tsx
apps/opik-frontend/src/components/pages-shared/llm/PromptModelSettings/providerConfigs/GeminiModelConfigs.tsx
apps/opik-frontend/src/hooks/useLLMProviderModelsData.ts
apps/opik-frontend/src/types/providers.ts

[OPIK-1275] Gemini provider config

---

apps/opik-frontend/src/components/pages-shared/experiments/ExperimentsRadarChart/ExperimentsRadarChart.tsx

- fix hover legend radar chart issue
Resolves #

[OPIK-1160] fix legend hover for radar chart

---

apps/opik-backend/config.yml
apps/opik-backend/pom.xml
apps/opik-backend/src/main/java/com/comet/opik/api/attachment/AttachmentInfo.java
apps/opik-backend/src/main/java/com/comet/opik/api/attachment/AttachmentInfoHolder.java
apps/opik-backend/src/main/java/com/comet/opik/api/attachment/CompleteMultipartUploadRequest.java
apps/opik-backend/src/main/java/com/comet/opik/api/attachment/StartMultipartUploadRequest.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AttachmentResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/session/RedirectResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/attachment/AttachmentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/attachment/AttachmentService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/attachment/FileUploadService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/AWSUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/TestDropwizardAppExtensionUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/AttachmentResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AttachmentResourceMinIOTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AttachmentResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/podam/PodamFactoryUtils.java
apps/opik-backend/src/test/java/com/comet/opik/podam/manufacturer/StartMultipartUploadRequestManufacturer.java
deployment/docker-compose/docker-compose.override.yaml
deployment/docker-compose/docker-compose.yaml

Implement attachment feature for OS installations
Integration testing, plus manually tested in cloud and with running Opik locally
https://www.notion.so/cometml/BE-Add-support-for-attachments-1707124010a3803ba260cdb0d3408a08#1757124010a380d08353e8e9fd25e695

[OPIK-727] Implement attachment feature for OS installations

---

apps/opik-documentation/documentation/fern/docs/quickstart.mdx

Small fixes to the quickstart

---

apps/opik-frontend/src/components/layout/PageLayout/PageLayout.tsx
apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx

[OPIK-1255] Improve expand/collapse discoverability of side menu

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/values.yaml

replace previous implementation that used docker images with lots of vulnerabilities
Resolves #
tested locally and on dev

update initContainer for opik-backend

---

apps/opik-documentation/documentation/fern/docs/self-host/kubernetes.mdx

update docs with snippet for external clickhouse configuration

---

opik.ps1

- Add ps1 file to support Windows users

OPIK-1263: Add ps1 file to start opik

---

deployment/helm_chart/opik/Chart.lock
deployment/helm_chart/opik/Chart.yaml
deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/values.yaml

[OPIK-1258] add minio to default helm configuration

---

.github/workflows/build_and_push_docker.yaml

fix opik-python-backend build

---

apps/opik-backend/src/main/java/com/comet/opik/api/WorkspaceNameHolder.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AuthenticationResource.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AuthenticationResourceTest.java

Update getWorkspaceName endpoint
Integration test

[OPIK-1287] Update getWorkspaceName endpoint

---

.github/workflows/python_sdk_unit_tests.yml
.github/workflows/sdk-e2e-tests.yaml

[NA] Add report for sdk tests

---

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DemoData.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/bi/MetadataDAO.java
apps/opik-backend/src/test/java/com/comet/opik/infrastructure/bi/DailyUsageReportJobTest.java

- Remove demo data from daily report

OPIK-1260: Remove demo data from daily report

---

apps/opik-documentation/documentation/fern/docs.yml
apps/opik-documentation/documentation/fern/docs/home.mdx

SEO updates

---

apps/opik-frontend/src/components/pages-shared/automations/RuleRowActionsCell.tsx
apps/opik-frontend/src/components/pages/ConfigurationPage/AIProvidersTab/AIProvidersRowActionsCell.tsx
apps/opik-frontend/src/components/pages/ConfigurationPage/FeedbackDefinitionsTab/FeedbackDefinitionsRowActionsCell.tsx
apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemRowActionsCell.tsx
apps/opik-frontend/src/components/pages/DatasetsPage/DatasetRowActionsCell.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentRowActionsCell.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectRowActionsCell.tsx
apps/opik-frontend/src/components/pages/PromptsPage/PromptRowActionsCell.tsx
apps/opik-frontend/src/components/shared/DataTable/utils.tsx
apps/opik-frontend/src/components/shared/DataTableCells/CellWrapper.tsx

Fix all tables actions button to not generate main row action (click handler)
Resolves #
Manual testing

[OPIK-1340] Sidebar with deleted dataset item information opens after deletion

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.module.scss
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/helpers.ts
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/treeRenderers.tsx
apps/opik-frontend/src/components/shared/SearchInput/SearchInput.tsx

[OPIK-1329] [GItHub] #1624 Add search functionality for span tree

---

README.md
opik.ps1
opik.sh

Windows:
Mac or Linux:
Update the installation instructions in the Read Me.

OPIK-1263: Change readme and final adjustments

---

README.md

were missing the cd command after repo clone
Resolves #

Update Readme startup instructions

---

.gitignore
deployment/docker-compose/docker-compose.yaml
deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/demo-data-generator-job.yaml
deployment/helm_chart/opik/values.yaml

add demo-data-generatior job and probes for backend services

---

deployment/docker-compose/docker-compose.yaml

- This PR relaxes the health checks and fix the dependency between frontend and backend

NA: Adjust health check

---

apps/opik-python-backend/src/opik_backend/demo_data_generator.py

- Change log level for demo data http call logs

NA: Change log level for demo data http call logs

---

apps/opik-documentation/documentation/fern/docs/self-host/kubernetes.mdx
apps/opik-documentation/documentation/fern/docs/self-host/local_deployment.mdx

We've recently had customers confused on which deployment docs they should use. Adding a small warning that the OSS docs are different.

Self deployment doc updates

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsViewer.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/DataTab/ExperimentDatasetItems.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/CompareExperimentsNameCell.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/CompareExperimentsOutputCell.tsx
apps/opik-frontend/src/components/shared/DataTableCells/TextCell.tsx

[ISSUE-1660] [FR]: Render markdown in experiment output

---

apps/opik-frontend/Dockerfile

Upgrade minor node image. This is just the builder stage, not the actually image being run.
N/A
- https://hub.docker.com/_/node

NO-JIRA: Upgrade Frontend Docker base build image

---

.github/workflows/installation_tests.yml

Updated tests according to edited readmes and docs (now testing ./opik.sh)

NO-OPIK update installation according to updated readmes and docs

---

apps/opik-documentation/documentation/fern/openapi/opik.yaml
sdks/code_generation/fern/openapi/openapi.yaml
sdks/python/src/opik/rest_api/types/span_public.py
sdks/typescript/src/opik/rest_api/api/types/SpanPublic.ts
sdks/typescript/src/opik/rest_api/serialization/types/SpanPublic.ts

Adds OpenApi spec for the changes made in #1664
OPIK-1018

[OPIK-1018] add OpenAPI spec for the `projectName` field of Span

---

apps/opik-frontend/src/components/layout/SideBar/GitHubStarListItem/GitHubStarListItem.tsx
apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx

- added scroll for SideBar items on small screen
Resolves #

[OPIK-1350] double scroll fix

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/InputOutputTab.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsViewer.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/DataTab/ExperimentDatasetItems.tsx
apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemPanelContent.tsx
apps/opik-frontend/src/lib/images.ts

[OPIK-1276] replace base64 values inside input/output

---

apps/opik-backend/src/main/java/com/comet/opik/api/Experiment.java
apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentSearchCriteria.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/ExperimentSortingFactory.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortableFields.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java

- Add sorting to find experiments endpoints

OPIK-1212: Add sorting for experiments

---

apps/opik-python-backend/src/opik_backend/executor.py
apps/opik-python-backend/src/opik_backend/executor_docker.py

Changes that were missing during conflicts resolution.
OPIK-1240
OPIK-1697

[OPIK-1240] Bringing in modifications from OPIK-1697

---

apps/opik-python-backend/README.md
apps/opik-python-backend/src/opik_backend/evaluator.py
deployment/docker-compose/docker-compose.yaml
deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/values.yaml

NA: Changing python backend default to processes

---

apps/opik-python-backend/entrypoint.sh
apps/opik-python-backend/src/opik_backend/evaluator.py
apps/opik-python-backend/src/opik_backend/executor_docker.py

- Lazy loading executor strategy to avoid running Docker when unnecessary.
This will make the application start up very fast and consumer less resources

NA: Lazy loading executor strategy

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/servicemonitor.yaml
deployment/helm_chart/opik/values.yaml

add serviceMonitor template disabled by default

---

.github/workflows/span_cost_upload_daily.yml

Workflow to update span cost daily

[OPIK-1365] Workflow to update span cost daily

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/json/ErrorMessageBodyWriter.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java

- Fix the error serialization for stream span search.

NA: Fix search error message response

---

.github/workflows/span_cost_upload_daily.yml
.gitignore

[NA] Fix Span cost update workflow

---

apps/opik-documentation/documentation/fern/docs/tracing/integrations/litellm.mdx

Add default authorization for LiteLLM Proxy example

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringSampler.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/log/LogContextAware.java

Adding a helper function to `wrapWithMdc` context any multithreaded function.
Test added in the previous PR

NO-JIRA: Fix online scoring MDC propagation issue

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsActionsPanel.tsx
apps/opik-frontend/src/components/pages/TracesPage/ThreadsTab/ThreadsActionsPanel.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesActionsPanel.tsx

got rid of removing prefixes for traces, experiments and threads; - got the green light from Jacques
Fixes: #1716 
Trace with dot
```
[
{
"id": "0195f672-26f6-7e28-a284-7f9c11d4cdff",
"name": "test-feedback-scores",
"start_time": "2025-04-02T12:20:31.094332Z",
"end_time": "",
"input": "testing",
"output": "",
"duration": "",
"metadata": "",
"tags": "",
"usage.total_tokens": "",
"usage.prompt_tokens": "",
"usage.completion_tokens": "",
"total_estimated_cost": "",
"span_count": 0,
"thread_id": "",
"error_info": "",
"created_by": "aadereiko",
"comments": "",
"feedback_scores.equals_a": "-",
"feedback_scores.equals_b": "-",
"feedback_scores.some_score": 0.1,
"feedback_scores.some_score-with_dash": 0.4,
"feedback_scores.some_score.with_dot": 0.2,
"feedback_scores.Numerical 10": "-", …
```

[OPIK-1399]: fix feedback scores with dots;

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringBaseScorer.java

NO-JIRA: Fix Online consumer overflown

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/deployment.yaml
deployment/helm_chart/opik/values.yaml

Parameterize the standard wait-for-clickhouse initContainer

---

apps/opik-backend/src/main/java/com/comet/opik/api/DatasetItemSearchCriteria.java
apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentSearchCriteria.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/EntityType.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java
apps/opik-backend/src/main/java/com/comet/opik/utils/TemplateUtils.java

- Refactored `EntityType` out of `FeedbackScoreDAO`
- Refactored `handleProjectRetrieval` logic out of `FeedbackScoreService` to `ProjectService`
- Refactored `getBatchSql` logic out of `FeedbackScoreDAO` to `TemplateUtils`
Based on existing tests

[NA] refactors preparing for guardrails

---

sdks/typescript/src/opik/integrations/opik-langchain/README.md

[OPIK-1392] add readme Langchain Integration JS

---

apps/opik-frontend/Dockerfile

[OPIK-1420]: label the build mode for FE images;

---

.github/workflows/documentation_codeblock_tests.yml

Add timeout to pytest for docs

Add timeout

---

sdks/typescript/package.json
sdks/typescript/src/opik/index.ts
sdks/typescript/src/opik/integrations/opik-langchain/package-lock.json
sdks/typescript/src/opik/integrations/opik-langchain/package.json
sdks/typescript/src/opik/integrations/opik-langchain/src/OpikCallbackHandler.ts

- put output from the last span to the trace
- fix build issue
- refactor SpanType
Resolves #

[OPIK-1418] Langchain trace output fix

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AttachmentResource.java

Fix typo for attachment endpoint documentation

[NA] Fix typo for attachment endpoint documentation

---

apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx
apps/opik-frontend/src/components/shared/DataTable/DataTable.tsx
apps/opik-frontend/src/components/shared/DataTableHeaders/TypeHeader.tsx
apps/opik-frontend/src/lib/table.ts
apps/opik-frontend/src/types/projects.ts
apps/opik-frontend/src/types/shared.ts

- added Custom Icon for Header cell
- added new column def for Guardrails
- feature toggle check
Resolves #

[OPIK-1370] add guardrails column in project list table

---

sdks/opik_optimizer/src/opik_optimizer/mipro_optimizer.py

Used the wrong Dataset for typing

Wrong Dataset for type checking

---

sdks/opik_optimizer/scripts/few_shot_bayesian_hotpot_example.py
sdks/opik_optimizer/scripts/few_shot_hotpot_example.py
sdks/opik_optimizer/scripts/hotpot_dataset_generation.py
sdks/opik_optimizer/scripts/mipro_hotpot_example.py
sdks/opik_optimizer/setup.py
sdks/opik_optimizer/src/opik_optimizer/base_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/evaluator.py
sdks/opik_optimizer/src/opik_optimizer/few_shot_bayesian_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/few_shot_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/integrations/dspy/dspy_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/mipro_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/optimization_result.py
sdks/opik_optimizer/src/opik_optimizer/predictor.py
sdks/opik_optimizer/src/opik_optimizer/prompt_parameter.py

Refinements to polish the optimizer code a bit:
* parameter name alignment
* typing alignment
* make all examples parallel

Optimizer refinements

---

CONTRIBUTING.md

Adjusted the SDK contribution guide to make it easier to follow the instructions

OPIK-1432 SDK contribution guide clarity changes

---

apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/TestHttpClientUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/ProjectResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java

Modify projects endpoints to support public projects
https://www.notion.so/cometml/Support-for-public-projects-1c37124010a380378ba5c93bb1cccea2#1c37124010a38184beb5ce17099037ac

[OPIK-1388] Modify projects endpoints to support public projects

---

sdks/opik_optimizer/src/opik_optimizer/demo/datasets.py
sdks/opik_optimizer/work_in_progress/few_shot_bayesian_halueval_example.py

[NA] Update demo dataset name

---

.github/workflows/deploy_python_sdk_docs.yml
apps/opik-documentation/documentation/fern/docs/tracing/integrations/adk.mdx

Fix link to ADK OpikTracer

---

apps/opik-documentation/python-sdk-docs/requirements.txt

Fix version of google-adk for doc building

---

apps/opik-frontend/src/components/shared/DebounceInput/DebounceInput.tsx

[NA] Fix issue with DebounceInput canceling when onValueChange property changes every render

---

apps/opik-frontend/src/components/pages-shared/attachments/ImagesListWrapper/ImagesListWrapper.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/AttachmentsList.tsx
apps/opik-frontend/src/lib/images.test.ts
apps/opik-frontend/src/lib/images.ts
apps/opik-frontend/src/types/attachments.ts

- added ability to parse base64 image given it is not separate property (part of the string)
- re-implemented functionality to replace base64 string in input field during the parsing process 
Resolves #

[OPIK-1414] [FE] [Base64 performance] - Trace sidebar performance

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/events/DatasetEventListenerTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java

OPIK-1448: Fix create experiment unexpected 404

---

.github/CODEOWNERS

Defined CODEOWNERS for `/sdks/opik_optimizer`.
N/A
N/A
N/A

NO-JIRA: Add Opik optimizer CODEOWNERS

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringBaseScorer.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringLlmAsJudgeScorer.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringUserDefinedMetricPythonScorer.java

Fixing the parallelization limitations around OnlineScoring and also adding Otel collection for message queue delay and message processing
Resolves #

[OPIK-1433] Improving OnlineScoring performance

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/BaseTraceDataTypeIcon.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/treeRenderers.tsx
apps/opik-frontend/src/components/shared/DataTableCells/GuardrailsCell.tsx
apps/opik-frontend/src/constants/guardrails.ts
apps/opik-frontend/src/constants/traces.ts
apps/opik-frontend/src/types/traces.ts

[OPIK-1372] guardrail span type

---

apps/opik-frontend/src/lib/images.test.ts
apps/opik-frontend/src/lib/images.ts

[OPIK-1455] base64 validation fix

---

.github/workflows/sdks_generate_openapi_spec_and_fern_code.yml

Implemented daily Github action workflow that updates the OpenAPI spec, both for the Opik documentation and for the Fern generators, and updates the Fern auto-generated code for the Python and TypeScript SDKs.
N/A
Successfully verified before merging:
- https://github.com/comet-ml/opik/actions/runs/14470480039
- https://github.com/comet-ml/opik/pull/1857
N/A

NO-JIRA: Add generate OpenAPI workflow

---

sdks/python/src/opik/integrations/langchain/anthropic_vertexai_run_helpers.py
sdks/python/src/opik/integrations/langchain/google_run_helpers.py
sdks/python/src/opik/integrations/langchain/opik_tracer.py
sdks/python/src/opik/types.py

Fix usage tracking for Anthropic models hosted on VertexAI

---

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Use metadata cost as a fallback to compute cost and support anthropic_vertexai provider

Use metadata cost as a fallback to compute cost and support anthropic_vertexai provider

---

apps/opik-frontend/src/components/shared/DataTableCells/PrettyCell.tsx
apps/opik-frontend/src/components/shared/SyntaxHighlighter/SyntaxHighlighter.tsx

[OPIK-1464] small optimizations for Trace table and Trace details code blocks

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/InputOutputTab.tsx

[OPIK-1464] fix Trace sidebar callstack error

---

apps/opik-frontend/package-lock.json
apps/opik-frontend/package.json

[OPIK-1464] update codemirror version

---

readme_CN.md

This submission addresses an issue where a portion of the [documentation](https://github.com/comet-ml/opik/blob/main/readme_CN.md) was in Korean. I have corrected this by translating the content into Chinese. This improvement enhances the clarity and understandability of the documentation for Chinese-speaking users.
N/A
N/A
N/A

docs:Fix README in CN

---

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/cost/SpanCostCalculator.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java

[OPIK-1471] Improve OpenAI cost computation by checking for cached tokens

---

apps/opik-backend/src/main/java/com/comet/opik/api/Trace.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Add automation test for span count in trace
resolves TODO of Opik 1278 - add span count
1374
Resolves #
Opik-1278
Opik-1374

[OPIK-1374] Add automation test for span count

---

apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java
apps/opik-backend/src/main/java/com/comet/opik/utils/ErrorUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/TestHttpClientUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/SpanResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java

Modify span endpoints for public porjects
https://www.notion.so/cometml/Support-for-public-projects-1c37124010a380378ba5c93bb1cccea2#1c37124010a38184beb5ce17099037ac

[OPIK-1388] Modify span endpoints for public porjects

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/domain/TraceServiceImplTest.java

Modify implementation for trace endpoints needed for public projects
https://www.notion.so/cometml/Support-for-public-projects-1c37124010a380378ba5c93bb1cccea2#1c37124010a38184beb5ce17099037ac

[Opik-1388] Modify implementation for trace endpoints needed for public projects

---

apps/opik-backend/src/main/java/com/comet/opik/api/Dataset.java
apps/opik-backend/src/main/java/com/comet/opik/api/DatasetUpdate.java
apps/opik-backend/src/main/java/com/comet/opik/api/Project.java
apps/opik-backend/src/main/java/com/comet/opik/api/ProjectUpdate.java
apps/opik-backend/src/main/java/com/comet/opik/api/Visibility.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RequestContext.java
apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000014_add_datasets_visibility.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Add visibility flag to datasets
https://www.notion.so/cometml/Support-for-public-Datasets-1d77124010a3807e9320ced8ad4d7800

[OPIK-1460] Add visibility flag to Dataset

---

apps/opik-backend/src/main/java/com/comet/opik/domain/attachment/AttachmentService.java

Add url encoding to start upload attachment link query params

[NA] Add url encoding to start upload attachment link query params

---

apps/opik-backend/src/main/java/com/comet/opik/api/Project.java
apps/opik-backend/src/main/java/com/comet/opik/api/ProjectStatsSummary.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/GuardrailsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

This PR adds a new stat for projects and traces: guardrails failed count.
OPIK-1376
Added a couple of tests

[OPIK-1376] new stat: guardrails failed count

---

.github/workflows/release.yaml

fix for a small but annoying problem in release workflow
Resolves #

fix updating version.txt when the last digit is 0

---

apps/opik-documentation/documentation/fern/docs/home.mdx

Fix two minor typos in the home page

Update home.mdx to fix a couple minor typos

---

opik.ps1
opik.sh

NA: Fix install event report

---

.github/workflows/build_and_push_docker.yaml
.github/workflows/build_apps.yml

The change is needed to make secrets visible in a job;

[NA]: fix the github token issue;

---

apps/opik-guardrails-backend/Dockerfile

Fix some permission error for guardrail backend

---

apps/opik-frontend/src/main.scss

[OPIK-1495] fix rendering border bottom bug in experiment table

---

sdks/python/tests/library_integration/dspy/test_dspy.py

DSPy latest release (2.6.19) seems to change the way data are logged.
Resolves #
Fixed integration tests

[OPIK-1497]: DSPy latest release (2.6.19) seems to change the way data are logged.

---

apps/opik-frontend/src/main.scss

[OPIK-1495] revert border bottom fix

---

apps/opik-frontend/src/components/pages/ExperimentsPage/charts/ExperimentChartContent.tsx

[OPIK-1480] Experiment page Scatter charts

---

apps/opik-frontend/src/api/traces/useLazySpansList.ts
apps/opik-frontend/src/api/traces/useSpansList.ts
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/InputOutputTab.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/TraceDataViewer.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDetailsPanel.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.tsx

[OPIK-1475] trace details sidebar lazy input/output

---

apps/opik-frontend/Dockerfile

Fix FE image: install specific nginx and fix nginx logging

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml
deployment/helm_chart/opik/templates/serviceaccount.yaml
deployment/helm_chart/opik/values.yaml

Add optional service account for clickhouse backup job

---

apps/opik-backend/pom.xml

will fix High CVE https://vulert.com/vuln-db/CVE-2025-27820
Resolves #

[NA] fix CVE-2025-27820

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/bi/BiEventListener.java
opik.ps1
opik.sh

NA: Update os event for installation

---

apps/opik-frontend/src/api/feature-toggle/useFeatureToggle.ts
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricChart/MetricChartContainer.tsx
apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricsTab.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesSpansTab.tsx
apps/opik-frontend/src/components/shared/DataTableCells/GuardrailsCell.tsx
apps/opik-frontend/src/hooks/useTracesOrSpansStatistic.ts
apps/opik-frontend/src/types/projects.ts
apps/opik-frontend/src/types/shared.ts
apps/opik-frontend/src/types/traces.ts

[OPIK-1383]: FE & BE integration guardrails;

---

apps/opik-documentation/documentation/fern/docs/tracing/integrations/openai.mdx

Update openai integration doc to mention all supported methods

---

apps/opik-backend/src/main/java/com/comet/opik/api/DeleteIdsHolder.java
apps/opik-backend/src/main/java/com/comet/opik/api/OptimizationUpdate.java
apps/opik-backend/src/main/java/com/comet/opik/api/events/ExperimentCreated.java
apps/opik-backend/src/main/java/com/comet/opik/api/events/ExperimentsDeleted.java
apps/opik-backend/src/main/java/com/comet/opik/api/events/OptimizationsDeleted.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/DatasetEventListener.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/OptimizationsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetEventInfoHolder.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDatasetId.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/OptimizationResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/events/DatasetEventListenerTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetExperimentE2ETest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/OptimizationsResourceTest.java

Optimization update delete endpoints
https://www.notion.so/cometml/BE-Opik-Prompt-Optimization-1df7124010a380b7abc1cec263bd5493

[OPIK-1492] Optimization update delete endpoints

---

apps/opik-documentation/documentation/fern/docs/home.mdx

Fix minor typo in the documentation

[Doc] Fix minor typo on the home page

---

apps/opik-backend/src/main/java/com/comet/opik/api/OptimizationSearchCriteria.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/OptimizationsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationService.java
apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000022_add_dataset_deleted_to_optimizations.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/OptimizationResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/OptimizationsResourceTest.java

- Add new endpoint 
- Add tests

OPIK-1513: Get all optimisations endpoint

---

sdks/python/src/opik/api_objects/attachment/attachment.py

Fix linter errors

---

apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentSearchCriteria.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/ExperimentResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java

Agent optimization changes for experiment endpoints
https://www.notion.so/cometml/BE-Opik-Prompt-Optimization-1df7124010a380b7abc1cec263bd5493

[OPIK-1493] Agent optimization changes for experiment endpoints

---

apps/opik-backend/src/main/java/com/comet/opik/api/Dataset.java
apps/opik-backend/src/main/java/com/comet/opik/api/DatasetCriteria.java
apps/opik-backend/src/main/java/com/comet/opik/api/events/DatasetsDeleted.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/DatasetEventListener.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortableFields.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortingFactoryDatasets.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/DatasetResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/OptimizationsResourceTest.java

Changes to dataset endpoints needed for agent optimization
https://www.notion.so/cometml/BE-Opik-Prompt-Optimization-1df7124010a380b7abc1cec263bd5493

[OPIK-1493] Changes to dataset endpoints needed for agent optimization

---

apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationDAO.java

- Simplifying the query and pushing the where condition

NA: Replicate experiment changes to optimization endpoint

---

sdks/python/src/opik/integrations/adk/opik_tracer.py

Fix #2013
Add support for streaming in ADK integration
Resolves #

Add support for streaming in ADK integration

---

apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/OptimizationResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/OptimizationsResourceTest.java

Fix for following bugs:
1) num_trials - returns 1 in case Optimization has no trials and it should be 0
2) flag dataset_deleted - returns only 1 optimisation per deleted dataset, should be all
Added corresponding integration tests

[NA] Fix agent optimization bugs

---

sdks/opik_optimizer/src/opik_optimizer/meta_prompt_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/utils.py

Resolves issues with metaprompter

fix: metaprompter for opik optimizer

---

opik.ps1
opik.sh

Changed default behaviour in `opik.sh` and `opik.ps1` to not to do port mapping, except for accessing Opik and for the Open API documentation, by running only `docker-compose.yaml` by default.
Added an optional `-port-mapping` flag to do port mapping for the rest of services (backend, ClickHouse, MySQL etc.) by running  `docker-compose.override.yaml`.
Made many improvements and fixes in the code and organisation of both scripts.
OPIK-1515
- Locally tested `opik.sh`:
- With and without port mapping, both start and stop.
- Regressed all flags.
- Regressed combinable flags.
- Pending test on `opik.ps1`.
N/A

OPIK-1515: Add port mapping to opik.sh and opik.ps1

---

sdks/typescript/src/opik/index.ts

[OPIK-1505] public dataset type export

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.tsx

[OPIK-1475] Trace sidebar collapsing fix

---

apps/opik-guardrails-backend/opik_guardrails/services/validators/pii/validator.py

Fix PII validator passed logic

---

opik.ps1

Per my testing, I discovered some issues that were inherited from the previous implementation of `opik.ps1` and fixed them:
- Multiple args were not accepted and showed error: `A positional parameter cannot be found that accepts argument`
- Directory was changed to `deployment\docker-compose` but not reverted back if the script was killed with CTRL + C. This was an annoying user experience.
- There was a bug when printing verify command.
Not related, but discovered as part of testing OPIK-1515.
- Tested by running locally all flags (and their combinations) in a Windows machine
N/A

OPIK-1515: Fixes in opik.ps1

---

sdks/python/tests/library_integration/dspy/test_dspy.py

This PR adds tests for DSPy graph logging.

[NA] Add tests for dspy log graph

---

sdks/opik_optimizer/benchmarks/opik-mipro-hotpot-500.py
sdks/opik_optimizer/scripts/few_shot_bayesian_hotpot_chat_prompt_example.py
sdks/opik_optimizer/scripts/meta_prompt_hotpot_example.py
sdks/opik_optimizer/setup.py
sdks/opik_optimizer/src/opik_optimizer/few_shot_bayesian_optimizer/few_shot_bayesian_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/meta_prompt_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/mipro_optimizer/_mipro_optimizer_v2.py
sdks/opik_optimizer/src/opik_optimizer/mipro_optimizer/mipro_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/task_evaluator.py
sdks/opik_optimizer/src/opik_optimizer/utils.py

[OPIK-1534] sdk integrate optimization api into opik optimizer

---

.github/workflows/build_and_push_docker.yaml
.github/workflows/build_apps.yml

fix release flow for opik-guardrails-backend

---

apps/opik-frontend/src/components/pages-shared/experiments/CompareExperimentsConfigCell/CompareExperimentsConfigCell.tsx
apps/opik-frontend/src/components/pages-shared/experiments/FeedbackScoresChartsWrapper/FeedbackScoresChartContainer.tsx
apps/opik-frontend/src/components/pages/CompareOptimizationsPage/OptimizationProgressChartContainer.tsx
apps/opik-frontend/src/components/pages/CompareOptimizationsPage/OptimizationProgressChartContent.tsx
apps/opik-frontend/src/components/pages/CompareTrialsPage/PromptTab/PromptTab.tsx

Improve the chart on the Optimization details page
Change the way the prompt is parsed on the Prompt tab for the trial
Resolves #

[OPIK-1479] [FE] [Agent optimizations] Agent Optimizations page

---

sdks/opik_optimizer/src/opik_optimizer/few_shot_bayesian_optimizer/few_shot_bayesian_optimizer.py
sdks/opik_optimizer/src/opik_optimizer/mipro_optimizer/mipro_optimizer.py

With the new optimizer BE support, the optimizer SDK will attempt to create an optimization. But we can still allow code to run to create experiments, even if using older BE.

Allow optimizer SDK without BE support

---

apps/opik-documentation/documentation/fern/docs/tracing/integrations/autogen.mdx
apps/opik-documentation/documentation/fern/docs/tracing/opentelemetry/overview.mdx

Update docs for Autogen integration

Update Autogen integration

---

apps/opik-documentation/documentation/fern/docs/self-host/kubernetes.mdx

Update k8s docs with additional configuration snippets

---

sdks/python/src/opik/integrations/langchain/openai_run_helpers.py
sdks/python/src/opik/integrations/openai/openai_chat_completions_decorator.py

This pull request resolves an issue in the SDK where a 'NoneType' object was being treated as a mapping at the Events Users Level. The fix ensures proper handling of such scenarios.
Resolves #
No updates required.

[OPIK-1381] [SDK] Fix error: 'NoneType' object is not a mapping

---

apps/opik-frontend/src/plugins/comet/RetentionBanner.tsx
apps/opik-frontend/src/plugins/comet/api/useOrganizationMembers.ts
apps/opik-frontend/src/plugins/comet/types.ts

Admin Exceeded:
Non-admin Exceeded: 
Resolves #

[OPIK-1514]: retention banner updates

---

apps/opik-frontend/src/lib/traces.test.ts
apps/opik-frontend/src/lib/traces.ts

[OPIK-1543] Improve "pretty mode" algorithm

---

apps/opik-frontend/src/components/App.tsx
apps/opik-frontend/src/components/shared/DataTable/DataTable.tsx
apps/opik-frontend/src/components/shared/DataTable/DataTableTooltipContext.tsx
apps/opik-frontend/src/components/shared/DataTableCells/CellTooltipWrapper.tsx
apps/opik-frontend/src/components/shared/TooltipWrapper/TooltipWrapper.tsx
apps/opik-frontend/src/components/ui/tooltip.tsx

Added table context that emulates tooltip functionality using Radix Popover 
Resolves #

[OPIK-1322] [FE] [Performance improvement] Implement Table-specific tooltip handling

---

sdks/python/src/opik/integrations/llama_index/callback.py
sdks/python/tests/library_integration/llama_index/test_llama_index.py

Adds an option to disable the "index_construction" phase tracking in `llama_index`. This allows users to avoid tracking overhead if it's unnecessary for their use case.
added tests to verify functionality with and without tracking enabled.

[OPIK-851] [SDK] Make "index_construction" phase tracking optional in llama_index

---

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Public projects additional endpoints for SDK
https://www.notion.so/cometml/Support-for-public-projects-1c37124010a380378ba5c93bb1cccea2#1c37124010a38184beb5ce17099037ac

[OPIK-1486] Public projects additional endpoints for SDK

---

apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx

[OPIK-1579] hide experiment charts if there are no experiments

---

apps/opik-documentation/documentation/fern/docs.yml
apps/opik-documentation/documentation/fern/docs/reference/overview.mdx
apps/opik-documentation/documentation/fern/docs/reference/ruby-otel-sdk/overview.mdx

- Add doc page for Ruby Otel Opik integration

OPIK-1559: Add docs for Ruby Otel Opik integration

---

apps/opik-frontend/src/hooks/useLLMProviderModelsData.ts

Add a way to run online evaluation for vertex ai;
Resolves #

[OPIK-1618]: vertex ai online eval;

---

sdks/python/src/opik/api_objects/opik_client.py

The Pull Request updates the Opik client `.search_traces()` method to improving batch handling for retrieving large datasets.

[OPIK-1435] [SDK] Implement stream-based traces search [Long term solution]

---

apps/opik-documentation/documentation/fern/docs/agent_optimization/algorithms/mipro_optimizer.mdx

Fixed broken links

---

sdks/opik_optimizer/setup.py
sdks/opik_optimizer/src/opik_optimizer/data/hotpot-500.json
sdks/opik_optimizer/src/opik_optimizer/demo/datasets.py

The hotpot dataset URL is offline. This PR packages up 500 rows and makes part of the opik-optimizer package.

Optimizer: fix hotpot download

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/openai/OpenAIClientGenerator.java

- The lib upgrade caused this issue. The new version only sets the default URL when using the chat mode.

OPIK-1637: Fix missing base url error due to lib upgrade

---

apps/opik-documentation/python-sdk-docs/source/guardrails/guardrail.rst
apps/opik-documentation/python-sdk-docs/source/guardrails/pii.rst
apps/opik-documentation/python-sdk-docs/source/guardrails/topic.rst
apps/opik-documentation/python-sdk-docs/source/guardrails/validation_response.rst
apps/opik-documentation/python-sdk-docs/source/index.rst

Add guardrails SDK docs

---

apps/opik-frontend/src/api/playground/createLogPlaygroundProcessor.ts
apps/opik-frontend/src/api/prompts/useCreatePromptVersionMutation.ts
apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessages/AddNewPromptVersionDialog.tsx
apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessages/LLMPromptMessage.tsx
apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessages/LLMPromptMessageActions.tsx
apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessages/LLMPromptMessages.tsx
apps/opik-frontend/src/components/pages-shared/llm/PromptModelSelect/PromptModelSelect.tsx
apps/opik-frontend/src/components/pages-shared/llm/PromptsSelectBox/PromptsSelectBox.tsx
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/PlaygroundOutputActions.tsx
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPage.tsx
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompts/PlaygroundPrompt.tsx
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompts/PlaygroundPrompts.tsx
apps/opik-frontend/src/components/pages/PromptPage/ExperimentsTab/ExperimentsTab.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/EditPromptVersionDialog.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/PromptTab.tsx
apps/opik-frontend/src/components/pages/PromptPage/TryInPlaygroundButton.tsx
apps/opik-frontend/src/components/pages/PromptsPage/AddEditPromptDialog.tsx
apps/opik-frontend/src/components/shared/LoadableSelectBox/LoadableSelectBox.tsx
apps/opik-frontend/src/components/shared/Loader/Loader.tsx
apps/opik-frontend/src/components/shared/MarkdownPreview/MarkdownPreview.tsx
apps/opik-frontend/src/constants/llm.ts
apps/opik-frontend/src/main.scss
apps/opik-frontend/src/types/llm.ts

[OPIK-1542] Add prompt selector to the Playground

---

apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/PlaygroundOutputActions.tsx

[OPIK-1656]: validate out empty messages;

---

apps/opik-documentation/documentation/fern/docs/evaluation/evaluate_agents.mdx

Add reference to guardrails in agent evaluation doc

Add reference to guardrails in agent evaluation doc

---

apps/opik-documentation/documentation/fern/docs/agent_optimization/cookbook/optimizer_introduction_cookbook.mdx
apps/opik-documentation/documentation/fern/docs/agent_optimization/cookbook/synthetic_data_optimizer_cookbook.mdx
apps/opik-documentation/documentation/fern/docs/agent_optimization/opik_optimizer/concepts.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/aisuite.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/anthropic.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/bedrock.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/dspy.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/gemini.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/groq.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/instructor.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/langchain.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/langgraph.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/llama_index.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/ollama.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/openai.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/predibase.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/ragas.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/watsonx.mdx

Fix layout issue

---

apps/opik-documentation/documentation/fern/docs/tracing/sdk_configuration.mdx

Added docs on how to set the project name. This is until we add the changes to the configure method/cli
Resolves #

Update sdk_configuration.mdx with project name

---

apps/opik-frontend/src/components/pages/OptimizationsPage/OptimizationsPage.tsx

[OPIK-1671] [FE] Add Optimizer column to Optimization runs page

---

apps/opik-frontend/src/plugins/comet/WorkspacePreloader.tsx

For some users in stg, the default workspace is not present, we now handle this case on FE
Resolves #

[OPIK-1672]: ensure workspace is set when none is default

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/LlmProviderLangChainMapper.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/openai/LlmProviderOpenAi.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/openrouter/OpenRouterErrorMessage.java

- Adding mapping to the OpenRouter error
- Manually tested

NA: Map error message to OpenAI client using open router

---

sdks/typescript/src/opik/types.d.ts

[OPIK-1647] add headersiterator type

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/LlmProviderLangChainMapper.java

-- Add missing validation to mapper

NA: Add missing validation to LLM provider LangChain mapper

---

apps/opik-documentation/documentation/fern/docs.yml
apps/opik-documentation/documentation/fern/docs/reference/typescript-sdk/integrations/openai.mdx
apps/opik-documentation/documentation/fern/docs/reference/typescript-sdk/integrations/overview.mdx

[OPIK-1675] Open AI TS SDK integration docs

---

.github/workflows/documentation_preview_link.yml
apps/opik-documentation/documentation/fern/docs.yml
apps/opik-documentation/documentation/fern/docs/tracing/opentelemetry/python-sdk.mdx

Add OTel Python SDK example

---

apps/opik-frontend/src/components/pages-shared/experiments/AddExperimentDialog/AddExperimentDialog.tsx

[NA]: fix isJson label for experiments code snippets;

---

apps/opik-backend/src/main/java/com/comet/opik/api/Optimization.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/OptimizationsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationService.java
apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000026_reduce_optimization_last_updated_at_to_micros.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/OptimizationResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/OptimizationsResourceTest.java

[OPIK-1557] Optimizations Upsert endpoint

---

.github/workflows/publish_opik_optimizer.yml

Add deployment job for the Opik Optimizer

Deploy job for Opik Optimizer

---

apps/opik-frontend/src/api/playground/createLogPlaygroundProcessor.ts
apps/opik-frontend/src/api/prompts/usePromptCreateMutation.ts
apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessages/AddNewPromptVersionDialog.tsx
apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessages/LLMPromptMessage.tsx
apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessages/LLMPromptMessageActions.tsx
apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessages/LLMPromptMessages.tsx
apps/opik-frontend/src/components/pages-shared/llm/PromptsSelectBox/PromptsSelectBox.tsx
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/usePromptDatasetItemCombination.ts
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPage.tsx
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompts/PlaygroundPrompt.tsx
apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompts/PlaygroundPrompts.tsx
apps/opik-frontend/src/components/pages/PromptPage/CommitsTab/CommitsTab.tsx
apps/opik-frontend/src/components/pages/PromptPage/TryInPlaygroundButton.tsx
apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricChart/MetricBarChart.tsx
apps/opik-frontend/src/components/shared/EyeInput/EyeInput.tsx
apps/opik-frontend/src/components/ui/button.tsx
apps/opik-frontend/src/constants/llm.ts
apps/opik-frontend/src/main.scss
apps/opik-frontend/src/types/llm.ts
apps/opik-frontend/src/types/playground.ts

[OPIK-1635] [FE] [Prompt Library <-> Playground] Resolve small inconsistencies

---

apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000027_add_visibility_mode_to_traces_table.sql

- Add migration to create field on the table

OPIK-1664: Add visibility mode migration

---

.github/workflows/documentation_codeblock_tests.yml
.github/workflows/documentation_image_optimizer.yml
.github/workflows/documentation_preview_link.yml
.github/workflows/end2end_suites.yml
.github/workflows/lib-integration-tests-runner.yml
.github/workflows/python_sdk_unit_tests.yml
.github/workflows/sdk-e2e-library-tests.yaml
.github/workflows/sdk-e2e-tests.yaml

This reverts commit 2ce447c58a09fb8cde6226daffe13b2381dd6641.
Related to use of `pull_request_target`

chore: revert github actions changes to PRs for `pull_request_target`

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/openrouter/OpenRouterErrorMessage.java

- Handle error unknown fields
```
{"error":{"message":"Rate limit exceeded: free-models-per-min. ","code":429,"metadata":{"headers":{"X-RateLimit-Limit":"20","X-RateLimit-Remaining":"0","X-RateLimit-Reset":"1748542800000"},"provider_name":null}},"user_id":"user_2p1Pw7VZBtsBz0IdBJCDdpiiL16"}
```

NA: Handle error with unknown fields

---

.github/workflows/documentation_codeblock_tests.yml
.github/workflows/documentation_image_optimizer.yml
.github/workflows/documentation_preview_link.yml
.github/workflows/end2end_suites.yml
.github/workflows/lib-integration-tests-runner.yml
.github/workflows/python_sdk_unit_tests.yml
.github/workflows/sdk-e2e-tests.yaml

This will allow external contributors to the repo to execute after approval several github actions flows. mainly for docs, SDK integrations tests and E2E tests.
Resolves #

Allow Actions from external PRs

---

apps/opik-backend/src/main/java/com/comet/opik/api/TraceThread.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/SpanResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/traces/TraceAssertions.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Add token count and cost to threads
https://comet-ml.atlassian.net/browse/OPIK-1685

[OPIK-1702] Add token count and cost to threads

---

apps/opik-backend/src/main/java/com/comet/opik/api/TraceThread.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortableFields.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/TraceThreadSortingFactory.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/traces/TraceAssertions.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

- Enable sorting for all thread table columns

OPIK-1703: Enable sorting for all thread table columns

---

apps/opik-frontend/src/components/pages/CompareExperimentsPage/ConfigurationTab/ConfigurationTab.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx
apps/opik-frontend/src/components/pages/CompareTrialsPage/ConfigurationTab/ConfigurationTab.tsx
apps/opik-frontend/src/components/pages/CompareTrialsPage/TrialsItemsTab/TrialItemsTab.tsx
apps/opik-frontend/src/components/pages/TracesPage/RulesTab/RulesTab.tsx
apps/opik-frontend/src/components/pages/TracesPage/ThreadsTab/ThreadsTab.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesSpansTab.tsx
apps/opik-frontend/src/components/shared/ExplainerCallout/ExplainerCallout.tsx
apps/opik-frontend/src/components/shared/ExplainerDescription/ExplainerDescription.tsx
apps/opik-frontend/src/components/shared/ExplainerIcon/ExplainerIcon.tsx
apps/opik-frontend/src/constants/explainers.ts
apps/opik-frontend/src/types/shared.ts

[OPIK-1725] Add option to close callout explainers

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/openai/OpenaiModelName.java

Add support for o3-mini model in playground

[OPIK-935] Add support for o3-mini model in playground

---

.github/workflows/documentation_codeblock_tests.yml
.github/workflows/documentation_image_optimizer.yml
.github/workflows/documentation_preview_link.yml
.github/workflows/end2end_suites.yml
.github/workflows/lib-integration-tests-runner.yml
.github/workflows/python_sdk_unit_tests.yml
.github/workflows/sdk-e2e-library-tests.yaml
.github/workflows/sdk-e2e-tests.yaml
sdks/python/tests/unit/decorator/test_tracker_outputs.py

Fixed the issue with workflows running tests in main branch.

Remove 'target' from workflows trigger event

---

README.md

The readme contains broken links to subsections because of the emojis. Fixing them.

Fix broken links on the README.md

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/session/RedirectResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/RedirectService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/RedirectResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/session/RedirectResourceTest.java

Redirect endpoint for optimizer

[OPIK-1594] Redirect endpoint for optimizer

---

apps/opik-frontend/src/api/traces/useTracesList.ts
apps/opik-frontend/src/components/pages-shared/experiments/CompareExperimentsOutputCell/CompareExperimentsOutputCell.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsViewer.tsx
apps/opik-frontend/src/lib/filters.ts
apps/opik-frontend/src/lib/traces.ts
apps/opik-frontend/src/types/datasets.ts
apps/opik-frontend/src/types/traces.ts

[OPIK-1681] [FE] Adapt experiment compare and project pages to handle auto-generated traces

---

deployment/helm_chart/opik/templates/ingress.yaml

add support for TLS secret for ingress in Opik helm chart

---

apps/opik-guardrails-backend/Dockerfile

Making sure that all files are owned by the running user
Resolves #

Set the correct permissions in the guardrails image

---

apps/opik-python-backend/src/opik_backend/executor_docker.py

- Report metrics in Millisecond instead of seconds

NA: Using ms instead of sec on metrics

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/aws/AwsModule.java

Disable SHA-256 validation for MinIO
Verified in https://self-hosted-eks.dev.comet.com/ environment

[NA] Disable SHA-256 validation for MinIO

---

.github/workflows/build_apps.yml

[OPIK-1809] For Hotfix branches set version that fits semver format

---

apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/ExperimentResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java

Tiny follow-up fix for #2336  on Experiment tests.
In addition, some small tech debt deduction in related tests and clients
#2147 
- Run Experiments tests locally.
N/A

issue-2147: Follow-up fix pr-2336 on Experiment tests

---

apps/opik-frontend/src/api/datasets/useDatasetItemBatchMutation.ts
apps/opik-frontend/src/components/pages-shared/experiments/ExperimentsActionsPanel/FilterExperimentsToCompareDialog.tsx
apps/opik-frontend/src/components/pages-shared/llm/ManageAIProviderDialog/ManageAIProviderDialog.tsx
apps/opik-frontend/src/components/pages-shared/llm/PromptModelSettings/PromptModelConfigs.tsx
apps/opik-frontend/src/components/pages-shared/traces/AddToDatasetDialog/AddToDatasetDialog.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsDialog.tsx
apps/opik-frontend/src/components/pages/DatasetsPage/AddEditDatasetDialog.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/AddEditProjectDialog.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/EditPromptVersionDialog.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/UseThisPromptDialog.tsx
apps/opik-frontend/src/components/pages/PromptsPage/AddEditPromptDialog.tsx
apps/opik-frontend/src/components/shared/ConfirmDialog/ConfirmDialog.tsx
apps/opik-frontend/src/components/shared/ExplainerDescription/ExplainerDescription.tsx
apps/opik-frontend/src/components/shared/Loader/Loader.tsx
apps/opik-frontend/src/components/shared/UploadField/UploadField.tsx
apps/opik-frontend/src/lib/file.test.ts
apps/opik-frontend/src/lib/file.ts
apps/opik-frontend/src/lib/images.test.ts
apps/opik-frontend/src/main.scss

[OPIK-229] [FE] Ability to upload datasets items from a file 

---

apps/opik-frontend/src/lib/traces.test.ts
apps/opik-frontend/src/lib/traces.ts

[OPIK-1709] Add support for "pretty mode" in OpenAI Agents threads

---

apps/opik-frontend/src/components/pages/TracesPage/ThreadsTab/ThreadsTab.tsx
apps/opik-frontend/src/constants/explainers.ts
apps/opik-frontend/src/types/traces.ts

[OPIK-1701] [FE] - Display Token Count and Cost Metrics in Thread Table

---

apps/opik-frontend/src/api/traces/useThreadsList.ts
apps/opik-frontend/src/components/pages/TracesPage/ThreadsTab/ThreadsTab.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesSpansTab.tsx
apps/opik-frontend/src/lib/sorting.ts
apps/opik-frontend/src/types/shared.ts

[OPIK-1704] [FE] - Enable Sorting on All Thread Table Columns

---

sdks/opik_optimizer/src/opik_optimizer/utils.py
sdks/opik_optimizer/tests/unit/test_utils.py

Allows console display of the optimization run
Includes tests
Not needed as these are internal functions

opik-optimizer: add optimization run display link

---

apps/opik-documentation/documentation/fern/docs/tracing/integrations/adk.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/langgraph.mdx
apps/opik-documentation/documentation/fern/docs/tracing/integrations/openai_agents.mdx

Agent integration thread logging

---

sdks/typescript/src/opik/integrations/opik-langchain/package-lock.json
sdks/typescript/src/opik/integrations/opik-langchain/package.json
sdks/typescript/src/opik/integrations/opik-langchain/src/OpikCallbackHandler.ts

- updated Opik client version
- fixed trace hierarchy relationship management
Resolves #

[OPIK-1711] fix trace hierarchy relationship management

---

deployment/docker-compose/docker-compose.yaml
deployment/helm_chart/opik/Chart.yaml
deployment/helm_chart/opik/README.md

[OPK-1899] upgrade zookeeper

---

sdks/python/tests/unit/evaluation/metrics/test_sentiment.py

Fixed the unit test that was accidentally merged in failing state.

[NA] Fix unit tests

---

apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java

OPIK-1708: Fix unintended commit

---

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/redis/RedissonLockService.java

- Given the new method `executeWithLockCustomExpire`, it's possible that the lock leasing is longer than the default `distributedLockConfig`. For this reason, the expiration has to be adjusted.

NA: Fix possible expiration before end of lock leasing

---

apps/opik-backend/config.yml
apps/opik-backend/src/main/java/com/comet/opik/OpikApplication.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/DatabaseUtils.java

Add SSL validation for MySQL
Tested withing https://comet-ml.atlassian.net/browse/OPIK-1914

[OPIK-1913] Add SSL validation for MySQL

---

apps/opik-backend/pom.xml
apps/opik-backend/src/main/java/com/comet/opik/api/metrics/WorkspaceMetricRequest.java
apps/opik-backend/src/main/java/com/comet/opik/api/metrics/WorkspaceMetricResponse.java
apps/opik-backend/src/main/java/com/comet/opik/api/metrics/WorkspaceMetricsSummaryRequest.java
apps/opik-backend/src/main/java/com/comet/opik/api/metrics/WorkspaceMetricsSummaryResponse.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/WorkspacesResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/IdGenerator.java
apps/opik-backend/src/main/java/com/comet/opik/domain/IdGeneratorImpl.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/WorkspaceMetricsDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/WorkspaceMetricsService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/IdGeneratorModule.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/WorkspaceResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceIntegrationTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/WorkspacesResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/domain/TraceServiceImplTest.java

Workspace daily metrics endpoint
https://www.notion.so/cometml/Home-Page-Tech-HLD-2097124010a380d098cfc0b378819713#20d7124010a380918a83ddb12a2494ad

[OPIK-1853] Workspace daily metrics endpoint

---

.github/workflows/release-n8n-wrapper.yaml
.github/workflows/release.yaml

Adding ability to call release action from n8n with callback for slack bot

modifying release action & adding release n8n wrapper

---

apps/opik-frontend/src/lib/traces.ts

Try to fix Langgraph pretty formatter

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml
deployment/helm_chart/opik/values.yaml

[DEV-2757](https://comet-ml.atlassian.net/browse/DEV-2757)
[DEV-2757]: https://comet-ml.atlassian.net/browse/DEV-2757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-2757] fix serviceAccount and use flat backup by default

---

apps/opik-frontend/src/lib/traces.ts

Add support for Dify Format in pretty mode.
Before:
After:

Update pretty code to support Dify input format

---

apps/opik-frontend/package-lock.json

* Fixed the vulnerability on the FE, checked the build, it worked correctly - will build docker images and after that it can be merged
Resolves #

[NA]: update dependencies in package-lock.json to latest versions

---

apps/opik-frontend/src/components/pages-shared/traces/ThreadDetailsPanel/ThreadDetailsPanel.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDetailsPanel.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsPanel.tsx
apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx
apps/opik-frontend/src/components/shared/ResizableSidePanel/ResizableSidePanel.tsx

[OPIK-1933] Update Sidebar Hotkeys for better item and detail navigation

---

apps/opik-backend/src/main/java/com/comet/opik/domain/WorkspaceMetricsDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/WorkspacesResourceTest.java

[OPIK-1977] Fix dates mismatch in metrics

---

apps/opik-python-backend/src/opik_backend/demo_data.py
apps/opik-python-backend/src/opik_backend/demo_data_generator.py

Generate proper demo data
Checked with local installation

[OPIK-1979] Generate proper demo data

---

apps/opik-frontend/src/components/pages/HomePage/CostOverview.tsx
apps/opik-frontend/src/components/pages/HomePage/MetricsOverview.tsx
apps/opik-frontend/src/components/pages/HomePage/ViewDetailsButton.tsx
apps/opik-frontend/src/components/shared/PercentageTrend/PercentageTrend.tsx

[OPIK-1843] [FE] Build a Metrics charts section - add tooltip

---

apps/opik-documentation/documentation/fern/docs/tracing/integrations/adk.mdx
apps/opik-documentation/python-sdk-docs/source/integrations/adk/index.rst
apps/opik-documentation/python-sdk-docs/source/integrations/adk/track_adk_agent_recursive.rst

Document the new `track_adk_agent_recursive` helper function and add troubleshooting section
Resolves #

Update ADK documentation

---

sdks/python/src/opik/integrations/openai/openai_chat_completions_decorator.py
sdks/python/src/opik/integrations/openai/opik_tracker.py
sdks/python/src/opik/integrations/openai/stream_patchers.py
sdks/python/tests/library_integration/openai/test_openai_chat_completions_beta_api.py

Openai updated API (stream and parse functions were moved from beta to official stable API) and some important implementation details in 1.92.0, this PR updates opik integration to support these changes properly.
Added new integration tests, updated some of the old ones.
All tests suits were manually run on the older openai version to make sure there is no regression (our current CI doesn't have separate tests for older library versions).

[NA] Implement updated OpenAI API support

---

apps/opik-documentation/documentation/fern/docs/tracing/integrations/gemini.mdx

fix https://github.com/comet-ml/opik/issues/2583
align code snippet to use the same as colab example. 
Resolves #

[ISSUE-2583] outdated gemini doc

---

apps/opik-frontend/src/components/shared/DataTableCells/ErrorsCountCell.tsx
apps/opik-frontend/src/types/projects.ts

[OPIK-1978] improve error copies

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/values.yaml

add workaround for clickhouse operator template bug

---

apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000030_add_project_configs_table.sql
apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000031_extend_comments_entity_type_thread.sql

NA: Fix migration version

---

apps/opik-backend/src/main/java/com/comet/opik/api/TraceThread.java
apps/opik-backend/src/main/java/com/comet/opik/api/TraceThreadUpdate.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadIdDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadIdService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadService.java
apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000031_add_tags_to_trace_threads.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Update thread endpoint. Could be used to add tags to threads.

[OPIK-1786] Update thread endpoint

---

.github/workflows/documentation_deploy.yml
.github/workflows/documentation_preview_link.yml
apps/opik-documentation/documentation/fern/docs/evaluation/log_experiments_with_rest_api.mdx
apps/opik-documentation/documentation/fern/fern.config.json
apps/opik-documentation/documentation/package-lock.json
apps/opik-documentation/documentation/package.json

Update to docs for logging experiements using bulk experiment item upload

Update rest api docs for experiments

---

apps/opik-backend/src/main/java/com/comet/opik/api/sorting/ExperimentSortingFactory.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortableFields.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java

Add sorting by average duration for experiments

[OPIK-1965] Add sorting by average duration for experiments

---

apps/opik-frontend/src/api/traces/useThreadUpdateMutation.ts
apps/opik-frontend/src/components/pages-shared/traces/ThreadDetailsPanel/ThreadDetailsPanel.tsx
apps/opik-frontend/src/components/pages-shared/traces/ThreadDetailsPanel/ThreadDetailsTags.tsx
apps/opik-frontend/src/components/pages/TracesPage/ThreadsTab/ThreadsTab.tsx
apps/opik-frontend/src/types/traces.ts

Manage tags in the Thread details panel
New tags column in the Threads table
Resolves #

[OPIK-1787] tags for threads

---

apps/opik-frontend/src/lib/traces.ts

Fix pretty-mode support for Langgraph + OpenAI Responses

---

apps/opik-frontend/src/components/pages-shared/automations/AddEditRuleDialog/LLMJudgeRuleDetails.tsx
apps/opik-frontend/src/components/pages-shared/llm/PromptModelSelect/PromptModelSelect.tsx
apps/opik-frontend/src/hooks/useLLMProviderModelsData.ts
apps/opik-frontend/src/types/providers.ts

[OPIK-2002] [FE] Remove structured output restriction for the online scoring

---

apps/opik-documentation/documentation/fern/docs.yml
apps/opik-documentation/documentation/fern/docs/agent_optimization/opik_optimizer/models.mdx
apps/opik-documentation/documentation/fern/docs/agent_optimization/opik_optimizer/reference.mdx
apps/opik-documentation/documentation/fern/docs/cookbook/huggingface_datasets_integration.mdx

Doc updates

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/templates/configmap-frontend-nginx.yaml
deployment/helm_chart/opik/values.yaml

[OPIK-2047] expose swagger with /swagger

---

apps/opik-backend/src/main/java/com/comet/opik/api/Prompt.java
apps/opik-backend/src/main/java/com/comet/opik/api/filter/FieldType.java
apps/opik-backend/src/main/java/com/comet/opik/api/filter/FiltersFactory.java
apps/opik-backend/src/main/java/com/comet/opik/api/filter/PromptField.java
apps/opik-backend/src/main/java/com/comet/opik/api/filter/PromptFilter.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/PromptResource.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortingFactoryPrompts.java
apps/opik-backend/src/main/java/com/comet/opik/domain/PromptDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/PromptService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java
apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterStrategy.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/SetFlatArgumentFactory.java
apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000019_add_tags_to_prompts.sql
apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000021_add_tags_to_prompts.sql
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/PromptResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Tagging and filtering support for prompts

[OPIK-2025] Tagging and filtering support for prompts

---

apps/opik-frontend/src/components/pages-shared/experiments/VerticallySplitCellWrapper/VerticallySplitCellWrapper.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsActionsPanel.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx
apps/opik-frontend/src/components/pages/PromptPage/ExperimentsTab/ExperimentsTab.tsx
apps/opik-frontend/src/components/shared/DataTableCells/DurationCell.tsx
apps/opik-frontend/src/lib/sorting.ts
apps/opik-frontend/src/types/datasets.ts
apps/opik-frontend/src/types/projects.ts
apps/opik-frontend/src/types/shared.ts

[OPIK-1966] [FE] Add Duration as a new selectable column to the Experiment and Experiment Detail views

---

apps/opik-frontend/src/components/pages-shared/automations/AddEditRuleDialog/AddEditRuleDialog.tsx
apps/opik-frontend/src/components/pages/OnlineEvaluationPage/OnlineEvaluationPage.tsx
apps/opik-frontend/src/components/pages/TracesPage/RulesTab/RulesTab.tsx
apps/opik-frontend/src/constants/explainers.ts

[OPIK-1779] hide Thread rules

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringEngine.java

This PR has fixes for some minor comments that were left in #2689

[NA] fix minor comments from PR #2689

---

apps/opik-frontend/src/components/pages-shared/traces/AddTagDialog/AddTagDialog.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesActionsPanel.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesSpansTab.tsx

Added the ability to Tag multiple traces at once within a Project 
Resolves #1009 
https://github.com/user-attachments/assets/8217068c-fd97-4384-b2b3-2363bfdc70ba
/claim #1009

feat: added the ability to select tags for multiple tags

---

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringLlmAsJudgeScorer.java
apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadService.java

- Addressing the read consistency issue by streaming threads pending closure, closing, and publishing them
-  Fix the null point caused by the exception without a cause in the Online Scoring subscriber.

OPIK-1778: Fix read consistency issues

---

.github/workflows/sdk-e2e-library-tests.yaml
sdks/python/src/opik/evaluation/models/litellm/opik_monitor.py
sdks/python/tests/e2e_library_integration/litellm/constants.py
sdks/python/tests/e2e_library_integration/litellm/test_litellm_chat_model.py
sdks/python/tests/e2e_library_integration/litellm/test_opik_logging.py

Implemented a fix, added a new test.

[NA] Fix bug with missing litellm spans inside LLM-judge spans

---

apps/opik-backend/src/main/java/com/comet/opik/api/Prompt.java
apps/opik-backend/src/main/java/com/comet/opik/api/filter/Field.java
apps/opik-backend/src/main/java/com/comet/opik/api/filter/FieldType.java
apps/opik-backend/src/main/java/com/comet/opik/api/filter/FiltersFactory.java
apps/opik-backend/src/main/java/com/comet/opik/api/filter/PromptField.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortableFields.java
apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortingFactoryPrompts.java
apps/opik-backend/src/main/java/com/comet/opik/domain/PromptDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/PromptService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/PromptResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Enable sorting and filtering on all prompt columns

[OPIK-2057] Enable sorting and filtering on all prompt columns

---

apps/opik-backend/src/main/java/com/comet/opik/api/TraceThreadSampling.java
apps/opik-backend/src/main/java/com/comet/opik/api/events/TraceThreadsCreated.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringTraceThreadLlmAsJudgeScorer.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/TraceThreadOnlineScoringSamplerListener.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadMapper.java
apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadService.java
apps/opik-frontend/src/constants/llm.ts

- Fix issues with read consistency by sending entities into events.
- Fix LLM as Judge template to match the JSON schema property name.

OPIK-1778: Fix issues with read consistency by send entities into events

---

apps/opik-frontend/src/constants/llm.ts

[OPIK-1779] update the llm as judge prompts

---

apps/opik-frontend/src/api/prompts/usePromptUpdateMutation.ts
apps/opik-frontend/src/api/prompts/usePromptsList.ts
apps/opik-frontend/src/components/pages-shared/traces/ThreadDetailsPanel/ThreadDetailsTags.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TagList/TagList.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptPage.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTagsList.tsx
apps/opik-frontend/src/components/pages/PromptsPage/PromptsPage.tsx
apps/opik-frontend/src/components/shared/TagListRenderer/TagListRenderer.tsx
apps/opik-frontend/src/types/prompts.ts

[OPIK-2026] [FE] Tagging and filtering support for Prompts

---

apps/opik-frontend/src/api/datasets/useDatasetUpdateMutation.ts
apps/opik-frontend/src/api/datasets/useDatasetsList.ts
apps/opik-frontend/src/api/prompts/usePromptsList.ts
apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx
apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetTagsList.tsx
apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx
apps/opik-frontend/src/types/datasets.ts

[OPIK-2032] [FE] Add tags support to datasets

---

apps/opik-frontend/src/lib/date.test.ts
apps/opik-frontend/src/lib/date.ts

[OPIK-2077] [Metrics-> Duration] FE round very small duration to 0

---

apps/opik-python-backend/src/opik_backend/demo_data.py

- Remove error log to reduce the noise

OPIK-2076: Remove empty array as it was causing error logs and creating noise

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/TraceDataViewer.tsx
apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/VirtualizedTreeViewer.tsx
apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricChart/MetricChartContainer.tsx
apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricsTab.tsx

[OPIK-1936] [M2] Minor changes in spans details view

---

apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx
apps/opik-frontend/src/components/pages/PromptsPage/PromptsPage.tsx

- add missed columns to tabel
Resolves #

[OPIK-2058] [FE] Enable sorting and filtering on all Prompt columns

---

apps/opik-frontend/src/plugins/comet/init.tsx
apps/opik-frontend/src/plugins/comet/newrelic/index.ts
apps/opik-frontend/src/plugins/comet/newrelic/snippet.js

[OPIK-2106] [FE] Add newrelic support to Opik FE as part of comet plugin

---

.github/copilot-instructions.md

NA: Add copilot instructions for Code Review new revision

---

apps/opik-backend/src/main/java/com/comet/opik/api/events/TracesDeleted.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/CommentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java
apps/opik-backend/src/main/java/com/comet/opik/domain/attachment/AttachmentDAO.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/DatabaseUtils.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/events/BaseEvent.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Trace thread deletion should also delete related entities

[OPIK-2078] Trace thread deletion should also delete related entities

---

apps/opik-frontend/src/components/pages-shared/attachments/AttachmentPreviewDialog/AttachmentPreviewDialog.tsx
apps/opik-frontend/src/components/pages-shared/attachments/AttachmentThumbnail/AttachmentThumbnail.tsx
apps/opik-frontend/src/components/shared/ZoomPanContainer/ZoomPanContainer.tsx

[OPIK-2071] [UX improvements] Improvements to full-screen popup

---

apps/opik-backend/.cursor/rules/branch_name.mdc

NA: Add cursor rule for Git Flow

---

CONTRIBUTING.md

add general contribution guidelines to CONTRIBUTING.md;

---

sdks/python/src/opik/config.py
sdks/python/src/opik/error_tracking/environment_details.py
sdks/python/src/opik/integrations/langchain/anthropic_run_helpers.py

Added collecting of versions of packages that are potentially useful for debugging and errors investigation to sentry events.
Update Sentry DSN token to prepare for rotation.

[NA] Add more metadata about package versions to sentry events

---

apps/opik-frontend/src/components/pages/ConfigurationPage/WorkspacePreferencesTab/WorkspacePreferencesTab.tsx

[OPIK-1917] show edit preference dialog if data isPending

---

opik.sh

- Create a local config file that points by default to the local installation.
First time:
Once created:

OPIK-2145: Create local config file

---

opik.ps1
opik.sh

- Create a local config file that points by default to the local installation.

OPIK-2145: Create local config file on Win

---

sdks/python/src/opik/integrations/bedrock/converse_decorator.py

Before this PR model name (modelId) was missing.

[NA] Alexkuzmik/add model id to bedrock converse calls

---

apps/opik-backend/src/main/java/com/comet/opik/api/filter/FiltersFactory.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java

Support list like keys for custom filters

[OPIK-2194] Support list like keys for custom filters

---

.github/workflows/release-wrapper-release-n-deploy.yml

adding action for release-n-deploy (#2917)

---

apps/opik-backend/config.yml
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/jobs/TraceThreadsClosingJob.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/JobTimeoutConfig.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/OpikConfiguration.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/bi/DailyUsageReportJob.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/bi/OpikGuiceyLifecycleEventListener.java
apps/opik-backend/src/test/resources/config-test.yml

Fix hanging tests

---

apps/opik-backend/.cursor/rules/api_design.mdc
apps/opik-backend/.cursor/rules/architecture.mdc
apps/opik-backend/.cursor/rules/business_logic.mdc
apps/opik-backend/.cursor/rules/code_quality.mdc
apps/opik-backend/.cursor/rules/db_migration_script.mdc
apps/opik-backend/.cursor/rules/error_handling.mdc
apps/opik-backend/.cursor/rules/general.mdc
apps/opik-backend/.cursor/rules/logging.mdc
apps/opik-backend/.cursor/rules/mysql.mdc
apps/opik-backend/.cursor/rules/tech_stack.mdc
apps/opik-backend/.cursor/rules/testing.mdc

This PR applies foundational rules to existing backend coding guidelines by expanding and restructuring the current rule files into comprehensive, well-documented guidelines for the Opik backend development.
- Converts brief rule files into comprehensive documentation with code examples
- Adds detailed explanations and best practices for each development area
- Maintains backward compatibility while enhancing clarity and usability
OPIK-2197
N/A
N/A

[OPIK-2197] Apply foundational rules on existing BE rules

---

sdks/python/src/opik/api_objects/opik_client.py
sdks/python/src/opik/api_objects/prompt/client.py
sdks/python/src/opik/api_objects/prompt/prompt.py

Refactored Prompt implementation to reduce the amount of cyclic references, cleaned up the code.

[NA] Alexkuzmik/improve prompt implementation

---

.cursor/rules/clean-code.mdc

This PR adds a new clean code guidelines document to establish industry-standard coding practices for the team. The guidelines cover fundamental principles like meaningful naming, single responsibility, DRY principle, and proper code organization.
- Introduces a comprehensive clean code guidelines document
- Establishes consistent coding standards across the codebase
- Provides documentation for best practices in code quality and maintainability
OPIK-2201
N/A
- https://github.com/PatrickJS/awesome-cursorrules

[OPIK-2201] Add industry standard rules

---

apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/quickstart-integrations.ts

[OPIK-2200] hide run button

---

.github/workflows/sdks_generate_openapi_spec_and_fern_code.yml
.github/workflows/span_cost_upload_daily.yml

This PR standardizes GitHub Actions workflows that automatically create PRs by aligning them with the repository's branch naming conventions and PR template requirements. The changes ensure consistency across automated workflows and improve their adherence to project guidelines.
- Updated cron schedules to run only on weekdays instead of daily
- Standardized branch naming to follow the `github-actions/NA-*` pattern with timestamps
- Enhanced PR templates to include proper sections and formatting
- OPIK-2246
- Cost job: https://github.com/comet-ml/opik/actions/runs/16934994156/job/47989315331
- Cost branch: https://github.com/comet-ml/opik/compare/github-actions/NA-automatically-update-model-prices-file-2025-08-13-10-48-02
- Fern Job: …

[OPIK-2246] [INFRA] Follow repository guidelines on actions automating PRs

---

apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Ollama.py
apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Ragas.py

Fix code highlighting for Ollama and Ragas

[OPIK-2230] [FE] Follow-up changes to framework integration scripts

---

apps/opik-backend/docs/diagrams/trace-batch-ingestion-flow.md

This PR adds comprehensive documentation for the trace batch ingestion flow in the Opik backend service through a new Mermaid diagram documentation file. The documentation includes detailed architectural diagrams, component relationships, and flow explanations to help developers understand the complex event-driven ingestion system.
Key changes:
- Adds detailed architectural documentation with multiple Mermaid diagrams
- Documents the complete trace batch ingestion flow from client request to event processing
- Provides component details, technology stack information, and performance optimizations
- OPIK-2256
- Visualised in Cursor preview with Mermaid markdown support.
- https://docs.cursor.com/en/guides/tutorials/architectural-diagrams
- …

[OPIK-2256] [DOCS] [BE] Add sample automatic Mermaid diagram

---

apps/opik-frontend/.cursor/rules/accessibility-testing.mdc
apps/opik-frontend/.cursor/rules/api-data-fetching.mdc
apps/opik-frontend/.cursor/rules/code-quality.mdc
apps/opik-frontend/.cursor/rules/forms.mdc
apps/opik-frontend/.cursor/rules/frontend_rules.mdc
apps/opik-frontend/.cursor/rules/performance.mdc
apps/opik-frontend/.cursor/rules/state-management.mdc
apps/opik-frontend/.cursor/rules/tech-stack.mdc
apps/opik-frontend/.cursor/rules/ui-components.mdc
apps/opik-frontend/.cursor/rules/unit-testing.mdc

[OPIK-2243]: fix the rules of FE opik

---

apps/opik-backend/src/main/java/com/comet/opik/domain/template/MustacheParser.java

Fix template parser exception propagation, from NewRelic https://onenr.io/0qwLDAWOOw5
- Resolves #
- OPIK-NA

[NR] Fix template parser exception propagation

---

apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx
apps/opik-frontend/src/plugins/comet/useInviteMembersURL.ts

[OPIK-2281] revert invite button from the sidebar

---

apps/opik-documentation/documentation/fern/docs/evaluation/evaluate_your_llm.mdx

OPIK-2276 Add docs to explain how to pass additional args to evaluation_task

---

apps/opik-documentation/documentation/fern/docs/quickstart.mdx

Focus on the happy path first and the troubleshooting later

[DOCS] Move troubleshooting section to end of the Quickstart

---

apps/opik-backend/src/main/java/com/comet/opik/api/metrics/ProjectMetricRequest.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java

Add filter capabilities to the Metrics tab
- Resolves #
- OPIK-2149
https://comet-ml.atlassian.net/browse/OPIK-2051

[OPIK-2149] Add filters to the metrics tab

---

apps/opik-frontend/src/components/pages-shared/experiments/ExperimentsActionsPanel/ExperimentsActionsPanel.tsx
apps/opik-frontend/src/components/pages-shared/llm/LLMJudgeScores/LLMJudgeScore.tsx
apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsActionsPanel.tsx
apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx
apps/opik-frontend/src/components/pages/HomePage/ProjectSelector.tsx
apps/opik-frontend/src/components/pages/OptimizationsPage/OptimizationsPage.tsx
apps/opik-frontend/src/components/pages/PromptPage/CommitsTab/CommitsActionsPanel.tsx
apps/opik-frontend/src/components/pages/PromptPage/PromptTab/PromptTab.tsx
apps/opik-frontend/src/components/pages/PromptPage/TryInPlaygroundButton.tsx
apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricsTab.tsx
apps/opik-frontend/src/components/pages/TracesPage/TracesPage.tsx
apps/opik-frontend/src/components/shared/ColumnsButton/ColumnsButton.tsx
apps/opik-frontend/src/components/shared/DataTableRowHeightSelector/DataTableRowHeightSelector.tsx
apps/opik-frontend/src/components/shared/ExperimentFeedbackScoresViewer/AddFeedbackScorePopover.tsx
apps/opik-frontend/src/components/shared/FiltersButton/FiltersButton.tsx
apps/opik-frontend/src/components/shared/GroupsButton/GroupsButton.tsx
apps/opik-frontend/src/plugins/comet/InviteUsersForm.tsx

This PR improves the discoverability of the compare experiments functionality by making UI elements more prominent and consistent across the application.
- **Enhanced Compare Button Visibility**: Changed the "Compare" button from `outline` variant to solid variant to make it more prominent and discoverable
- **Improved DataTableRowHeightSelector UX**: Refactored from `ToggleGroup` with icons to `DropdownMenu` with labeled options ("Small", "Medium", "Large") for better user experience and clarity
- **Consistent Button Styling**: Updated button variants and spacing across multiple components for better visual hierarchy
- **Icon and Spacing Improvements**: Standardized icon sizes and margins for better visual consistency
- ExperimentsActionsPanel - Made Compare button more prominent
- …

[OPIK-2234] [FE] Improve compare experiments discoverability

---

.github/workflows/pr-lint.yml

make component tag optional and make issues section optional if [NA] in title
NA

[NA] [GHA] PR Linter - make component tag optional and make issues section optional if [NA] in title

---

apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
apps/opik-backend/src/test/java/com/comet/opik/domain/stats/StatsMapperTest.java

Add spans average count for trace stats. Requested by FGAI.
- Resolves #
- OPIK-2275
Modified existing integration tests to cover it.
NA

[OPIK-2275] [BE] Add spans average count for trace stats

---

sdks/typescript/src/opik/integrations/opik-langchain/package.json

Updated the version of langchain integration after Jacques` changes
- [] User facing
- [] Documentation update
- Resolves #
- OPIK-

[NA] [TS-SDK]: Update opik-langchain package version to 1.0.3

---

apps/opik-documentation/documentation/fern/docs/tracing/integrations/langchain.mdx

Updated langchain integration documentation page.
- Resolves #
- OPIK-
-
Updated

[NA] [SDK] alexkuzmik / Update langchain integration docs

---

sdks/typescript/src/opik/integrations/opik-langchain/package-lock.json
sdks/typescript/src/opik/integrations/opik-langchain/package.json

- fixed LangChain integration build flow
- Resolves #
- OPIK-

[NA] [SDK] add tsup and upgrade opik version

---

.cursor/commands/comet/create-pr.md

Added a comprehensive Cursor command for creating GitHub Pull Requests with automatic Jira integration, quality checks, and template pre-filling. The command ensures code quality and proper workflow integration before creating PRs by following Opik Git workflow conventions.
- OPIK-2322 
This PR has been created by using this command itself: `/comet/create-pr`
- https://docs.cursor.com/en/agent/chat/commands

[OPIK-2322] [DOCS] Add create PR cursor command

---

apps/opik-frontend/src/components/pages-shared/onboarding/IntegrationExplorer/components/HelpGuideDialog.tsx

- add Opik University link
- Resolves #
- OPIK-2321

[OPIK-2321] add Opik University link

---

deployment/docker-compose/docker-compose.yaml
deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/values.yaml

use bitnamilegacy zookeeper images
- Resolves #
- OPIK-2330

[OPIK-2330] [HELM] [DC] use bitnamilegacy zookeeper images

---

apps/opik-documentation/documentation/fern/docs/evaluation/metrics/custom_model.mdx

Fix a typo in custom_model
- Resolves #
- OPIK-

[NA] [DOCS] Fix typo in custom_model.mdx

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceAnnotateViewer/TraceAnnotateViewer.tsx
apps/opik-frontend/src/components/shared/ExperimentFeedbackScoresViewer/AddFeedbackScorePopover.tsx

- fix bug when reason value from previous trace/span was filled in the next one
- Resolves #
- OPIK-2366

[OPIK-2366] fix the key for feedbackscores editor

---

sdks/typescript/src/opik/integrations/opik-langchain/package-lock.json
sdks/typescript/src/opik/integrations/opik-langchain/package.json
sdks/typescript/src/opik/integrations/opik-langchain/src/OpikCallbackHandler.ts
sdks/typescript/src/opik/integrations/opik-langchain/src/utils.ts
sdks/typescript/src/opik/integrations/opik-langchain/tests/OpikCallbackHandler.test.ts
sdks/typescript/src/opik/integrations/opik-langchain/tests/index.test.ts
sdks/typescript/src/opik/integrations/opik-langchain/tests/utils.test.ts
sdks/typescript/src/opik/integrations/opik-langchain/vitest.config.ts

- added unit tests
- added missed deps
- validated all npm commands 
- Resolves #
- OPIK-2325

[OPIK-2325] langchain integration tests and build fix

---

apps/opik-backend/config.yml
apps/opik-backend/src/main/java/com/comet/opik/domain/evaluators/python/PythonEvaluatorService.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/OpikConfiguration.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/PythonEvaluatorConfig.java
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/RetriableHttpClient.java
apps/opik-backend/src/main/java/com/comet/opik/utils/RetryUtils.java
apps/opik-backend/src/test/java/com/comet/opik/domain/evaluators/python/PythonEvaluatorServiceTest.java

This PR enhances the Python evaluator service with proper variable names and descriptions. Also, it reduces the mocking usage by using Pojos when possible. 
- NA
NA
NA

[NA] [BE] Address remaining comments from Python Evaluation retry PR

---

apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000024_create_alerts_webhooks_tables.sql

-  Create main tables for Alert MVP
- OPIK-2084

[OPIK-2084] [BE] OPIK-2085: Add Alert tables

---

sdks/python/src/opik/api_objects/experiment/helpers.py
sdks/python/tests/e2e/verifiers.py
sdks/python/tests/unit/api_objects/experiment/test_helpers.py

Use prompt name in experiment config
#1897
- Resolves #
- OPIK-NA
Updated corresponding tests
NA

[OPIK-000] [SDK] Issue-1897 Use prompt name in experiment config

---

apps/opik-documentation/documentation/fern/docs/cookbook/OpikOptimizerIntro.mdx
apps/opik-documentation/documentation/fern/docs/cookbook/quickstart_notebook.mdx
apps/opik-documentation/documentation/fern/docs/evaluation/concepts.mdx
apps/opik-documentation/documentation/fern/docs/evaluation/metrics/custom_metric.mdx
apps/opik-documentation/documentation/fern/docs/production/rules.mdx
apps/opik-documentation/documentation/fern/docs/quickstart.mdx
apps/opik-documentation/documentation/fern/docs/tracing/log_chat_conversations.mdx
apps/opik-documentation/documentation/fern/docs/tracing/sdk_configuration.mdx

[NA] [Docs] Fix typos

---

.cursor/commands/comet/work-on-github-issue.md

Created a new Cursor command for working on GitHub issues, adapted from the existing work-on-jira-ticket command. This command provides a comprehensive workflow for:
- Fetching GitHub issues by link and building full context (title, description, comments, labels, assignees, milestone)
- Validating feature branch naming conventions following Opik standards
- Generating actionable implementation plans based on issue context and Opik cursor rules
- Managing git workflow with proper branch creation and status management
- Providing implementation suggestions with proper commit message formatting
Key adaptations from Jira to GitHub:
- Updated MCP integration for GitHub API instead of Jira
- Changed branch naming from `OPIK-{NUMBER}` to `issue-{NUMBER}`
- Adapted issue context building for …

[OPIK-2405] [DOCS] Add cursor work-on-github-issue command

---

.github/workflows/clickhouse_migration_cluster_check.yml
scripts/check_clickhouse_migrations_cluster.sh

This PR implements a comprehensive GitHub workflow to validate that all ClickHouse DDL statements in migration files include the required `ON CLUSTER '{cluster}'` clause for distributed execution. This ensures consistency across all nodes in a ClickHouse cluster and prevents partial schema updates.
**GitHub Workflow (`.github/workflows/clickhouse_migration_cluster_check.yml`):**
- Triggers on PRs and pushes to `main` when ClickHouse migration files (`.sql`) are modified
- Only validates newly added or modified files (not existing migrations)
- Uses GitHub API for PR file detection and `git diff` for main branch pushes
- Aligned with existing workflow patterns.
- Optimized with `fetch-depth: 1` and `timeout-minutes: 5`
**Validation Script …

[OPIK-2414] [CI/CD] Add PR check for ON CLUSTER statement in ClickHouse migrations

---

deployment/helm_chart/opik/README.md
deployment/helm_chart/opik/values.yaml

fix  image for minio initContainers
- [V] User facing
- Resolves #3305

[issue-3305] fix  image for minio initContainers

---

scripts/check_clickhouse_migrations_cluster.sh

This PR fixes the ClickHouse migration validation script.
- OPIK-2414 
- Tested in CI and locally.
- N/A

[OPIK-2414] [CI] Fix ClickHouse migration validation script

---

sdks/opik_optimizer/.pre-commit-config.yaml
sdks/opik_optimizer/src/opik_optimizer/colbert.py
sdks/opik_optimizer/src/opik_optimizer/few_shot_bayesian_optimizer/reporting.py
sdks/opik_optimizer/src/opik_optimizer/utils.py

Better fallback for search_wikipedia failures.
Fixes search_wikipedia timeouts
N/A
N/A

[NA] [Optimizer] Tweaks for search_wikipedia timeouts

---

.gitignore

Update gitignore to remove caches.
Common cache files used by Opik Optimizer and other SDKs in sub-directories
NA
Tested locally
NA

[NA] [BE/FE] Update Gitignore for Cache Files

---

scripts/dev-runner.sh

This PR introduces a comprehensive local development runner script (`scripts/dev-runner.sh`) that provides a unified interface for managing the complete Opik development environment. The script orchestrates infrastructure (Docker containers), backend (Java), and frontend (React) services with proper dependency management and process lifecycle handling.
- **Infrastructure Layer**: Docker containers (MySQL, Redis, ClickHouse) via `opik.sh --infra --port-mapping`
- **Backend Services**: Java application with Maven build automation  
- **Frontend Services**: React development server with Vite and npm dependency management
- **Service Orchestration**: Proper start/stop order with dependency awareness
- **Smart Start Order**: Infrastructure → Backend → Frontend (dependency-aware)
- **Safe Stop …

[OPIK-2175] [SCRIPTS] Add local dev runner script

---

apps/opik-backend/src/main/java/com/comet/opik/domain/AnnotationQueueDAO.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AnnotationQueuesResourceTest.java

Return number of reviewed items per author in queue
- Resolves #
- OPIK-2489
NA

[OPIK-2489] [BE] Return number of reviewed items per author in queue

---

.github/workflows/opik-optimizer-e2e-tests.yaml

Resolve deps issue with new package requirements in Opik Optimizer. Currently blocking https://github.com/comet-ml/opik/pull/3392
- Resolves #
- OPIK-
n.a
n.a

[NA] [SCRIPTS] Fix CI/CD for Optimizer, Import Deps Issue.

---

apps/opik-python-backend/requirements.txt

Security fix that updates Jinja2 dependency from version 3.1.5 to 3.1.6 in the Python backend service to address a known vulnerability. This is a patch-level update that maintains compatibility while resolving security concerns.
- NA 
- Manually tested the service locally, by running Python Online Evaluations.
- Manually verified the right package ins the image.
- Passed CI tests for this service.
- https://pypi.org/project/Jinja2/

[NA] [BE] Fix Python Backend vulnerability - Update Jinja2

---

.github/workflows/opik-optimizer-e2e-tests.yaml
.github/workflows/opik-optimizer-unit-tests.yaml

Speed up e2e tests by caching the litellm cache on Github actions cache.
- Resolves #
- OPIK-
n/a
n/a

[NA] [SCRIPTS] Speed up e2e Testing for Optimizer with LiteLLM Cache in Actions

---

apps/opik-documentation/documentation/fern/docs/evaluation/metrics/custom_metric.mdx

Improve custom metrics documentation.
- N/A
- N/A
- N/A

[NA][DOCS] Improve custom metrics documentation

---

apps/opik-python-backend/requirements.txt
apps/opik-python-backend/src/opik_backend/demo_data_generator.py

This PR optimizes the demo data generator by replacing the complex concurrent thread processing approach with a simpler and more efficient batch API call.
- NA 
- Existing tests pass: `test_create_demo_data_structure` and `test_create_demo_data_idempotence`
- Verified functionality is preserved while improving performance
1. **Simplified thread closing logic**: Replaced ThreadPoolExecutor with single batch API call
2. **Updated dependency**: Bumped opik from 1.8.33 to 1.8.57 for batch API support
3. **Reduced code complexity**: Removed ~20 lines of concurrent processing code
4. **Improved performance**: Single API call instead of multiple concurrent requests
- **Reduced network overhead**: Batch operation instead of individual API calls
- **Simplified error handling**: Single retry loop …

[NA] [BE] Optimize demo data generator thread closing with batch API

---

.github/workflows/documentation_deploy.yml
apps/opik-documentation/documentation/fern/docs.yml

Add Posthog to documentation
- Resolves #
- OPIK-0000
N/A
N/A

[NA] [Docs] Add analytics to docs

---

apps/opik-documentation/documentation/fern/docs.yml

Tidying up sidebar nav for docs and using shorter names where possible.
- Resolves #
- OPIK-
n/a
n/a

[NA] [DOCS] Update Sidebar Nav

---

.github/workflows/typescript_sdk_integration_publish.yml

fix ts sdk publish workflow
- Resolves #
- OPIK-2566

[OPIK-2566] fix ts sdk publish workflow

---

opik.ps1
scripts/dev-runner.ps1
scripts/dev-runner.sh

This PR adds a comprehensive PowerShell version of the development runner script (`scripts/dev-runner.ps1`) to provide Windows developers with the same local development capabilities as macOS/Linux users who use the bash version (`scripts/dev-runner.sh`).
The new PowerShell script provides complete feature parity with the bash version, including:
- **Build Management**: Maven backend build with test skipping and npm frontend build with dependency installation
- **Service Control**: Start/stop/restart backend and frontend services with proper PID tracking and graceful shutdown
- **Docker Integration**: Start/stop Docker infrastructure services via `opik.ps1` wrapper
- **Database Migrations**: Run MySQL and ClickHouse database migrations with error recovery instructions
- **Status …

[OPIK-2175] Add Windows PowerShell version of dev-runner script

---

sdks/typescript/src/opik/config/Config.ts
sdks/typescript/tests/config.test.ts
sdks/typescript/vitest.config.ts

ts sdk cloud url as default config value
- Resolves #
- OPIK-2522

[OPIK-2522] [SDK] ts sdk cloud url as default

---

apps/opik-backend/src/main/java/com/comet/opik/api/Alert.java
apps/opik-backend/src/main/java/com/comet/opik/api/AlertTrigger.java
apps/opik-backend/src/main/java/com/comet/opik/api/Webhook.java
apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000026_change_webhooks_secret_token_as_nullable.sql

Make secret token as an optional field for Alert
- Resolves #
- OPIK-2588
NA

[OPIK-2588][BE] Make secret token as an optional field for Alert

---

apps/opik-backend/config.yml
apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ServiceTogglesConfig.java
apps/opik-backend/src/test/resources/config-test.yml

Add toggle for alerts
- Resolves #
- OPIK-2589
NA
NA

[OPIK-2589][BE] Add toggle for alerts

---

apps/opik-documentation/documentation/fern/docs/contributing/python-sdk.mdx

Fixed Python SDK documentation to include unit tests
- Resolves #
- OPIK-
No new tests
Changed contributing guide section.

[NA] [DOCS] Fixed Python SDK contributing documentation.

---

apps/opik-backend/src/main/java/com/comet/opik/api/WebhookTestResult.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/WebhookSubscriber.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/webhooks/WebhookHttpClient.java
apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AlertResource.java
apps/opik-backend/src/main/java/com/comet/opik/domain/AlertService.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/AlertResourceClient.java
apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AlertResourceTest.java

Test webhook endpoint
- Resolves #
- OPIK-2103
NA

[OPIK-2103][BE] Test webhook endpoint

---

.cursor/rules/local-development-workflow.mdc

This PR updates and expands the `local-development-workflow.mdc` Cursor rule to favor the usage of `dev-runner.sh` for local development workflows.
- **Reorganized structure** to prioritize `dev-runner.sh` as the primary development approach
- **Added comprehensive quick start** with first-time setup, daily development, and BE-only mode sections
- **Enhanced access information** for both standard and BE-only modes with backend health URLs, Swagger, and MinIO console
- **Expanded SDK development sections** for Python and TypeScript SDKs with local backend configuration
- **Improved Docker development** section with `opik.sh` as an alternative for production-like testing
- **Comprehensive troubleshooting** with port conflicts, Docker issues, and resource management
- **Added data loss …

[OPIK-2175] [DOCS] Update local-development-workflow rule to favor dev-runner.sh usage

---

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceAnnotateViewer/AnnotateRow.tsx
apps/opik-frontend/src/components/pages-shared/traces/UserComment/UserCommentForm.tsx
apps/opik-frontend/src/components/pages/SMEFlowPage/AnnotationView/AnnotationView.tsx
apps/opik-frontend/src/components/pages/SMEFlowPage/AnnotationView/CommentAndScoreViewer.tsx
apps/opik-frontend/src/components/pages/SMEFlowPage/hotkeys.ts
apps/opik-frontend/src/components/ui/button.tsx
apps/opik-frontend/src/components/ui/hotkey-display.tsx
apps/opik-frontend/src/constants/explainers.ts

This PR implements UX improvements for hotkeys navigation in the annotation interface. The changes enhance the user experience by providing better keyboard navigation support and visual feedback for hotkey interactions.
Key improvements include:
- Enhanced hotkey navigation system with improved keyboard shortcuts
- Updated annotation viewer components for better user interaction
- Added dedicated hotkey display UI component for better visibility
- Improved user comment forms with better hotkey integration
- Added explainer constants for hotkey documentation
- Resolves # 
- OPIK-2491 
- NA 
The changes have been tested with:
- Frontend linting and type checking passed
- Manual testing of hotkey navigation functionality
- Verification of annotation viewer improvements
- Testing of user …

[OPIK-2491] [FE] Improve hotkeys navigation
