src/comet_llm/backend_error_codes.py, src/comet_llm/experiment_api/request_exception_wrapper.py, src/comet_llm/handlers/failed_response.py, src/comet_llm/logging_messages.py, tests/unit/experiment_api/test_request_exception_wrapper.py
* now logs error if trying to log to a non llm project
* fixed lint errors
* added an abstract function for handling responses
* added safe mechanism
* fixed lint
* fixes
* fixed lint
* lint
=> [CM-8195] now logs error if trying to log to a non llm project (#67)

deployment/installer/README.md, deployment/installer/opik_installer/__init__.py, deployment/installer/opik_installer/ansible/play.opik-deps.yml, deployment/installer/opik_installer/ansible/roles/comet-opik/defaults/main.yml, deployment/installer/opik_installer/ansible/roles/comet-opik/tasks/main.yml, deployment/installer/opik_installer/opik_constants.py, deployment/installer/opik_installer/version.py
- Add installer `upgrade` sub-command
- Add `--local-port` option to the `install` sub-command to support specifying the locally forwarded port for opik server.
- Reject invoking command as root (this could cause some strange behavior)
- Update defaults to point to the correct values for the public repos/registries for the install artifacts (to reduce required options)
=> Installer UX improvements

deployment/installer/opik_installer/ansible/roles/comet-opik/tasks/main.yml
- Ansible had some trouble identifying the forwarded port on macOS, this has now been addressed.
=> Fix forwarded-port identification on macOS

apps/opik-frontend/src/components/pages/DatasetCompareExperimentsPage/DatasetCompareExperimentsPage.tsx, apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.module.scss, apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.tsx, apps/opik-frontend/src/lib/utils.ts
=> OPIK-21 [UX] Improve UX of the trace component

build_and_run.sh
Used to run queries, inspect and manage the schema etc. during local development.
N/A
Connected to ClickHouse on port 8123 running inside my local Minikube.
N/A
=> [NO-JIRA] Port forward Clickhouse to localhost

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
Handing the following case from the requirements spec:
> NOTE: The behavior of how this endpoint is working can depend of a number of supplied experiments ids. In case of only 1 experiment supplied probably the product team will want to show only dataset items that was used for experiment. This should be clarified with product team. 
In addition, fixed a latent bug in the normal path: join by traces not getting the last trace by update date before joining with feedback scores.
Resolves OPIK-42
- Added integration test.
- Datasets & Experiments API doc.
- Dataset Requirements doc.
=> OPIK-42 Experiment compare for single supplied experiment

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
After discussion, agreed to generalise this behaviour https://github.com/comet-ml/opik/pull/167 for every case.
OPIK-42
- Updated integration tests.
N/A
=> OPIK-42 Compare only dataset items with matching experiment items

.github/workflows/deploy_docs.yaml
Updates the docs build so that the python SDK is installed before running the `make` command to build the python SDK
=> Update docs build workflow

apps/opik-frontend/package-lock.json, apps/opik-frontend/package.json, apps/opik-frontend/src/components/pages/DatasetCompareExperimentsPage/DatasetCompareExperimentsPage.tsx, apps/opik-frontend/src/components/pages/DatasetCompareExperimentsPage/DatasetCompareExperimentsPanel/DatasetCompareExperimentsPanel.tsx, apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx, apps/opik-frontend/src/components/shared/ResizableSidePanel/ResizableSidePanel.tsx, apps/opik-frontend/src/components/shared/TooltipWrapper/TooltipWrapper.tsx, apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceAnnotateViewer/AnnotateRow.tsx, apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceAnnotateViewer/TraceAnnotateViewer.tsx, apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDetailsPanel.tsx, apps/opik-frontend/src/components/ui/tooltip.tsx
Pressing esc should:
- Close the annotation sidebar if it is open
- Close the sidebar if it’s open
Pressing up_arrow or down_arrow should go to the previous and next trace
Resolves #
=> OPIK-20 [UX] Add simple keyboard shortcuts for trace sidebar

apps/opik-frontend/src/components/shared/NewExperimentButton/NewExperimentButton.tsx
Updated the new experiment modal based on the new metrics:
=> Updated new experiment creation modal

apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
Update Find experiment endpoint from the current exact name search to:
- By partial name.
- Case insensitive.
Resolves OPIK-55
- Updated integration test.
N/A
=> OPIK-55 Find experiment by partial name and case-insensitive

apps/opik-backend/config.yml, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/AuthenticationConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/BulkOperationsConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/AuthCredentialsCacheService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/AuthModule.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/CacheService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/redis/LockService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/redis/RedissonLockService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/TestDropwizardAppExtensionUtils.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/AuthModuleCache2E2Test.java, apps/opik-backend/src/test/resources/config-test.yml
=> NA: Add missing cache for sdk auth

apps/opik-documentation/documentation/docs/tracing/log_distributed_traces.md, apps/opik-documentation/documentation/docs/tracing/log_traces.md
In the documentation, the phrase "function annotators" is used, but I think that should be "function decorator".
=> Fix Python terminology

apps/opik-frontend/index.html, apps/opik-frontend/package-lock.json, apps/opik-frontend/package.json, apps/opik-frontend/public/config.js, apps/opik-frontend/src/plugins/comet/WorkspacePreloader.tsx, apps/opik-frontend/src/plugins/comet/analytics/index.ts, apps/opik-frontend/src/plugins/comet/analytics/snippet.js, apps/opik-frontend/src/plugins/comet/analytics/useSegment.ts, apps/opik-frontend/src/plugins/comet/init.tsx, apps/opik-frontend/src/store/PluginsStore.ts
=> [OPIK-63] [New feature] Add segment to Opik Cloud

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/DatabaseAnalyticsModule.java
Minor bug discovered during the query plan analysis task.
The Span creation endpoint was not setting the proper precision for `created_at` field.
Fixed by adding precision 9 to the `now64` call.
Additionally, run spotless to fix formatting issues.
N/A
N/A
=> NO-JIRA Missing now64 precision of 9

apps/opik-backend/src/main/java/com/comet/opik/api/Experiment.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
Applies to the two existing endpoints:
- Get experiment by ID.
- Find experiments.
Datasets are stored in MySQL whereas experiments are in ClickHouse, so there's going to be a performance penalty no matter the implementation.
Implemented the dataset name retrieval in a single DB call in both cases, so there's a single MySQL query per each ClickHouse query.
Nevertheless, it should be fine in production for both endpoints:
- Get experiment by ID: No concern as the size of the response is very small, only one experiment and therefore one dataset is returned.
- Find experiments: it's a paginated call and meant to be used by the UI. As long as the page size has a resonable size, it should be fine. That should always be the case for a UI usage.
OPIK-71
- Updated and verified integration tests. …
=> OPIK-71 Resolve dataset name in experiment endpoints

apps/opik-frontend/src/api/datasets/useExperimentsList.ts, apps/opik-frontend/src/components/layout/Breadcrumbs/Breadcrumbs.tsx, apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/AddExperimentToCompareDialog.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentAddHeader.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsCell.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsHeader.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPage.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsDataViewer.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsPanel.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsViewer.tsx, apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx, apps/opik-frontend/src/components/pages/DatasetPage/DatasetPage.tsx, apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx, apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsActionsButton.tsx, apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx, apps/opik-frontend/src/components/shared/DataTableCells/ResourceCell.tsx, apps/opik-frontend/src/components/shared/DebounceInput/DebounceInput.tsx, apps/opik-frontend/src/components/shared/FeedbackScoresEditor/AddFeedbackScorePopover.tsx, apps/opik-frontend/src/components/shared/LoadableSelectBox/LoadableSelectBox.tsx, apps/opik-frontend/src/components/shared/LoadableSelectBox/NoOptions.tsx, apps/opik-frontend/src/components/shared/NewExperimentButton/NewExperimentButton.tsx, apps/opik-frontend/src/components/shared/SearchInput/SearchInput.tsx, apps/opik-frontend/src/components/ui/button.tsx, apps/opik-frontend/src/components/ui/input.tsx, apps/opik-frontend/src/components/ui/select.tsx, apps/opik-frontend/src/hooks/useDatasetIdFromCompareExperimentsURL.ts, apps/opik-frontend/src/router.tsx, apps/opik-frontend/src/types/datasets.ts
=> [OPIK-37] [UX Improvement] Move experiments to separate page

build_and_run.sh
Exposed MySQL port from Minikube to localhost.
This is useful for local development purposes and to make easier debugging.
N/A
- Connected to MySQL within Minikube running locally and able to send queries and to inspect the schema.
N/A
=> NO-JIRA: Expose MySQL for local development

sdks/python/setup.py
1. Use envionment "VERSION" if it exists
2. Else, uses version.txt file contents
3. Else, uses 0.0.1
Resolves #166 
Tested all three scenarios
None
=> Use the project version.txt as fallback for SDK version

apps/opik-backend/config.yml, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/instrumentation/InstrumentAsyncUtils.java, apps/opik-backend/src/main/java/com/comet/opik/utils/JsonUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/ClientSupportUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/ConditionalGZipFilter.java, apps/opik-backend/src/test/resources/config-test.yml
Add compression to avoid errors like the one below:
```
[Client action]---------------------------------------------{
1 * Client response received on thread main
1 < 400
1 < content-length: 47
1 < content-type: application/json
1 < date: Thu, 12 Sep 2024 08:38:07 GMT
{"code":400,"message":"Unable to process JSON"}
}----------------------------------------------------------
```
Resolves #
=> OPIK-75: Add client side and server side compression

apps/opik-frontend/src/components/layout/EmptyLayout/EmptyLayout.tsx, apps/opik-frontend/src/components/layout/WorkspaceGuard/WorkspaceGuard.tsx, apps/opik-frontend/src/plugins/comet/GetStartedPage.tsx, apps/opik-frontend/src/router.tsx
- Change layout for the Get Started page
- Fix link area to be only clickable in the demo project card
- Add responsiveness in the card
- Redirect to a new tab in case user clicks into the demo project card
Resolves #
=> [OPIK-86] Change layout for get started page

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/FeedbackDefinitionResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TraceResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackDefinitionDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackDefinitionService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/ConditionalGZipFilter.java
Many parts of the service were lacking basic info logs. This first iteration added a few basic logs; next, we may add more debug logs and any remaining relevant info logs.
Resolves #
=> [NA] Add info logs

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsCell.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsDetails.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/ConfigurationTab/CompareConfigCell.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx, apps/opik-frontend/src/components/pages/DatasetItemsPage/AddEditDatasetItemDialog.tsx, apps/opik-frontend/src/components/shared/TraceDetailsPanel/BaseTraceDataTypeIcon.tsx
[OPIK-102] [UX] Support metadata when adding datasetItem from UI
[OPIK-93] [UX Improvements] Add tooltips to trace/span type icons
Resolves #
[OPIK-102]: https://comet-ml.atlassian.net/browse/OPIK-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OPIK-93]: https://comet-ml.atlassian.net/browse/OPIK-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OPIK-102] [UX] Support metadata when adding datasetItem from UI

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemService.java
=> [NA] Fix style issues

apps/opik-backend/src/main/java/com/comet/opik/api/Project.java, apps/opik-backend/src/main/java/com/comet/opik/api/TraceCountResponse.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/internal/UsageResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/internal/UsageResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Adds endpoint `GET /v1/internal/usage/workspace-trace-counts` to get traces count on previous day for all workspaces.
It will be used on EM side to update Stripe, blocking based on usage and billing details.
Resolves #CM-11314
Added integration test and checked with running Opik locally
=> [CM-11314] Opik endpoint for traces count

build_and_run.sh
Exposes the `opik-backend` service running on port 8080 on the same port of localhost.
This is useful to directly call the service for local development, testing and debugging purposes.
NO-JIRA
- Started the whole application with `build_and_run.sh` and then successfully run `curl` towards `localhost:8080` to retrieve an experiment by id.
N/A
=> NO-JIRA Expose backend port for local development

.github/workflows/sdk-e2e-tests.yaml, .gitignore, sdks/python/tests/e2e/test_experiment.py
=> add sdk e2e tests workflow

apps/opik-frontend/src/components/pages/CompareExperimentsPage/AddExperimentToCompareDialog.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsDetails.tsx, apps/opik-frontend/src/components/pages/TracesPage/AddToDataset/AddToDatasetDialog.tsx
=> [OPIK-124] [UX Improvements] Changes to Add to compare modal

deployment/docker-compose/README.md, deployment/docker-compose/docker-compose.override.yaml, deployment/docker-compose/docker-compose.yaml, deployment/docker-compose/nginx_default_local.conf
Services ports such as redis, clickhouse and other were being exported to the host unecessarily. This PR removes that
Noticed that when trying to run on my computer and I already had redis running on the host machine (port conflict)
Resolves #
=> removing exporting internal services ports by default

apps/opik-documentation/documentation/docs/tracing/integrations/langchain.md
fixes outdated references to `CometTracer` and replaces them with `OpikTracer`
Resolves #
updated langchain docs
=> Langchain Docs Typos

apps/opik-frontend/src/components/shared/AddEditFeedbackDefinitionDialog/FeedbackDefinitionDetails/CategoricalFeedbackDefinitionDetails.tsx, apps/opik-frontend/src/components/shared/AddEditFeedbackDefinitionDialog/FeedbackDefinitionDetails/NumericalFeedbackDefinitionDetails.tsx, apps/opik-frontend/src/components/shared/FeedbackScoresEditor/AddFeedbackScorePopover.tsx, apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceAnnotateViewer/AnnotateRow.tsx, apps/opik-frontend/src/components/ui/input.tsx, apps/opik-frontend/src/components/ui/textarea.tsx, apps/opik-frontend/src/lib/traces.ts
=> [OPIK-82] Dot character not allowed on feedback definition values

apps/opik-backend/src/main/java/com/comet/opik/api/Trace.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreMapper.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Added new `usage` field on `Trace`, which is calculated by summing the values of all the spans under the particular trace, per each usage key.
Due to summing, using `Long` type and `summap` function in ClickHouse instead of `Integer` and `summapwithoverflow`.
Some minor fixes in a few queries and also improved many Trace tests along the way.
OPIK-58
- Added and updated integration tests:
- Summing usual token values.
- Mixed with other random keys.
- Mixed with missing keys.
- Mixed with null keys.
- Spans with null values case.
- Tests for all Trace retrieval endpoints: get by ID and find endpoints.
- Existing tests already check the case of no spans under the trace, resulting in a null trace usage.
- https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/summap
- …
=> OPIK-58 Add trace usage

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimitInterceptor.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimitService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/redis/RedisRateLimitService.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/ratelimit/RateLimitE2ETest.java
During tests, we found a scenario where the limit expired, and the application tried to retrieve it, generating the following error:
```
ERR user_script:1: RateLimiter is not initialized script: 1378f96e73a4251ef63dadab589a062f8276a044, on @user_script:1.. channel: [id: 0x0e387790, L:/10.4.68.55:58598
```
OPIK-144
- We managed to reproduce the error by recreating it as explained above. 
- To replicate this scenario, a test was created by calling the method directly without previous limit initialization.
https://www.javadoc.io/doc/org.redisson/redisson/latest/org/redisson/api/RRateLimiterAsync.html
=> [OPIK-144] Fix condition when limit expires and application tries to retrieve to check available permits

tests_end_to_end/application_sanity/conftest.py, tests_end_to_end/application_sanity/sanity_config.yaml, tests_end_to_end/application_sanity/sanity_dataset.jsonl
* Made the decision to call the basic flows defined in the [initial Notion page](https://www.notion.so/cometml/Opik-open-source-Test-Automation-Initial-Plan-9854af5df2e4414c8b224d269fb959e5) "sanity tests" as they should cover all of our basic flows and not take too long to run. As such, the setup fixtures and test suite itself is going to live inside the "application_sanity" subfolder of test_end_to_end, to maybe differentiate these flows from more specific features tests we might add in the future
* For traces and spans we are currently creating 5 traces each via the low level Opik() client and via the @track() decorator, each containing 2 spans, all objects have different names, and they all contain tags, metadata, feedback scores to check all data integrity is kept in the UI when …
=> [OPIK-193] Fixtures to setup traces, spans, datasets, experiments via SDK for end to end automated tests

apps/opik-documentation/documentation/docs/evaluation/manage_datasets.md, sdks/python/src/opik/api_objects/dataset/dataset.py, sdks/python/src/opik/api_objects/dataset/utils.py, sdks/python/src/opik/api_objects/opik_client.py, sdks/python/tests/e2e/test_dataset.py, sdks/python/tests/unit/api_objects/dataset/test_deduplication.py
The SDK has been updated so that items are not duplicated if they already exist in the dataset. This assumes that only one user is updating a dataset, we can move the hash_sync function to be called before each insert if we want to resolve this edge case but would come at a small performance cost:
```
import opik
client = opik.Opik()
dataset = client.create_dataset("deduplicated_dataset")
item = {
"input": {"question": "What is the of capital of France?"},
"expected_output": {"output": "Paris"},
}
dataset.insert([item, item])
```
The documentation has been updated
=> [OPIK-38] Deduplicate items before inserting them in a dataset

apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemDAO.java
Address missing comments from the previous PR
OPIK-159
=> [OPIK-159] Address missing comments

sdks/python/src/opik/message_processing/streamer.py, sdks/python/src/opik/url_helpers.py
When logging a trace to a project, the message:
```
OPIK: Started logging traces to the "Default Project" project at https://www.comet.com/opik/jacques-comet/projects.
```
will be displayed.
This message is only displayed once, but if you start logging to a different project you will see this message again.
=> Add message with link to trace project

sdks/python/examples/evaluation_example.py, sdks/python/src/opik/api_objects/dataset/dataset.py, sdks/python/src/opik/evaluation/evaluator.py, sdks/python/src/opik/evaluation/tasks_scorer.py, sdks/python/tests/unit/evaluation/test_evaluate.py
Added a `nb_samples` option to evaluate function
=> Added nb_samples parameter in evaluate function

apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx, apps/opik-frontend/src/types/projects.ts
- Integrate new `last_updated_trace_at` field in the Projects table
Resolves #
=> [OPIK-137] Integrate new last_updated_trace_at in the Projects table

sdks/python/src/opik/decorator/base_track_decorator.py
This PR adds @track(flush=True) so that you don't have to do it manually after the function has been called.
Before:
```python
from opik import track, flush_tracker
@track()
def streaming_function(input):
messages = [{"role": "user", "content": input}]
response = framework.completion(
model="gpt-3.5-turbo",
messages=messages,
)
return response
streaming_function("Why?")
flush_tracker()
```
After:
```python
from opik import track
@track(flush=True)
def streaming_function(input):
messages = [{"role": "user", "content": input}]
response = framework.completion(
model="gpt-3.5-turbo",
messages=messages,
)
return response
streaming_function("Why?")
```
None, except for adding some convenience.
No tests added.
Docstring for flush added.
=> Moved flush to after_call

.github/workflows/sanity.yml, tests_end_to_end/application_sanity/conftest.py, tests_end_to_end/application_sanity/sanity_config.yaml, tests_end_to_end/application_sanity/test_sanity.py, tests_end_to_end/page_objects/ProjectsPage.py, tests_end_to_end/page_objects/TracesPage.py, tests_end_to_end/page_objects/TracesPageSpansMenu.py
Setup a class structure for each page in the project to be expanded upon in the future as we add more flows and checks. Will try and keep all interactions with the pages themselves isolated in the Page classes to keep tests compact and readable. 
Added tests to check creation of Traces and Spans via SDK, everything seems to work, will add the rest and re-test for any flakiness.
@ferc you can try and run these yourselves if you checkout the project branch, have python and Opik installed locally and do
```
cd tests/end_to_end
export PYTHONPATH='.'
pip install -r test_requirements.txt
pytest -s application_sanity/test_sanity.py --browser chromium --base-url http://localhost:5173 --setup-show --headed
```
Otherwise you can find a successful run on Actions here: …
=> OPIK-194 Sanity end-to-end tests - UI tests

apps/opik-backend/config.yml, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java, apps/opik-backend/src/test/resources/config-test.yml
Testing locally, we managed to reproduce the error, which was apparently due to some truncation of the statement. A temporary fix is to increase the query size limit. However, we will address this soon with the ClickHouse consultancy
#OPIK-160
Add tests to simulate error
=> [OPIK-160] Fix trace and span error during insertion due to input/output size

sdks/python/src/opik/api_objects/opik_client.py, sdks/python/src/opik/message_processing/streamer.py, sdks/python/src/opik/url_helpers.py
Updated the message that is displayed when logging a trace to support the following:
```
import opik
client = opik.Opik(project_name="test", workspace="jacques-comet")
trace = client.trace(name="test")
```
will display:
```OPIK: Started logging traces to the "Default Project" project at https://www.comet.com/opik/jacques-comet/projects.```
=> Updated trace url link

.github/workflows/sdk-e2e-tests.yaml, sdks/python/src/opik/integrations/openai/opik_tracker.py, sdks/python/tests/library_integration/openai/test_openai.py, sdks/python/tests/testlib/backend_emulator_message_processor.py, sdks/python/tests/testlib/models.py
This PR allows user to set project name for OpenAI client.
```python
client = OpenAI()
client = opik_tracker.track_openai(
openai_client=client,
project_name="opik184",
)
```
Resolves #
integration tests are added
=> OPIK-184 [SDK] Allow users to configure the project name in OpenAI integration

apps/opik-frontend/e2e/pages/DatasetsPage.ts, apps/opik-frontend/e2e/pages/FeedbackDefinitionsPage.ts, apps/opik-frontend/e2e/pages/TracesPage.ts, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsDetails.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx, apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsFiltersButton.tsx, apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx, apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx, apps/opik-frontend/src/components/pages/TracesPage/TracesPage.tsx, apps/opik-frontend/src/components/ui/button.tsx
[OPIK-234] [UX improvements] Unify bottom paddings
[OPIK-231] [UX improvements] Experiment title misaligned
[OPIK-236] [UX improvements] Project page title should be project name
[OPIK-241] [UX improvements] Remove disabled state on experiment filters
Resolves #
[OPIK-234]: https://comet-ml.atlassian.net/browse/OPIK-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OPIK-231]: https://comet-ml.atlassian.net/browse/OPIK-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OPIK-236]: https://comet-ml.atlassian.net/browse/OPIK-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OPIK-241]: https://comet-ml.atlassian.net/browse/OPIK-241?atlOrigin=eyJpIjoiNWRk …
=> [OPIK-234]   [UX improvements] Unify bottom paddings

apps/opik-frontend/src/components/layout/Breadcrumbs/Breadcrumbs.tsx, apps/opik-frontend/src/components/layout/TopBar/TopBar.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsDetails.tsx, apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemPanelContent.tsx, apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx, apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx, apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx, apps/opik-frontend/src/components/pages/FeedbackDefinitionsPage/FeedbackDefinitionsPage.tsx, apps/opik-frontend/src/components/pages/ProjectsPage/DeleteProjectDialog.tsx, apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx, apps/opik-frontend/src/components/pages/TracesPage/TracesPage.tsx, apps/opik-frontend/src/components/ui/breadcrumb.tsx, apps/opik-frontend/src/components/ui/dialog.tsx, apps/opik-frontend/src/components/ui/label.tsx, apps/opik-frontend/src/plugins/comet/UserMenu.tsx
=> Handle long names (without spaces) in breadcrumbs, page titles and popups

sdks/python/examples/demo_data_generator.py
- Replace `requests` library with `urllib` to avoid SSL issues in the lambda function
Resolves #
=> [OPIK-266] Replace requests library in the demo generator script

sdks/python/src/opik/integrations/langchain/opik_tracer.py, sdks/python/tests/library_integration/langchain/test_langchain.py
This PR allows user to set project name for LangChain callback.
end-2-end tests are added
=> OPIK-186 [SDK] Allow users to configure the project name in LangChain integration

apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.tsx
- Fix orphan spans crash when `parent_span_id` is not present in the list of spans of the trace (orphan spans = ignored spans in the sidebar)
Resolves #
=> [OPIK-238] Fix orphan spans error ignoring them

.github/CODEOWNERS
Extended ownership of some subfolders to other teams, so PRs are requested to them and only require their approval, so they can move faster.
N/A
Github reports `This CODEOWNERS file is valid.`
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> NO-JIRA: Refine CODEOWNERS

apps/opik-backend/src/main/java/com/comet/opik/api/validate/DatasetItemInputValidator.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
Allow null custom fields
OPIK-218
```
1 * Sending client request on thread main
1 > PUT http://localhost:64258/v1/private/datasets/items
1 > Accept: application/json
1 > Authorization: [redacted]
1 > Comet-Workspace: fcad5ab8-81dc-4afb-bea0-5e31a779de45
1 > Content-Type: application/json
{"dataset_name":"Dxy3ajznes","items":[{"id":"019295bf-eb3a-7039-8f70-081dcb7b1b2e","input":{"a5cfoWjH9m":"v6adRGluPX","haJhM7bxmU":"M2ZVpQcurR","DKgvnHVoMc":"VnEPhyQVME","TCD8si3J1w":"oGYB5aRNO0","V9k48d4K9I":"XL2yuu9nd0"},"expected_output":{"p8GpolcCVj":"zwFA5ruYEv","fBXysf5a2L":"rF2goFpFuF","ed8xBpjs7l":"xhbKDNcjqS","z6kkjaAEVt":"KA51rxsgSF","60WfjGubtj":"Iye6DHKe68"},"metadata":{"EdkEnQQNjr":"UHCElyCBQx","5xuTVl8udL":"jII7zJGDtM","7MH4KeamGd":"yeX242v2oO","HhR6jysGuf":"Y5nwVNpHfm","y0o0hHNq4L":"CSmkAGTX …
```
=> [OPIK-218] Allow null custom fields

sdks/python/src/opik/integrations/langchain/opik_encoder_extension.py
`to_json` is replaced with `model_dump` inside encoder function because it adds less data that we don't want to log. 
Resolves #
=> [NA] Langchain integration: replace to_json with model_dump

sdks/python/src/opik/configurator/configure.py, sdks/python/tests/unit/configurator/test_configure.py
We will print a warning message if user runs `configure()` and there is already cached Opik client instance.
=> OPIK-258 [SDK] show warning message when user runs configure()

apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000005_move_data_to_new_dataset_item_data_field.sql
Migration following previous PR: https://github.com/comet-ml/opik/pull/369
OPIK-218
- Manually tested
=> [OPIK-218] Data migration

apps/opik-frontend/src/hooks/useCodemirrorTheme.tsx
Apply "0.875rem" (14px) font size for all CodeMirror components
Resolves #
=> [NA] Fix font size for code blocks

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimitInterceptor.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/redis/RedisRateLimitService.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/ratelimit/RateLimitE2ETest.java
```
org.redisson.client.RedisException: ERR user_script:1: RateLimiter is not initialized script: 1378f96e73a4251ef63dad, on @user_script:1.. channel: [id: 0x534ebb1e, L:/10.xx.xx.77:56910 - R:redis-cache.com./10.xx.xx.51:6379] command: (EVAL), params: [local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'interval');local type = redis.call('hget', KEYS[1], 'type');assert(rate ~= false and interval ~= false and type ~= false, 'RateLimiter is not initialized')local valueName = KEYS[2];local permitsName = KEYS[4];if type == '1' then valueName = KEYS[3];permitsName = KEYS[5];end;local currentValue = redis.call('get', valueName); if currentValue == false then redis.call('set', valueName, rate); return rate; else local expiredValues = …
```
=> [NA] Fix rate limit error

apps/opik-documentation/documentation/docs/cookbook/litellm.md
Fixing a small typo to the LiteLLM md
Small typo in docs
Resolves #
=> Fix typo in docs

.github/CODEOWNERS
Product team should be able to review and approve all `*.md` files without Opik devs involvement.
This is case sensitive, but I checked that the extension of all existing files in the repo are currently in lower case.
N/A
Github reports:
> This CODEOWNERS file is valid.
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> NO-JIRA: Add product as md files owners

apps/opik-documentation/documentation/docs/tracing/sdk_configuration.mdx, apps/opik-documentation/documentation/sidebars.ts, sdks/python/src/opik/config.py
1. Added documentation page for configuring the SDK using environment variables or configuration file
2. Updated the SDK to support a `OPIK_CONFIG_PATH` environment variable
=> Added config documentation

apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000003_add_last_created_experiment_at_to_datasets_table.sql
Migration to add field last created experiment at which will allow us to filter by datasets with experiments and sort by it.
OPIK-294
=> [OPIK-294] Add last created experiment at to dataset table

deployment/docker-compose/docker-compose.yaml
When running docker-compose locally, all containers have the default restart policy (no restart) whereas Redis is set to always. 
This is inconsistent and also annoying, as Redis automatically starts on laptop start-up for local development.
Aligned with the rest of containers and verified that no other occurrences happen in the repository.
N/A
Run docker-compose locally and re-started docker in my local laptop:
- Prior to the fix, Redis start ups automatically.
- After the fix, Redis doesn't start up automatically. 
- https://docs.docker.com/engine/containers/start-containers-automatically/
=> NO-JIRA: Redis docker-compose no restart

sdks/python/src/opik/evaluation/models/litellm_chat_model.py
This PR contains:
- print real key name of skipped unsupported LLM params
- handle passed param/dict to avoid changing the original param value
=> NA: Fixing the side effects of the function and printing the correct error message

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/AppMetadataService.java
In #500, the get backend version endpoint was introduced. However, the configuration were not injected properly resulting in a constantly empty response.
OPIK-329
Tested locally.
Before this change:
```sh
❯ curl http://localhost:5173/api/is-alive/ver
{}
```
After this change:
```sh
❯ curl http://localhost:5173/api/is-alive/ver
{"version":"my_test_version"}
```
=> [OPIK-329] fix backend version endpoint

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/http/CorsFactory.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/http/cors/CorsDisabledE2ETest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/http/cors/CorsEnabledE2ETest.java
Fix CORS response headers for requests containing the `comet-workspace` request header.
OPIK-136
Added an E2E test that covers and tested locally.
Before this change:
```sh
❯ curl 'http://localhost:5173/api/v1/private/projects' \
-X 'OPTIONS' \
-H 'access-control-request-headers: comet-workspace' \
-H 'access-control-request-method: GET' \
-H 'origin: http://localhost:5173' \
-i
HTTP/1.1 200 OK
Server: nginx/1.27.2
Date: Thu, 31 Oct 2024 07:20:57 GMT
Content-Length: 0
Connection: keep-alive
Vary: Origin
```
After this change:
```sh
❯ curl 'http://localhost:5173/api/v1/private/projects' \
-X 'OPTIONS' \
-H 'access-control-request-headers: comet-workspace' \
-H 'access-control-request-method: GET' \
-H 'origin: http://localhost:5173' \
-i
HTTP/1.1 200 OK
Server: nginx/1.27.2
Date: Thu, 31 …
```
=> [OPIK-136] fix cors request header comet workspace

deployment/helm_chart/opik/templates/configmap-frontend-nginx.yaml
- Current `50M` is not enough if we batch + upload images for each item (traces/spans/datasets)
Resolves #
=> Increase the client_max_body_size in nginx for better support for images in the payload

apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx, apps/opik-frontend/src/types/datasets.ts
- Add dataset item count column in the dataset table
- Remove experiment count column in the dataset table
Resolves #
=> [OPIK-352] Display dataset item count

.github/workflows/documentation_cookbook_tests.yml, .github/workflows/lib-langchain-tests.yml, .github/workflows/lib-llama-index-tests.yml, .github/workflows/lib-openai-tests.yml, .github/workflows/python_sdk_linter.yml, .github/workflows/python_sdk_unit_tests.yml, .github/workflows/sanity.yml, .github/workflows/test_installer.yml, .github/workflows/update_helm_readme.yaml, deployment/helm_chart/opik/README.md, deployment/helm_chart/opik/templates/configmap-frontend-nginx.yaml, deployment/helm_chart/opik/values.yaml
- Added an option to add nginx configuration settings for Opik FE (Values.component.frontend.additionalNginxSettings)
- update workflows to use the latest version of checkout action
Resolves #
=> add additionalNginxSettings for frontend configuration

apps/opik-frontend/src/components/pages/PromptPage/PromptTab/CommitHistory.tsx, apps/opik-frontend/src/components/pages/PromptPage/PromptTab/CommitsTab.tsx, apps/opik-frontend/src/components/pages/PromptPage/PromptTab/PromptTab.tsx, apps/opik-frontend/src/components/pages/PromptPage/PromptTab/UseThisPromptDialog.tsx, apps/opik-frontend/src/components/pages/PromptsPage/PromptsPage.tsx, apps/opik-frontend/src/types/prompts.ts
* added code snippets for prompt usages;
* displaying commits instead of their ids;
* added refetch interval;
Resolves #
=> [OPIK-319]: prompt library improvements;

apps/opik-frontend/src/api/projects/useProjectsList.ts, apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx, apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx, apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx, apps/opik-frontend/src/components/pages/FeedbackDefinitionsPage/FeedbackDefinitionsPage.tsx, apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx, apps/opik-frontend/src/components/pages/PromptsPage/PromptsPage.tsx, apps/opik-frontend/src/components/shared/DataTable/DataTable.tsx, apps/opik-frontend/src/components/shared/DataTableHeaders/TypeHeader.tsx, apps/opik-frontend/src/lib/sorting.ts, apps/opik-frontend/src/lib/table.ts, apps/opik-frontend/src/types/shared.ts, apps/opik-frontend/src/types/sorting.ts
=> [OPIK-372] [FE] Add sorting for projects table

apps/opik-backend/src/main/java/com/comet/opik/domain/ImageUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ImageTruncationArgProvider.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Image truncation was introduced in #578. It had several issues:
1. Wasn't working well for payloads with more than one image message
2. Wasn't working at all for images lacking the `data:image/...` prefix
3. Had a couple of tests that needed to be improved, see https://github.com/comet-ml/opik/pull/578#discussion_r1832699886
- OPIK-400
- OPIK-393
Improved E2E tests to cover all cases
=> [OPIK-400] improve image truncation

apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentSearchCriteria.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
Add a flag `dataset_deleted` to allow filtering by experiments linked to deleted datasets.
OPIK-295
=> [OPIK-295] Get experiments linked to deleted datasets

apps/opik-frontend/src/components/pages/PromptPage/PromptTab/CommitHistory.tsx, apps/opik-frontend/src/components/pages/PromptPage/PromptTab/PromptTab.tsx
1. Updated the background colors for a prompt code snippet and commits
2. Made an active commit id bold 
3. Now, a code snippet doesn't take all free space
Resolves #
=> [OPIK-394]: adjust the UI for Prompts to Figma;

apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx
- Revert truncate the base64 images in the traces/spans table until the BE has a fix for the LLM tab table (it returns less elements than requested)
Resolves #
=> Revert truncate base64 images in the traces/spans table

apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx
- Re-enable the truncation for base64 images in traces/spans table
Resolves #
=> Enable truncate base64 images in traces/spans table

apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx, apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx
Increase the default amount of items per page in the Traces and Experiment items pages to 100
Resolves #
=> [OPIK-298] [UX improvements] Increase default amount of items per page

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000007_change_spans_usage_value_to_nullable.sql, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
Null value in payload leads to 500 error
Resolves #https://comet-ml.atlassian.net/browse/OPIK-203
Tested with running Opik locally. Reproduced without the fix, and then checked that fix resolves this issue.
Added integration test.
=> [OPIK-203] Filter our spans.usage with null values

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortableFields.java, apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortingFactory.java, apps/opik-backend/src/main/java/com/comet/opik/api/sorting/SortingFactoryProjects.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java, apps/opik-backend/src/main/java/com/comet/opik/utils/PaginationUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/utils/PaginationUtilsTest.java
We want to achieve sorting by `last_updated_trace_at`. This field has a dynamically computed value and is not stored in MySQL. For that purpose we need to manually sort and paginate.
**Note:** For the time being we decided to not support sorting by multiple fields as that would introduce some messy logic.
OPIK-396
Added an E2E test that covers the new sorting logic. Pagination logic is covered with unit tests.
=> [OPIK-396] dynamically sort by last_updated_trace_at

sdks/python/src/opik/api_objects/opik_client.py, sdks/python/src/opik/url_helpers.py
* Now the creation of traces shows a link to a specific project
Resolves #
=> [OPIK-390]: [SDK] add a project name to creation of traces;

sdks/python/src/opik/evaluation/evaluator.py, sdks/python/src/opik/evaluation/scores_logger.py
* Now, the scores during `evaluate` work properly. They handle the project_name correctly
* I wanted to write some tests but for the time being, there is no way to get the project info by a name. So, it's best to do it after the BE is ready
Resolves #553
=> [OPIK-402]: handle project name and score definitions for evaluate();

apps/opik-backend/src/main/java/com/comet/opik/api/ProjectIdLastUpdated.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java
The FE uses the `last_updated_at` as a fallback to when `last_trace_updated_at` is not present. When sorting, this must be taken into account.
OPIK-422
Added an E2E test that covers this case.
=> [OPIK-422] fix projects with no traces sorting

apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/InputOutputTab.tsx
- [OPIK-405] Detect base64 images across the input object (not only with OpenAI structure) and display them in the Images section
Resolves #
[OPIK-405]: https://comet-ml.atlassian.net/browse/OPIK-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OPIK-405] Detect base64 images across the input object

apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/InputOutputTab.tsx
- Add missing GIF format
Resolves #
=> [OPIK-405] Add missing format for GIF images

apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/InputOutputTab.tsx
- The BE could avoid sending the `input` if it's empty (`undefined` instead of `{}`)
Resolves #
=> [OPIK-405] Fix case where data.input could be undefined

apps/opik-frontend/src/api/datasets/useDatasetItemByName.ts, apps/opik-frontend/src/api/projects/useProjectByName.ts
* using a new endpoint that was provided by the BE;
Resolves #
=> [NA]: [FE] replace getProjectByName function endpoint;

sdks/python/src/opik/evaluation/evaluator.py, sdks/python/src/opik/evaluation/tasks_scorer.py, sdks/python/tests/e2e/test_experiment.py
this code snippet:
```
evaluation = evaluate(
experiment_name="First eval",
dataset=dataset,
task=evaluation_task,
experiment_config={
"model": MODEL
},
project_name="SOME_NEW_PROJECT"
)
```
the experiment simply has no feedback scores
Resolves #
=> [OPIK-51]: make scoring_metrics optional

deployment/helm_chart/opik/Chart.lock, deployment/helm_chart/opik/Chart.yaml, deployment/helm_chart/opik/README.md, deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml, deployment/helm_chart/opik/values.yaml
- added bitnami-common as a dependency to opik chart to support simpler value configurations
- add variable for clickhouse backup bucket 
- add toleration and nodeSelector for clickhouse backup job
- set default successfulJobsHistoryLimit=1 for clickhouse backup cronjob
Resolves #
Tested on Dev
=> [DEV-2440] opik chart improvements

apps/opik-backend/src/main/java/com/comet/opik/api/FeedbackScoreNames.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/FeedbackScoreResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/ExperimentResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/ProjectResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/internal/UsageResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FeedbackDefinitionResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FeedbackScoreResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/HealthCheckIntegrationTest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/AuthModuleCache2E2Test.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/AuthModuleNoAuthIntegrationTest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/aws/rds/MysqlRdsIamE2eTest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/bi/OpikGuiceyLifecycleEventListenerTest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/health/IsAliveE2ETest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/http/cors/CorsDisabledE2ETest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/http/cors/CorsEnabledE2ETest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/ratelimit/RateLimitE2ETest.java
- Add endpoint to retrieve all feedback score names
- Fix parallel container starting
OPIK-418
- Filter by `project_id`
- Filter by `with_experiments_only`
- Both filters
- No filters
=> [OPIK-418] Add endpoint to return all feedback score names

apps/opik-backend/src/main/java/com/comet/opik/api/DatasetItemSearchCriteria.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/podam/manufacturer/JsonNodeTypeManufacturer.java
Similarly to traces and spans, we would like to truncate base64 encoded images in dataset items as well.
OPIK-417
Added a couple of E2E tests to cover the new flows.
=> [OPIK-417] Truncate base64 images for dataset items

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java
In #651 truncation was added for dataset items but only truncated the `data` field.
This PR covers truncation for the `experimentItems` field as well.
OPIK-433
Extended the existing E2E test to cover the new behavior.
=> [OPIK-433] truncate base64 images for `datasetItem.experimentItems`

sdks/python/src/opik/decorator/arguments_helpers.py, sdks/python/src/opik/decorator/base_track_decorator.py, sdks/python/src/opik/decorator/tracker.py, sdks/python/src/opik/integrations/anthropic/messages_create_decorator.py, sdks/python/src/opik/integrations/bedrock/converse_decorator.py, sdks/python/src/opik/integrations/openai/openai_decorator.py, sdks/python/tests/unit/decorator/test_tracker_outputs.py
This PR allows to pass `ignore` parameter to the decorator so that corresponding decorated function arguments were not logged as span/trace inputs.
```python
@track(ignore=["a", "c", "e"])
def f(a, b, c=3, d=4, e=5):
return {"some-key": "the-output-value"}
```
Base track decorator code was refactored, now it's easier to extend.
https://github.com/comet-ml/opik/issues/468
Unit tests are added.
Docstrings are added to track decorator
=> [OPIK-285] allow users to specify function parameters to not log when using the track decorator

.github/workflows/lib-llama-index-tests.yml, sdks/python/tests/library_integration/llama_index/test_llama_index.py
Something is broken in llama-index when you try to install it for python 3.8, so you can't even import it due to some pydantic errors.
So I just bumped the minimal tested python version to 3.9
=> [OPIK-445] LLama-index tests fix

deployment/docker-compose/docker-compose.yaml
The Opik backend and frontend containers were hardcoded to be built on `linux/amd64`.
Removed that, so it builds in the native architecture of the user, such as arm64 etc.
N/A
I run `docker compose -f docker-compose.yaml -f docker-compose.override.yaml up -d --build` prior and after the change in my local Mac with arm64 architecture.
Prior to the change, the containers where built as amd64 and run in emulated mode.
After the change, they were built as arm64 and run natively. 
- https://docs.docker.com/reference/compose-file/build/#platforms
=> NO-JIRA: Remove amd64 architecture from docker compose

scripts/README.md, scripts/generate_openapi.sh, sdks/python/code_generation/fern/generators.yml
New script which automates:
1. Generation of the latest `openapi.yaml` from the current backend.
2. Updates the `openapi.yaml` used for the Python SDK Fern generation.
3. Generates the Python Fern code.
4. Updates the latest Python Fern code.
5. Formats the Python code.
This way, the previous manual process can all be done just by running:
```bash
/scripts/generate_openapi.sh
```
N/A
- Run with the current Python SDK `openapi.yaml` and generates no changes.
- I'll send a follow-up PR with the latest `openapi.yaml` from the backend, as there are changes in the endpoints.
- https://buildwithfern.com/learn/sdks/introduction/overview
=> NO-JIRA: Add generate Open API script

apps/opik-frontend/src/components/shared/DataTableCells/TextCell.tsx
=> [OPIK-461] Text columns should wrap content in dataset table

sdks/python/src/opik/api_objects/span.py, sdks/python/src/opik/api_objects/trace.py, sdks/python/src/opik/decorator/base_track_decorator.py, sdks/python/tests/unit/decorator/test_tracker_outputs.py
Updated the `update_current_span` and `update_current_trace` methods to not override `input` and `output` values but instead merge them with existing values.
Resolves #708 
Added unit test
No docs updated
=> update_current_span now supports updating the output

apps/opik-documentation/documentation/docs/tracing/integrations/openai.md, sdks/python/examples/openai_integration_example.py, sdks/python/src/opik/integrations/openai/openai_decorator.py, sdks/python/src/opik/integrations/openai/opik_tracker.py, sdks/python/src/opik/integrations/openai/stream_wrappers.py, sdks/python/tests/library_integration/openai/test_openai.py
Updated the OpenAI integration to track `openai_client.beta.chat.completions.parse` calls:
```
from opik.integrations.openai import opik_tracker
from openai import OpenAI
from pydantic import BaseModel
client = opik_tracker.track_openai(OpenAI())
class CalendarEvent(BaseModel):
name: str
date: str
participants: list[str]
completion = client.beta.chat.completions.parse(
model="gpt-4o-2024-08-06",
messages=[
{"role": "system", "content": "Extract the event information."},
{"role": "user", "content": "Alice and Bob are going to a science fair on Friday."},
],
response_format=CalendarEvent,
)
print(completion)
```
Resolves #706 
Added a new end to end test and updated the `examples/openai_integration_example.py` method.
OpenAI integration page was updated
=> Implement tracking for beta.chat.completions.parse method

sdks/python/setup.py
LiteLLM minimal version is bumped because they fixed a few bugs that were impacting our metrics.
Levenshtein version relaxed to "less than next major version".
=> [NA] Update setup.py dependencies

apps/opik-backend/src/main/java/com/comet/opik/api/Trace.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/cost/SpanCostCalculator.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Computes trace cost based on token usage
Resolves #OPIK-415
https://www.notion.so/cometml/Opik-Span-Cost-tracking-13c7124010a380a7ad36ced128a26dc7
=> [OPIK-415] Compute traces cost based on token usage

apps/opik-backend/src/main/java/com/comet/opik/api/DataPoint.java, apps/opik-backend/src/main/java/com/comet/opik/api/metrics/ProjectMetricRequest.java, apps/opik-backend/src/main/java/com/comet/opik/api/metrics/ProjectMetricResponse.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
This PR extends the MVP implemented in #678 to have the additional following functionality:
1. Support all interval types
2. ~Support null range, i.e. "all time"~ - product requirements changed, these changes are reverted
3. `null` back-fill instead of `0`
4. Feedback scores metric implementation
This PR doesn't include the `usage` metric which will be introduced in a later PR
Partially resolves OPIK-395
Added several E2E tests to cover the newly added scenarios.
=> [OPIK-395] Project Metrics - all but `usage`

apps/opik-frontend/src/components/shared/ResizableSidePanel/ResizableSidePanel.tsx
Added a prop to ResizableSidePanel to be able to be closed on clicking outside;
Resolves #
=> [OPIK-288]: make sidebars close after clicking outside;

apps/opik-frontend/src/api/api.ts, apps/opik-frontend/src/api/datasets/useCompareExperimentsList.ts, apps/opik-frontend/src/api/traces/useSpanUpdateMutation.ts, apps/opik-frontend/src/api/traces/useSpansList.ts, apps/opik-frontend/src/api/traces/useTraceBatchDeleteMutation.ts, apps/opik-frontend/src/api/traces/useTraceById.ts, apps/opik-frontend/src/api/traces/useTraceDeleteMutation.ts, apps/opik-frontend/src/api/traces/useTraceFeedbackScoreDeleteMutation.ts, apps/opik-frontend/src/api/traces/useTraceFeedbackScoreSetMutation.ts, apps/opik-frontend/src/api/traces/useTraceUpdateMutation.ts, apps/opik-frontend/src/api/traces/useTracesList.ts, apps/opik-frontend/src/components/pages/TracesPage/TracesActionsPanel.tsx, apps/opik-frontend/src/lib/feedback-scores.tsx
Add the optimistic update for all cases when the user sets/ edits /deletes the feedback score
Resolves #
=> [OPIK-448] [FE] UI on editing feedback score is slow

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/redis/RedissonLockService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/redis/RedissonLockServiceIntegrationTest.java
- Fixing flaky test
- Adjusting logs 
OPIK-474
=> [OPIK-474] Fix Flaky test

apps/opik-backend/src/main/java/com/comet/opik/api/metrics/MetricType.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java
This adds the cost metric to the project metrics.
OPIK-470
Added E2E tests that cover the new flow.
=> [OPIK-470] Project Metrics - add cost

apps/opik-frontend/src/api/traces/useSpansStatistic.ts, apps/opik-frontend/src/api/traces/useTraceFeedbackScoreDeleteMutation.ts, apps/opik-frontend/src/api/traces/useTraceFeedbackScoreSetMutation.ts, apps/opik-frontend/src/api/traces/useTracesStatistic.ts, apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx, apps/opik-frontend/src/components/shared/DataTable/DataTable.tsx, apps/opik-frontend/src/components/shared/DataTable/DataTableColumnResizer.tsx, apps/opik-frontend/src/components/shared/DataTableCells/ListCell.tsx, apps/opik-frontend/src/components/shared/DataTableHeaders/FeedbackScoreHeader.tsx, apps/opik-frontend/src/components/shared/DataTableHeaders/HeaderStatistic.tsx, apps/opik-frontend/src/components/shared/DataTableHeaders/HeaderWrapper.tsx, apps/opik-frontend/src/components/shared/DataTableHeaders/TypeHeader.tsx, apps/opik-frontend/src/components/ui/table.tsx, apps/opik-frontend/src/hooks/useTracesOrSpansStatistic.ts, apps/opik-frontend/src/lib/table.ts, apps/opik-frontend/src/types/shared.ts
=> [OPIK-398] Project statistics - FE implementation

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Fix for error:
```
Cannot invoke "com.comet.opik.api.ProjectStats.stats()" because "projectStats" is null
```
OPIK-487
=> [OPIK-487] Fix null pointer

apps/opik-frontend/src/api/projects/useProjectMetric.ts, apps/opik-frontend/src/components/pages/ExperimentsPage/charts/ExperimentChartContainer.tsx, apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricChart/MetricChart.tsx, apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricsTab.tsx, apps/opik-frontend/src/components/shared/ChartTooltipContent/ChartTooltipContent.tsx, apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceDataViewer/TraceDataViewer.tsx, apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/TraceTreeViewer.module.scss, apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/treeRenderers.tsx, apps/opik-frontend/src/hooks/charts/useChartTickDefaultConfig.ts, apps/opik-frontend/src/lib/charts.ts
* add a cost chart
* worked on the tick width and formatting behavior
Resolves #
* also fixes the issues for the cases where the cost didn't fit:
=> [OPIK-437]: add fe cost chart

scripts/generate_openapi.sh
When executing the `generate_openapi.sh` script, if fern wasn't installed, the script finished successfully which was confusing. 
This PR adds validation that fern is installed when generating OpenAPI client code.
Tested with and without `fern` installed. The script works as expected.
=> [NA] Validate fern installed

.github/workflows/documentation_cookbook_tests.yml, sdks/python/src/opik/api_objects/opik_client.py, sdks/python/src/opik/rest_client_configurator/retry_decorators.py, sdks/python/tests/e2e/test_backend_check.py
Adds `auth_check()` method to Opik. The method returns None if everything if the configured workspace is accessible for the configured API key, and raises an `ApiError` with the error message and status code from the backend if there is a problem with access.
Added e2e tests.
Also added a workaround for Fern bug with ignored httpx timeouts.
=> [OPIK-515] implement opik client auth_check method

sdks/python/src/opik/evaluation/metrics/llm_judges/hallucination/template.py
```
from opik.evaluation.metrics import Hallucination
metric = Hallucination(model="ollama/qwen2.5:3b")
score = metric.score(
input="What is the capital of France?",
output="Paris",
context=["France is a country in Europe."]
)
print(score)
```
The output format of the LLM may not in JSON format.
```
opik/evaluation/metrics/llm_judges/hallucination/metric.py", line 133, in _parse_model_output
dict_content = json.loads(content)
^^^^^^^^^^^^^^^^^^^
raise exceptions.MetricComputationError(
opik.evaluation.metrics.exceptions.MetricComputationError: Failed hallucination detection
```
Add "Output format must be JSON format only." into the prompt template
Re-run the above code. The output result would be like this
```
{
"score": 1.0,
"reason": [
"The CONTEXT provided only basic information about …
```
=> [SDK] Control output format

sdks/python/src/opik/api_objects/experiment/__init__.py, sdks/python/src/opik/api_objects/experiment/helpers.py, sdks/python/src/opik/api_objects/opik_client.py, sdks/python/tests/unit/api_objects/experiment/test_helpers.py
Fixes the bug when `prompt` parameter was ignored if `experiment_config` dictionary was not passed (or invalid non-dict value was passed)
Experiment metadata processing logic was extracted to a separate module and covered with unit tests.
=> [Opik-413] fix missing prompt data

apps/opik-backend/src/main/java/com/comet/opik/api/filter/Operator.java, apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
Add NOT_EQUAL operator for filtering
Resolves: #551
Added corresponding integration tests
=> [OPIK-486] Add NOT_EQUAL operator for filtering

.github/workflows/documentation_cookbook_tests.yml, sdks/python/src/opik/api_objects/dataset/dataset.py, sdks/python/src/opik/rest_client_configurator/retry_decorators.py
Since fern API returned a stream object when reading dataset items, retries haven't really worked with that (we had only retries on returning a streaming object). If there was a ReadTimeout error during the chunk read - an exception was not caught and the code failed after first attempt.
This PR adds retries to the whole `get-items` operation in `Dataset` api class.
=> [OPIK-555] Add retries for get dataset items operation

deployment/helm_chart/opik/templates/clickhouse-backup-cronjob.yaml, deployment/helm_chart/opik/templates/clickhouseinstallation.yaml, deployment/helm_chart/opik/templates/deployment.yaml
=> DT-326: add optional commonLabels to opik pods

apps/opik-backend/pom.xml, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ChatCompletionsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TextStreamer.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/ChatCompletionsClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ChatCompletionsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Created the skeleton of the chat completion proxy endpoint, with same signature as the Open API one.
Integrated langchain4j and re-used request and response models.
Supported both stream and un-stream mode in the get chat completion endpoint.
Naive implementation that only returns a 501 not implemented status code, with random data.
Left a reference implementation of server sent events (mime type: text/event-stream) based on a chunked output, that can be reused in the future for any similar endpoint. 
Added a proper Open API spec, but not updated nor generated the models yet. Will go in a follow-up PR once this contract is fully agreed.
- https://comet-ml.atlassian.net/browse/OPIK-545
- Added naive integration tests covering the streaming and unstreaming responses.
- …
=> OPIK-545: Add chat completions resource

apps/opik-backend/src/main/java/com/comet/opik/api/events/TracesCreated.java, apps/opik-backend/src/main/java/com/comet/opik/api/events/TracesUpdated.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/ProjectEventListener.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000006_add_projects_last_updated_trace_at.sql, apps/opik-backend/src/test/java/com/comet/opik/TestComparators.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/domain/TraceServiceImplTest.java
In order to avoid in-memory sorting, we wanted this column to be added to `projects` table and updated whenever a trace is created or updated.
OPIK-419
Added tests that cover the flows.
=> [OPIK-419] add last updated trace at to projects

apps/opik-documentation/documentation/docs/cookbook/langgraph.ipynb, apps/opik-documentation/documentation/docs/tracing/integrations/langgraph.md, sdks/python/src/opik/integrations/langchain/opik_tracer.py
Add support for tracking LangGraph Graph definition in Opik
=> LangGraph Graph Definition tracking

.github/workflows/end2end_suites.yml, tests_end_to_end/page_objects/ProjectsPage.py
After addition of new homepage, URL for projects paged changed slightly to include the workspace name, causing projects and traces tests to fail. Added fix.
Also, modified the workflow file slightly to automatically run all the tests on every PR that modifies the tests (optional non-blocking check)
=> NO-JIRA failing tests fixes

sdks/python/src/opik/jsonable_encoder.py
`pydantic.BaseModel` instances are now converted to dictionaries when serialized before sending.
Tested manually.
=> [NA] Add pydantic.BaseModel support to serializer

apps/opik-backend/src/main/java/com/comet/opik/api/ErrorInfo.java, apps/opik-backend/src/main/java/com/comet/opik/api/Span.java, apps/opik-backend/src/main/java/com/comet/opik/api/SpanUpdate.java, apps/opik-backend/src/main/java/com/comet/opik/api/Trace.java, apps/opik-backend/src/main/java/com/comet/opik/api/TraceUpdate.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000008_add_error_info_to_spans_and_traces.sql, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Add error_info to spans and traces
Covered by existing tests
=> [OPIK-529] Add error_info to spans and traces

apps/opik-backend/src/main/java/com/comet/opik/api/Identifier.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
Get experiment by name endpoint
=> [OPIK-582] Get experiment by name endpoint

apps/opik-frontend/src/components/pages/PromptPage/PromptTab/EditPromptDialog.tsx
=> [OPIK-578] [FR]: Prompt diff

apps/opik-backend/src/main/java/com/comet/opik/api/ProviderApiKeyUpdate.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/LlmProviderApiKeyResource.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/LlmProviderApiKeyResourceTest.java, apps/opik-documentation/documentation/rest_api/opik.yaml, sdks/code_generation/fern/openapi/openapi.yaml, sdks/python/src/opik/rest_api/llm_provider_key/client.py, sdks/python/src/opik/rest_api/types/span.py, sdks/python/src/opik/rest_api/types/span_public.py, sdks/python/src/opik/rest_api/types/trace.py, sdks/python/src/opik/rest_api/types/trace_public.py, sdks/typescript/src/opik/rest_api/api/resources/llmProviderKey/client/Client.d.ts, sdks/typescript/src/opik/rest_api/api/resources/llmProviderKey/client/Client.js, sdks/typescript/src/opik/rest_api/api/types/Span.d.ts, sdks/typescript/src/opik/rest_api/api/types/SpanPublic.d.ts, sdks/typescript/src/opik/rest_api/api/types/Trace.d.ts, sdks/typescript/src/opik/rest_api/api/types/TracePublic.d.ts, sdks/typescript/src/opik/rest_api/serialization/types/Span.d.ts, sdks/typescript/src/opik/rest_api/serialization/types/Span.js, sdks/typescript/src/opik/rest_api/serialization/types/SpanPublic.d.ts, sdks/typescript/src/opik/rest_api/serialization/types/SpanPublic.js, sdks/typescript/src/opik/rest_api/serialization/types/Trace.d.ts, sdks/typescript/src/opik/rest_api/serialization/types/Trace.js, sdks/typescript/src/opik/rest_api/serialization/types/TracePublic.d.ts, sdks/typescript/src/opik/rest_api/serialization/types/TracePublic.js
Delete LLM Provider Api key endpoint documentation and SDK code
=> [OPIK-627] Delete LLM Provider Api key endpoint documentation and SDK code

deployment/docker-compose/nginx_default_local.conf
Fix issues with `413 Request Entity Too Large` errors due to missing configuration in docker compose deployments
Should resolve #834
=> Updated max body size for docker deployments

apps/opik-frontend/src/api/playground/useCompletionProxyStreaming.ts, apps/opik-frontend/src/api/playground/useCreateOutputTraceAndSpan.ts, apps/opik-frontend/src/components/pages/ConfigurationPage/AIProvidersTab/AIProvidersTab.tsx, apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutput.tsx, apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputs.tsx, apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPage.tsx, apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompt/PlaygroundPrompt.tsx, apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompt/PromptModelSelect/PromptModelSelect.tsx, apps/opik-frontend/src/lib/provider.ts, apps/opik-frontend/src/types/playground.ts
* Now playground is cached in a local storage.
* The cases when a user has no valid model anymore are also handled;
* Outputs now are controlled by prompts;
* Add a reset button
Resolves #
=> [OPIK-619]: playground fe cache

sdks/python/setup.py, sdks/python/src/opik/api_objects/helpers.py
Moved from `uuid7.uuid7()` to `uuid6.uuid7()` which follows `RFC9562`
=> [NA] Update uuid7 generation package

apps/opik-backend/config.yml, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/LlmProviderApiKeyResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/LlmProviderApiKeyDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/LlmProviderApiKeyService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/PromptVersionDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/cost/ModelPrice.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ChatCompletionsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/podam/manufacturer/ProviderApiKeyManufacturer.java, apps/opik-backend/src/test/resources/config-test.yml
In Opik Backend, there was no default redis url for local development. As this is validated to not to be null on service start up, the service failed to start locally. Fixed in config.yml
This is overwritten by the value coming from the test container in tests. However, added a value in test-config.yml in order to follow the existing convention.
Moved test in ChatCompletionsResourceTest under Create, which is the right place.
Applied Spotless formatting, which fixed multiple files.
NO-JIRA
- Started the service locally before and after the fix.
- https://redisson.org/docs/configuration/
=> NO-JIRA: Fix redis URL configuration

sdks/python/src/opik/config.py, sdks/python/src/opik/decorator/base_track_decorator.py, sdks/python/tests/unit/decorator/test_track_disabled.py, sdks/python/tests/unit/decorator/test_track_disabled_mode.py
If you set `OPIK_TRACK_DISABLE` configuration to `True` (via the environment variable or config file) - `@track` decorator will stop logging data.
It will also disable data logging for any other `track_LIBRARY_NAME` integration: openai, anthropic, bedrock, aisuite, guardrails.
**Important!!!:** the rest of the API works as usually and is not related to a new configuration.
In order to minimize the impact on the existing user scripts that just need to stop logging data, spans and traces objects are still created under the hood, so `get_current_[span, trace]_data` and `update_current_[span, trace]` continue working as they worked before, nothing will start suddenly returning None or raising exceptions in places where it was working before the tracking was disabled. But no data will be sent …
=> [OPIK-673] implement OPIK_TRACK_DISABLE configuration

apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab.tsx
- Due a recent BE API contract the feedback scores aggregations in the traces/spans table are broken, this adjusts the FE with the new BE API contract
https://github.com/comet-ml/opik/pull/894/files#diff-fecda966dc2808695e352f153a981a39f19d31c17a32f1b6315bdb239f74af19R65
Resolves #
=> Fix traces/spans aggregations for feedback scores

apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java
Project statistics tests were not covering correct stat name and type due to a custom comparator implementation mistake. 
I fixed the tests to fail on the wrong stat name, and then fixed the tests to make it green.
OPIK-679
=> [OPIK-679] fix feedback scores tests

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/validate/IdParamsValidator.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/AssertionUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/ProjectResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Return all feedback score names for project ids endpoint
Covered by integration test
=> OPIK-645 Return all feedback score names for project ids endpoint

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/SpanResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Return 409 instead of throwing exception for workspaceId or project mismatch
=> [OPIK-647] Return 409 instead of throwing exception for workspaceId or project mismatch

deployment/docker-compose/README.md, deployment/docker-compose/docker-compose.override.yaml, deployment/docker-compose/docker-compose.yaml
Remove port binding for all services in `deployment/docker-compose/docker-compose.yaml` except:
- Frontend from 5173 container at 5173 in host: needed to access Opik from the browser.
- Backed OpenAPI specification from container 3003 to random host port: this is our public documentation for the API spec.
Opik works normally with this set up.
For development, `deployment/docker-compose/docker-compose.override.yaml` can be used which binds everything to known ports in the host (same as the container port).
The purpose is to reduce the risk of exposing the ports.
Updated documentation as well.
N/A
Run and successfully tested:
- `docker compose -f docker-compose.yaml up -d`
- `docker compose -f docker-compose.yaml -f docker-compose.override.yaml up -d`
N/A
=> NO-JIRA: Remove docker-compose.yaml port binding

apps/opik-frontend/src/components/shared/TraceDetailsPanel/TraceTreeViewer/treeRenderers.tsx
- The custom `renderItem` in the `react-syntax-tree` was lacking of the `onClick` handler that apparently it's needed to focus the item in Safari (without click no focus event is triggered in that browser)
Resolves #990
=> [OPIK-717] Fix click into a span in the tree-viewer in Safari

.github/workflows/end2end_suites.yml, tests_end_to_end/page_objects/FeedbackDefinitionsPage.py, tests_end_to_end/tests/FeedbackDefinitions/test_feedback_definitions_crud.py, tests_end_to_end/tests/Feedbacks/test_feedbacks_crud.py, tests_end_to_end/tests/conftest.py
Coverage: creation, editing and deletion of feedback definitions via the UI (only user-facing way of interacting with them at the moment)
=> OPIK-364 feedback definitions crud tests

tests_end_to_end/tests/Projects/test_projects_crud_operations.py, tests_end_to_end/tests/sdk_helpers.py
Fixed a test that was broken by automatically redirecting to created project's traces page after creation.
Trying to debug a JSONDecodeError on retrieve prompt version method that only seems to happen on GHA
=> NO-OPIK automation fixes

apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/PlaygroundOutputActions.tsx
when we load 25 datasets, it doesn't always show the picked dataset since a selected is out of range
Resolves #
=> [OPIK-655]: fix the dataset number;

apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluator.java, apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluatorLlmAsJudge.java, apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluatorType.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorRowMapper.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleRowMapper.java, apps/opik-backend/src/main/java/com/comet/opik/domain/LlmAsJudgeAutomationRuleEvaluatorModel.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceTest.java
- The main problem was the `AutomationRuleRowMapper`, which pointed to `AutomationRuleEvaluator` instead of `AutomationRuleEvaluatorModel`.
- There was also a tiny mistake related to nested transactions.
- Finally, the mapping documentation was also fixed to so that the generation doesn't break.
I couldn't understand why this only happens within the docker container.
Issues #
OPIK-736
=> [OPIK-736] Fix deserialization issue

apps/opik-frontend/src/constants/playground.ts, apps/opik-frontend/src/types/providers.ts
The list of models has been aligned with the BE Proxy:
Resolves #
=> [OPIK-739]: hide unsupported by ai proxy models;

apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluator.java, apps/opik-backend/src/main/java/com/comet/opik/api/FeedbackDefinition.java, apps/opik-backend/src/main/java/com/comet/opik/api/Span.java, apps/opik-backend/src/main/java/com/comet/opik/api/SpanUpdate.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/AuthenticationConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/BatchOperationsConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/CorsConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/DistributedLockConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/EncryptionConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/LlmProviderClientConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/MetadataConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/OpikConfiguration.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/RateLimitConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/RedisConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/UsageReportConfig.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
Manually set span cost
Covered with integration tests
=> [OPIK-720] Manually set span cost

apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompts/PlaygroundPrompt.tsx, apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompts/PromptModelSelect/PromptModelSelect.tsx, apps/opik-frontend/src/components/shared/AddEditAIProviderDialog/AddEditAIProviderDialog.tsx
Intervenes with the changes of @andriidudar. however, we have already discussed it
Resolves #
=> [OPIK-740]: handle adding provider

apps/opik-backend/src/main/java/com/comet/opik/api/error/JsonInvalidFormatExceptionMapper.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectMetricsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
Return more detailed error message for Json deserialization errors
Covered by integration test
=> [OPIK-721] Return more detailed error message for Json deserialization errors

apps/opik-frontend/src/components/pages/HomePage/EvaluationSection.tsx, apps/opik-frontend/src/components/pages/HomePage/GetStartedSection.tsx, apps/opik-frontend/src/components/pages/HomePage/HomePage.tsx, apps/opik-frontend/src/components/pages/HomePage/ObservabilitySection.tsx
- new get started section
- removed Learn more buttons
- replaced See all buttons
Resolves #
=> [OPIK-706] simplify home page

sdks/python/src/opik/evaluation/models/litellm/litellm_chat_model.py
Added a temporary warnings filter to stop seeing pydantic warning coming from litellm.
LiteLLM maintainers have already fixed that (but haven't released yet), so we'll remove it in the future.
=> Temporary disable litellm import warnings

apps/opik-frontend/package-lock.json, apps/opik-frontend/package.json, apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessagesVariables/LLMPromptMessagesVariable.tsx, apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessagesVariables/LLMPromptMessagesVariables.tsx, apps/opik-frontend/src/components/pages-shared/traces/TracesPathsAutocomplete/TracesPathsAutocomplete.tsx, apps/opik-frontend/src/components/pages/TracesPage/RulesTab/AddEditRuleDialog/AddEditRuleDialog.tsx, apps/opik-frontend/src/components/pages/TracesPage/RulesTab/AddEditRuleDialog/LLMJudgeRuleDetails.tsx, apps/opik-frontend/src/components/pages/TracesPage/RulesTab/RulesTab.tsx, apps/opik-frontend/src/components/shared/Autocomplete/Autocomplete.tsx, apps/opik-frontend/src/components/ui/command.tsx, apps/opik-frontend/src/components/ui/skeleton.tsx, apps/opik-frontend/src/lib/utils.ts
=> [OPIK-753] [FE] Autocomplete component for variable key select

apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000010_create_automation_rule_evaluator_logs_table.sql, apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000010_create_evaluation_rule_log_table.sql
This table will store all rule logs, shown per rule. That will allow the user to see what happens during the online evaluation process.
OPIK-795
=> OPIK-795: Create rule logs table

.github/workflows/build_apps.yml
Updated Github action to build and push the `opik-python-backend` service image.
OPIK-663
After merging and pushing a change, image will be verified at: 
- https://github.com/orgs/comet-ml/packages?repo_name=opik
N/A
=> OPIK-663: Add Python Backend image builder

tests_end_to_end/page_objects/DatasetItemsPage.py, tests_end_to_end/page_objects/ExperimentItemsPage.py, tests_end_to_end/page_objects/FeedbackDefinitionsPage.py, tests_end_to_end/page_objects/PromptPage.py, tests_end_to_end/page_objects/TracesPage.py
Traces tests got broken because adding a 4th tab above the tables interfered with the locator for the next page button that was being used. Changed the locator everywhere to cover this and any possible future changes.
=> NO-OPIK fix locator for next page buttons

apps/opik-frontend/src/components/pages/HomePage/GetStartedSection.tsx
- remove close get-started section button
Resolves #
=> [OPIK-706] remove close get-started section button

apps/opik-python-backend/Dockerfile, apps/opik-python-backend/entrypoint.sh, apps/opik-python-backend/src/opik_backend/__init__.py, apps/opik-python-backend/src/opik_backend/docker_runner.py
The Sandbox Python Executor image is now pulled instead of being built locally. 
The exact registry, name and tag is parameterised as env variables and aligned with the variable names from the Helm charts.
The image is pulled before starting the service as a warm-up. Although this isn't strictly necessary as running a docker container automatically pulls the image if not available locally.
Other improvements in Dockerfile: 
- Added `tini` to handle zombie sub-processes.
- Pulling minimum OS packages
- Better wait on the docker daemon start up.
- Etc.
OPIK-663
- Run all automated tests.
- Curl on Flask service locally.
- Curl on gunicorn server inside Docker.
- https://github.com/krallin/tini
=> OPIK-663: Pull instead of building Sandbox Python Executor image

apps/opik-backend/src/main/java/com/comet/opik/domain/llmproviders/LlmProviderGemini.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ChatCompletionsResourceTest.java
FE reported that Gemini streaming isn't working properly:
> It just waits for the full response and then returns 200 status
I was able to reproduce locally and noticed that `GoogleAiGeminiStreamingChatModel::generate()` is blocking and therefore the chat completions endpoint only responds when the above is finished.
This PR fixes the issue as you can see in this video:
Tested locally by running the application and calling the relevant endpoint.
=> [NA] fix gemini streaming

deployment/docker-compose/README.md, deployment/docker-compose/docker-compose.override.yaml, deployment/docker-compose/docker-compose.yaml
Added `opik-python-backend` service to docker-compose files. Following the usual conventions:
- Version defined by variable `OPIK_VERSION`.
- Override (default behaviour) exposes port into local host.
Documented in `README.md`, plus some minor improvements in this file.
OPIK-663
Successfully started the service and curl the endpoint with a success reponse.
Manual tests:
- Pulled latest version AMD64 in local ARM64.
- Pulled specific version, which applies to both the service and the inner executor images. (AMD64 in local ARM64),
- Build locally as ARM64.
N/A
=> OPIK-663: Add Python Backend to Docker compose

sdks/python/src/opik/evaluation/models/base_model.py, sdks/python/src/opik/evaluation/models/litellm/litellm_chat_model.py
LiteLLMChatModel no longer filters completion_kwargs passed by user if they are not presented in `litellm.get_supported_openai_params()`. It caused a bug when litellm-specific params (e.g. `api_base`) were misclassified as not supported.
With the current implementation the only user-passed argument that can be filtered - `response_format` (there will be a warnings about that in that case)
1. https://github.com/comet-ml/opik/issues/1094
2. Probably https://github.com/comet-ml/opik/issues/1050
Integration tests  work.
Documentation cookbooks workflows also  work.
Updated the docstrings to make them more verbose regarding the arguments passed.
=> [OPIK-838] Add proper support for litellm completion kwargs

sdks/python/setup.py
The minimal version is the one where OpikLogger was introduced.
=> Add minimal litellm version to setup.py

apps/opik-frontend/package-lock.json, apps/opik-frontend/package.json, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/FrameworkIntegrations.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/FrameworkIntegrationsContent.tsx, apps/opik-frontend/src/components/pages/GetStartedPage/GetStarted.tsx, apps/opik-frontend/src/components/pages/HomePage/GetStartedSection.tsx, apps/opik-frontend/src/components/pages/QuickstartPage/Quickstart.tsx, apps/opik-frontend/src/components/shared/SideDialog/SideDialog.tsx, apps/opik-frontend/src/components/ui/sheet.tsx, apps/opik-frontend/src/plugins/comet/FrameworkIntegrations.tsx, apps/opik-frontend/src/plugins/comet/GetStartedPage.tsx, apps/opik-frontend/src/plugins/comet/QuickstartPage.tsx, apps/opik-frontend/src/store/PluginsStore.ts
- implement side dialog component and log a trace dialog
Resolves #
=> [OPIK-759] implement side dialog component and log a trace dialog

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java
Despite the slight differences in the parts and the big difference in granules. I'm confident this new query is more efficient since it postpones the retrieval of fields that are not part of the sortable key. This has sped up the process considerably.
Before:
```
Expression (Project names)
Limit
LimitBy
Expression ((Before LIMIT BY + (Before ORDER BY + Projection) [lifted up part]))
Sorting (Sorting for ORDER BY)
Expression ((Before ORDER BY + Projection))
Expression
ReadFromMergeTree (opik_prod.spans)
Indexes:
PrimaryKey
Keys: 
workspace_id
project_id
Condition: and((workspace_id in ['48d64607-f70d-4cb1-9207-dd658a423f8e', '48d64607-f70d-4cb1-9207-dd658a423f8e']), (project_id in ['019484c0-1a3c-7987-b2d4-0e3598e8717a', '019484c0-1a3c-7987-b2d4-0e3598e8717a']))
Parts: 16/20
Granules: …
```
=> OPIK-859: Reduce find spans query cost

sdks/python/src/opik/api_objects/opik_client.py
Added `truncate` parameter to search_spans & search_traces Opik methods.
=> [NA] Add truncate method to the search_spans and search_traces

apps/opik-backend/src/main/java/com/comet/opik/api/Comment.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/CommentDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/CommentResultMapper.java, apps/opik-backend/src/main/java/com/comet/opik/domain/CommentService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemMapper.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/domain/TraceServiceImplTest.java
=> [OPIK-757] Add support for comments part2

apps/opik-frontend/src/components/pages-shared/onboarding/ApiKeyCard/ApiKeyCard.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/ApiKeyCard/ApiKeyCardCore.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/FrameworkIntegrations.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/FrameworkIntegrationsContent.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/GoogleColabCard/GoogleColabCardCore.tsx, apps/opik-frontend/src/components/pages/ExperimentsShared/AddExperimentDialog.tsx, apps/opik-frontend/src/components/pages/HomePage/GetStartedSection.tsx, apps/opik-frontend/src/components/ui/sheet.tsx, apps/opik-frontend/src/plugins/comet/ApiKeyCard.tsx, apps/opik-frontend/src/plugins/comet/FrameworkIntegrations.tsx, apps/opik-frontend/src/plugins/comet/GoogleColabCard.tsx, apps/opik-frontend/src/store/PluginsStore.ts
=> [OPIK-762] create an experiment dialog improvements

apps/opik-backend/src/main/java/com/comet/opik/api/Comment.java, apps/opik-backend/src/main/java/com/comet/opik/api/Span.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/CommentDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/CommentResultMapper.java, apps/opik-backend/src/main/java/com/comet/opik/domain/CommentService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000012_extend_comments_entity_type_span.sql, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/AssertionUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/CommentAssertionUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/FeedbackScoreAssertionUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/BaseCommentResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/BaseTestClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/SpanResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/domain/SpanServiceTest.java, apps/opik-backend/src/test/java/com/comet/opik/domain/TraceServiceImplTest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/cache/CacheManagerTest.java
=> [OPIK-844] Add support for span comments

apps/opik-frontend/src/components/pages/CompareExperimentsPage/ConfigurationTab/ConfigurationTab.tsx
=> [OPIK-887] Change flattening delimiter from "|" to "." in experiment configuration

sdks/python/src/opik/integrations/openai/opik_tracker.py
When wrapping the OpenAI client with the tracker, it set the type as a Union of both the regular and async client. This caused downstream type check errors when using OpenAI classes. TypeVar can resolve this by allowing the output type to match the input type. The IDE will now understand that the type of the client remains the same.
This is the same pattern that currently exists in the Anthropic wrapper.
Resolves #1152 
Tested locally, fixed the problem. This is my first time contributing, so would love advice/help on what the order of operations is for contributing.
No updates to documentation required.
=> Resolve Typing Issues on Wrapping OpenAI Client

sdks/python/src/opik/evaluation/metrics/heuristics/regex_match.py
The regex example in `regex_match.py` was using `\d` in a regular string, which triggers a Python `SyntaxWarning: invalid escape sequence '\d'` when running an application using Opik. This warning occurs because Python interprets backslashes in regular strings as escape sequences, and `\d` is not a valid escape sequence.
Resolves #1163 
This change properly escapes the backslashes in the regular string while maintaining identical regex matching functionality. The double backslash ensures Python correctly passes a single backslash to the regex engine.
- Verified that the warning no longer appears when running the application
- Confirmed that the regex pattern continues to match the same strings as before. Doesn't really matter since it's just an example
=> modified regex example to fix invalid escape strings warning

apps/opik-frontend/src/components/pages-shared/onboarding/CodeExecutor/CodeExecutor.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/ConfigureEnvCode/ConfigureEnvCode.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/ConfigureEnvCode/ConfigureEnvCodeCore.tsx, apps/opik-frontend/src/components/pages/ExperimentsShared/AddExperimentDialog.tsx, apps/opik-frontend/src/plugins/comet/ConfigureEnvCode.tsx, apps/opik-frontend/src/store/PluginsStore.ts
- put ApiKey and workspace name to add experiment dialog
- close Quickstart Dialog after click on "view traces"
Resolves #
=> [OPIK-902] put ApiKey and workspace name to add experiment dialog

apps/opik-frontend/src/api/api.ts, apps/opik-frontend/src/api/projects/useProjectBatchDeleteMutation.ts, apps/opik-frontend/src/api/projects/useProjectCreateMutation.ts, apps/opik-frontend/src/api/projects/useProjectDeleteMutation.ts, apps/opik-frontend/src/api/projects/useProjectStatisticList.ts, apps/opik-frontend/src/api/projects/useProjectUpdateMutation.ts, apps/opik-frontend/src/api/projects/useProjectsList.ts, apps/opik-frontend/src/components/pages/HomePage/ObservabilitySection.tsx, apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/useActionButtonActions.ts, apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx, apps/opik-frontend/src/hooks/useProjectWithStatisticsList.ts, apps/opik-frontend/src/types/projects.ts
FE makes 2 requests on the Home and Projects page to retrieve projects with statistics. 
Resolves #
https://www.notion.so/cometml/Project-Endpoint-Split-18a7124010a380f8a9a7e47f4af17fcc?d=18a7124010a3807783d5001c94873d63#18a7124010a380db83fcc91fa252f529
=> [OPIK-905] [FE] Split find project endpoint into two endpoints: find and stats

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemResultMapper.java
I couldn't reproduce it yet
```
exception.message:duplicate element: NUMBER
exception.stacktrace:java.lang.IllegalArgumentException: duplicate element: NUMBER
at java.base/java.util.ImmutableCollections$Set12.<init>(ImmutableCollections.java:798)
at java.base/java.util.Set.of(Set.java:704)
at com.comet.opik.domain.DatasetItemResultMapper.lambda$mapColumnsField$2(DatasetItemResultMapper.java:83)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java
```
OPIK-917
=> OPIK-917: Fix DatasetItemPage error:  java.lang.IllegalArgumentException: duplicate element: NUMBER

apps/opik-backend/src/main/java/com/comet/opik/api/Prompt.java, apps/opik-backend/src/main/java/com/comet/opik/api/PromptType.java, apps/opik-backend/src/main/java/com/comet/opik/api/PromptVersion.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringEngine.java, apps/opik-backend/src/main/java/com/comet/opik/domain/PromptDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/PromptService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/PromptVersionDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/template/Jinja2Parser.java, apps/opik-backend/src/main/java/com/comet/opik/domain/template/MustacheParser.java, apps/opik-backend/src/main/java/com/comet/opik/domain/template/TemplateParser.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/PromptVersionColumnMapper.java, apps/opik-backend/src/main/java/com/comet/opik/utils/MustacheUtils.java, apps/opik-backend/src/main/java/com/comet/opik/utils/TemplateParseUtils.java, apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000010_add_type_to_prompt_version.sql, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/PromptResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/podam/manufacturer/PromptVersionManufacturer.java
=> [OPIK-855] Add type to prompt version

apps/opik-frontend/src/components/ui/table.tsx, apps/opik-frontend/src/main.scss
=> OPIK-918 Experiment configuration comparison is showing the wrong data in some cases

apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx, apps/opik-frontend/src/components/pages/ExperimentsShared/table.tsx, apps/opik-frontend/src/components/pages/PromptPage/ExperimentsTab/ExperimentsTab.tsx, apps/opik-frontend/src/components/shared/DataTable/utils.tsx
Resolves #
- Manually tested on the Projects page (with sorting applied)
- Manually tested on the Experiments page with groups and subgroup rows
=> [OPIK-863] Allow to quickly select multiple rows with Shift+Click

apps/opik-frontend/src/components/pages-shared/onboarding/CodeExecutor/CodeExecutor.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/FrameworkIntegrationsContent.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/IntegrationTemplate.tsx, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Anthropic.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Bedrock.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/DSPy.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/FunctionDecorators.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Gemini.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Groq.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Haystack.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/LangChain.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/LangGraph.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/LiteLLM.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/LlamaIndex.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/OpenAI.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Ragas.py, apps/opik-frontend/src/components/shared/CodeHighlighter/CodeHighlighter.tsx, apps/opik-frontend/src/hooks/useCodemirrorLineHighlight.tsx, apps/opik-frontend/src/lib/formatCodeSnippets.ts, apps/opik-frontend/src/main.scss
=> [OPIK-901] [Activation rate] Add line highlights in activation rate code blocks

apps/opik-frontend/package-lock.json, apps/opik-frontend/package.json, sdks/typescript/package-lock.json, sdks/typescript/package.json
- Closes https://github.com/comet-ml/opik/security/dependabot/37 + https://github.com/comet-ml/opik/security/dependabot/38
Resolves #
=> Upgrade vitest dependency to 3.0.5

apps/opik-frontend/src/plugins/comet/UserMenu.tsx, apps/opik-frontend/src/plugins/comet/WorkspacePreloader.tsx, apps/opik-frontend/src/plugins/comet/types.ts, apps/opik-frontend/src/plugins/comet/useAllUserWorkspaces.ts
- For Cloud version: Change the way of getting the workspaces of the user, instead of limiting the `/api/auth/test` -> `teams` field, now we fetch all the workspaces of the user + fetch all the workspaces of the organization where the user is an admin. As result we'll allow admin users to go to workspaces where it's not part of it without having to self-invite by itself
Resolves #
=> [OPIK-915] Display all the workspaces of the organization if the user is an admin of it

sdks/python/src/opik/evaluation/metrics/llm_judges/g_eval/metric.py, sdks/python/src/opik/integrations/langchain/google_run_helpers.py, sdks/python/tests/e2e/verifiers.py
LLM call pricing isn’t always correctly determined for the Vertex-AI provider. The provider detection logic was fixed.
=> [OPIK-955] [BUG] [SDK] improve VertexAI provider detection

sdks/python/src/opik/id_helpers.py, sdks/python/tests/unit/test_id_helpers.py
Updated the UUIDv4 to UUIDv7 function to handle timestamps correctly, also added unit tests for it
=> [OPIK-568] Updated uuidv4_to_uuidv7 function to handle timestamps

apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx, apps/opik-frontend/src/components/pages/HomePage/EvaluationSection.tsx, apps/opik-frontend/src/components/pages/HomePage/ObservabilitySection.tsx, apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx, apps/opik-frontend/src/components/shared/FeedbackScoreTag/FeedbackScoreTag.tsx, apps/opik-frontend/src/lib/money.ts
- feedback scores tag UI fixes
- round feedback scores value to 3
- remove columns from home page
- show feedback scores column by default on Experiment page
- show "-" if total cost is 0
Resolves #
=> [OPIK-964] home page improvements

apps/opik-sandbox-executor-python/requirements.txt, sdks/python/setup.py, sdks/python/src/opik/integrations/bedrock/opik_tracker.py
Improves typing of Bedrock client from BaseClient to BedrockRuntimeClient.
Resolves #1250
Worked when I modified my imported version of Opik. A CometML dev will want to pull down and make sure the updates to setup.py and requirements.txt work as expected, as my setup is using pyproject.toml + Poetry.
=> added typing for BedrockRuntimeClient

apps/opik-documentation/documentation/docs/tracing/log_traces.mdx, sdks/typescript/README.md, sdks/typescript/examples/ai-sdk-integration.ts, sdks/typescript/package-lock.json, sdks/typescript/package.json, sdks/typescript/src/opik/decorators/track.ts, sdks/typescript/src/opik/index.ts, sdks/typescript/src/opik/integrations/vercel/exporter.ts, sdks/typescript/src/opik/integrations/vercel/index.ts, sdks/typescript/src/opik/integrations/vercel/tracer.ts, sdks/typescript/tests/ai-sdk.test.ts, sdks/typescript/tests/batch.test.ts, sdks/typescript/tests/track.test.ts, sdks/typescript/tsconfig.json, sdks/typescript/tsup.config.ts
- Created `OpikExporter` to create with the OpenTelemetry Node SDK the telemetry instrument for attaching to the Vercel AI SDK
- Improve bundling system (`opik` and `opik/vercel`)
- Added more examples + improved README file
`.env`:
```bash
OPIK_API_KEY="your-api-key"
OPIK_HOST="https://www.comet.com/opik/api"
OPIK_PROJECT_NAME="your-project-name"
OPIK_WORKSPACE_NAME="your-workspace-name"
OPENAI_API_KEY="your-openai-key"
```
Install:
```bash
npm install opik ai @ai-sdk/openai @opentelemetry/sdk-node @opentelemetry/auto-instrumentations-node
```
Code snippet:
```typescript
import { openai } from "@ai-sdk/openai";
import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node";
import { NodeSDK } from "@opentelemetry/sdk-node";
import { generateText } from "ai"; …
```
=> [OPIK-933] [Typescript SDK] Add integration for Vercel AI SDK

sdks/typescript/examples/track-decorator-wrapper.js, sdks/typescript/package-lock.json, sdks/typescript/package.json, sdks/typescript/src/opik/decorators/track.ts, sdks/typescript/src/opik/index.ts, sdks/typescript/tests/track.test.ts
- Replace old `withTrack` decorator wrapper with the same `track` function (overloaded for TS decorators and simple wrapper decorators)
- Log input/output/errors in the track decorator
- Add `getTrackContext` to access to the current span/trace of the tracked function in order to being able to update or perform any operations with the current span and trace
- Added testing for the new cases
- Missing documentation, it'll be delivered separately
=> [OPIK-934] [TypeScript SDK] Improve track decorator

apps/opik-frontend/src/plugins/comet/UserMenu.tsx
- Only display workspaces where the user is member of (not all organization workspaces if you are an admin anymore)
Before
After (admin not being part of `fcarril-asdas` workspace, can access, not in the dropdown anymore)
=> [OPIK-1009] Only display workspaces where the user is member of

apps/opik-documentation/documentation/docs/tracing/export_data.md, sdks/python/src/opik/api_objects/opik_query_language.py, sdks/python/tests/unit/api_objects/test_opik_query_language.py
Add support for searching traces and spans by feedback scores even if they contain spaces:
```
traces = client.search_traces(
filter_string='feedback_score."My Score" > 0'
)
```
=> Add support for searching feedback scores with spaces

apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutput.tsx, apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputTable/PlaygroundOutputCell.tsx, apps/opik-frontend/src/main.scss
The problem was that tailwind setup removes `list-style` for `ul, ol, li` by making it `none`.
Resolves #
=> [OPIK-943]: fix the ordered and unordered lists in playground;

apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/main/java/com/comet/opik/utils/BinaryOperatorUtils.java
Using a built-in solution for the case insensitive map
OPIK-1010
=> OPIK-1010: Use better solution for case insensitive map

sdks/python/src/opik/cli.py, sdks/python/src/opik/configurator/configure.py, sdks/python/tests/unit/configurator/test_configure.py
If `opik configure` is called with `--yes` or `-y` then instead of asking a user for approval (with yes/no options) when it might be needed, an answer will automatically be set to True.
For example `opik configure --use-local --yes` will not lead to asking about using a currently running opik server if it was detected by configurator. The answer will assumed to be `yes` automatically.
The argument `automatic_approvals` appeared in python version of the configuration API.
Also added `--use-local` option in addition to the existing `--use_local`.
Resolves https://github.com/comet-ml/opik/issues/1287
New unit tests are added. Also tested manually.
Docstrings are updated.
=> [OPIK-1026] Add `--yes` and `-y` options to `opik configure` CLI command

sdks/python/src/opik/integrations/langchain/opik_tracer.py, sdks/python/tests/library_integration/langchain/test_langchain.py
It is possible to pass distributed headers to `langchain` callback init.
In that case root span will be attached to a parent span from those headers.
Test added
=> [OPIK-993] [SDK] Update langchain integration to support distributed headers

apps/opik-backend/pom.xml
Aiming to get the latest dependency upgrades.
OPIK-1036
- https://github.com/dropwizard/dropwizard/releases/tag/v4.0.12
=> OPIK-1036: Upgrade opik-backend to latest Dropwizard version

apps/opik-backend/pom.xml
Review and bump and all dependencies. 
They happen to be just minor versions.
Still the ClickHouse client dependencies left behind.
OPIK-1036
- https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-core
- https://mvnrepository.com/artifact/org.projectlombok/lombok
- https://mvnrepository.com/artifact/org.mapstruct/mapstruct
- https://mvnrepository.com/artifact/org.testcontainers/testcontainers-bom
- https://mvnrepository.com/artifact/software.amazon.awssdk/bom
- https://mvnrepository.com/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper
- https://mvnrepository.com/artifact/io.projectreactor/reactor-test
- https://mvnrepository.com/artifact/uk.co.jemos.podam/podam
- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-source-plugin
- …
=> OPIK-1036: Upgrade opik-backend dependencies

apps/opik-backend/pom.xml
Upgrading the remaining dependencies.
They're all minor versions.
OPIK-1036
- https://mvnrepository.com/artifact/com.github.spullara.mustache.java/compiler
- https://mvnrepository.com/artifact/io.projectreactor/reactor-test
- https://mvnrepository.com/artifact/com.diffplug.spotless/spotless-maven-plugin
=> OPIK-1036: Updated backend dependencies part 2

apps/opik-backend/pom.xml
Upgraded only transitive dependencies:
- `netty` with a BOM.
- `json-smart`.
Regarding `httpcore5` as it's also a transitive dependency, it was wrongly defined a `dependency` in a previous PR https://github.com/comet-ml/opik/pull/1299. It's not an actual direct dependency, so moved to `dependencyManagement` which is the correct place.
OPIK-1036
- https://mvnrepository.com/artifact/io.netty/netty-bom
- https://mvnrepository.com/artifact/org.apache.httpcomponents.core5/httpcore5
- https://mvnrepository.com/artifact/net.minidev/json-smart
=> OPIK-1036: Updated backend dependencies part 3

apps/opik-backend/src/main/java/com/comet/opik/domain/llm/LlmProviderService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/antropic/LlmProviderAnthropic.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/gemini/GeminiErrorObject.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/gemini/LlmProviderGemini.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/openai/LlmProviderOpenAi.java
Gemini client errors were not handled correctly. The purpose of this PR is fix the Gemini error handling method to respond with a human readable error.
Gemini API throws `RuntimeException`s with the error details as a JSON inside the message. This PR adds parsing to the error message in order to extract the meaningful part out of it.
OPIK-853
Tested locally:
```
❯ curl -v -X "POST" -H "Content-Type: application/json" --data '{"model":"gemini-1.5-flash","messages":[{"role":"user","content":"why are the sky blue?"}],"stream":true,"stream_options":{"include_usage":true},"temperature":0,"max_completion_tokens":1024,"top_p":1}' http://localhost:8080/v1/private/chat/completions
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* Connected to localhost …
```
=> [OPIK-853] handle gemini client errors

apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluator.java, apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluatorLlmAsJudge.java, apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluatorType.java, apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluatorUpdate.java, apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluatorUpdateLlmAsJudge.java, apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluatorUpdateUserDefinedMetricPython.java, apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleEvaluatorUserDefinedMetricPython.java, apps/opik-backend/src/main/java/com/comet/opik/api/AutomationRuleUpdate.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringSampler.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationModelEvaluatorMapper.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorModel.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorRowMapper.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AutomationRuleEvaluatorService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/UserDefinedMetricPythonAutomationRuleEvaluatorModel.java, apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000011_add_automation_rule_evaluators_type_user_defined_metric_python.sql, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/AutomationRuleEvaluatorResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceDeprecatedTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/domain/AutomationRuleEvaluatorServiceImplTest.java
Extending the online evaluator CRUD endpoints to add support for the Python code evaluator.
The update objects required a bigger refactor, as they weren't polymorphic.
The service returned types weren't polymorphic either, I upgraded them.
Fixed some bugs along the way:
- DAO count.
- DAO order.
Major refactors in the tests in order to make them more maintainable and faster, by avoiding duplications.
More PRs will follow to extend the support to the online evaluator.
OPIK-664
Extended test coverage for the new python evaluator types: model, evaluator object and evaluator update.
- Added and updated endpoints tests.
- Updated cache tests.
- Updated deprecated tests.
N/A
=> OPIK-664: Add Python evaluator CRUD endpoints support

.github/workflows/release.yaml, .github/workflows/typescript_sdk_publish.yml
- Align the TypeScript SDK publish workflow to accept a version instead of patch/minor/major
- Call the TypeScript SDK publish workflow from the `release.yaml`
- Some changes were applied due proper yaml formatter (I could rollback them if needed)
=> [OPIK-1011] [TypeScript SDK] Integrate the TypeScript SDK publish into the general release workflow

apps/opik-backend/src/main/java/com/comet/opik/utils/AsyncUtils.java
Currently, after the retry is exhausted, the error throw is RetryExhaustedException and the original exception is omitted
=> NA: Throw original error when retry exhausted

.github/workflows/end2end_suites.yml, tests_end_to_end/README.md, tests_end_to_end/pytest.ini, tests_end_to_end/tests/Datasets/test_dataset_items_crud_operations.py, tests_end_to_end/tests/Datasets/test_datasets_crud_operations.py, tests_end_to_end/tests/Experiments/test_experiment_crud_operations.py, tests_end_to_end/tests/Experiments/test_experiment_items_crud_operations.py, tests_end_to_end/tests/FeedbackDefinitions/test_feedback_definitions_crud.py, tests_end_to_end/tests/Projects/test_projects_crud_operations.py, tests_end_to_end/tests/Prompts/test_prompts_crud_operations.py, tests_end_to_end/tests/Traces/test_trace_spans.py, tests_end_to_end/tests/Traces/test_traces_crud_operations.py, tests_end_to_end/tests/conftest.py
Details
Improved logging and error handling for all tests in the integration e2e tests, example:
Also changed most of the tests' docstrings to make each step in the test clear and precise.
The purpose of this is making the results readable by non-QA team members, in order to better figure out whether a failure is caused by recent changes/a bug, or is expected, and also for anyone to better pinpoint what they need to debug in case of a failure. This should make the steps and results from the tests much easier to interpret and keep up with.
The PR is very large, but the bulk of it is wrapping test steps in try-except blocks for better error handling/error message display, and modifying the docstring of every test. There has been no functional changes to any of the tests, and they should run …
=> OPIK-991 Better logging and error handling for integration E2E tests

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/AuthCredentialsCacheService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/AuthModule.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/CacheService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RemoteAuthService.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/RemoteAuthServiceTest.java
Removed the distributed lock from the `RemoteAuthService` when retrieving the `userName` and `workspaceId` from Redis cache for a particular `apiKey` and `workspaceName`. 
Reasons:
1. It seems to be causing high latencies, as it serialises across all instances that cache retrieval for each `apiKey` and `workspaceName` combination.
2. It was not really useful:
2.1. Cache insertion was not within the critical section created by the distributed lock.
2.2. The cached data can't really change.
2.3. If cached data changed, it doesn't really matter as last wins and expires quickly (5s).
Additionally, the `AuthCredentialsCacheService` used a `List` object which doesn't handle concurrency properly if by chance multiple values are inserted. I changed it for a `Map` with clearly defined keys. The …
=> OPIK-1081: Remove lock from RemoteAuthService

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
When creating an experiment with the same ID, a `409 Conflict` is no longer returned. Instead, the existing experiment by that ID is returned without creating a new one.
When not created and returned, the experiment created event isn't posted: 
1. No event was really created.
2. No experiment should be recorded for the related dataset ID, including updating the `last_created_experiment_at`.
Additionally, improved logs, code and test health along the way.
Resolves OPIK-962
- Updated related test: when experiment already exists.
- Passed related tests: including normal experiment creation.
- Manually tested the cases above and also a 500 exception.
N/A
=> OPIK-962: Make experiment creation idempotent

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/gemini/GeminiErrorObject.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/ChatCompletionsClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ChatCompletionsResourceTest.java
Fixes bad error message presented to the user due to extra fields in the original payload.
OPIK-1145
Added an E2E test covering this flow.
=> [OPIK-1145] Fix non-helpful message for gemini invalid api key

CONTRIBUTING.md, README.md, apps/opik-backend/entrypoint.sh, apps/opik-backend/run_db_migrations.sh, deployment/docker-compose/README.md, deployment/docker-compose/docker-compose.yaml
Follow up from: https://github.com/comet-ml/opik/pull/1464
There's no way to prevent inconsistency between build and runtime by playing with `ARG` and `ENV` in `apps/opik-backend/Dockerfile`, so added a comment warning about this problem.
Improved backend start-up and migration scripts, for better debugging info.
Reviewed all `*.MD` files for `docker compose`, no changes as result.
#1413 
- Run service and verified both migration and start-up scripts.
N/A
=> issues-1413: follow-up improvements

sdks/python/src/opik/api_objects/opik_client.py, sdks/python/tests/e2e/test_feedback_scores.py, sdks/python/tests/e2e/verifiers.py
Added two methods to delete feedback scores from trace/span
Resolves #
https://github.com/comet-ml/opik/issues/1442
e2e test is added
=> [OPIK-1157] [SDK] [FR]: Python SDK: Provide method to delete trace feedback scores

apps/opik-backend/src/main/java/com/comet/opik/api/SpansCountResponse.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/internal/UsageResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/internal/UsageResourceTest.java
This PR adds a new resource: `/workspace-span-counts`.
Its logic is very similar to the existing `/workspace-trace-counts` endpoint - provides daily span count per workspace for the previous day.
OPIK-1191
Added an E2E test that covers the new logic.
=> [OPIK-1191] get spans counts by workspace

deployment/helm_chart/opik/README.md, deployment/helm_chart/opik/templates/configmap-frontend-nginx.yaml, deployment/helm_chart/opik/values.yaml
[DEV-2650](https://comet-ml.atlassian.net/browse/DEV-2650])
[DEV-2650]: https://comet-ml.atlassian.net/browse/DEV-2650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2650] set configurable proxy timeouts for opik backend

apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsActionsPanel.tsx, apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesActionsPanel.tsx
Solution: When downloading items, a new column called <feedback_score>_reason is added if one of the items to download has a reason.
Resolves #
Tested manually
=> [OPIK-1223] [FR]: Export the reason field of metrics via JSON download

sdks/python/src/opik/api_objects/experiment/experiment.py, sdks/python/src/opik/api_objects/experiment/rest_operations.py, sdks/python/src/opik/api_objects/opik_client.py, sdks/python/src/opik/evaluation/evaluator.py, sdks/python/src/opik/evaluation/rest_operations.py, sdks/python/tests/e2e/test_experiment.py
The Pull Request introduces additional methods and properties for better handling and retrieval of experiments, including the usage of experiment_id for more precise operations. It also deprecates a method and updates related code to use the new functionality.
Main Changes:
New method in `opik_client.py`: `get_experiments_by_name`, which returns a list of experiments by name.
Addition of new property: `dataset_name` in `experiment.py`.
Introduction of a new method: `get_experiments_data_by_name` in `rest_operations.py`.
Modified `get_experiment_by_name` functionality: Rewritten to handle cases where multiple experiments share the same name.
Deprecation warning: Added in `opik_client.py` for `get_experiment_by_name` with recommendations for alternative methods.
Enhanced evaluator …
=> [OPIK-1096] [SDK] Customerf feedback Python SDK handle multiple results get_experiment_by_name

apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java
It's not required to have a critical section for deleting all these elements: comments and spans.
It isn't required to delete the trace either, as it's a soft delete and it wins or it's ignored if concurrent insert or update.
N/A
- Passed endpoint tests.
N/A
=> NO-JIRA: Remove trace delete lock

sdks/python/src/opik/evaluation/engine/exception_analyzer.py, sdks/python/src/opik/evaluation/metrics/llm_judges/g_eval/metric.py, sdks/python/src/opik/evaluation/models/litellm/litellm_chat_model.py, sdks/python/src/opik/evaluation/models/litellm/opik_monitor.py, sdks/python/src/opik/evaluation/models/litellm/warning_filters.py, sdks/python/src/opik/integrations/crewai/opik_tracker.py
This PR introduces lazy import of `litellm` library.
It will be loaded on the first initialization of `LiteLLMChatModel`.
https://github.com/comet-ml/opik/issues/1475
Manually tested
=> OPIK-876 [SDK] Opik may take a lot of time to import because of litellm

apps/opik-frontend/package-lock.json, apps/opik-frontend/package.json, apps/opik-frontend/src/components/shared/MarkdownPreview/MarkdownPreview.tsx, apps/opik-frontend/src/lib/utils.test.ts, apps/opik-frontend/src/lib/utils.ts
=> [OPIK-1166] Add support for "\n" to "pretty mode" in traces and span sidebar

apps/opik-frontend/src/components/pages-shared/onboarding/EvaluationExamples/evaluation-scripts/EvaluateLLM.py, apps/opik-frontend/src/components/pages-shared/onboarding/EvaluationExamples/evaluation-scripts/EvaluatePrompts.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Anthropic.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/Bedrock.py, apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/integration-scripts/DSPy.py
Added import os to all getting started code templates where it's missing.
Resolves OPIK-1237
In getting started page some of the getting started python code is broken due to missing os import after code injection of the environment configuration code.
Can be seen in [Run evaluations] both templates, as well as [Log LLM calls] in Anthropic, Bedrock, and DSPy
Manual
N/A
=> [Opik 1237] [Bug] Fix getting started issue with os import for injected code

.github/workflows/build_and_push_docker.yaml, .github/workflows/build_apps.yml, .github/workflows/release.yaml
Since building multi-arch Docker images for Opik takes about 30 minutes, I’ve been looking for ways to make it faster.
There are a few options, but most of them are either ugly workarounds or leave the registry with extra images (one for `amd64`, one for `arm64`) on top of the final multi-arch image, which isn’t great.
Therefore, I want to suggest a different approach:
I don't see a reason why do we need multi-arch images for non-release builds. so we could just build regular linux/amd64 images for every build on main or other branches, and only create multi-arch images for official releases. Same for the `latest` tag - it would only be created on release builds (something I wanted to change a while ago).
The new flow is also using the standard action for building and pushing docker …
=> [OPIK-654] New build flow - faster main builds

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java, apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterStrategy.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/DatasetsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
In #1409, two new filter operators were introduced: `is_empty` and `is_not_empty`. The `is_empty` filter didn't work as expected since it didn't consider entities that don't have any feedback score and therefore don't exist in the `feedback_scores` table.
After a discussion with @andriidudar and @andrescrz, we decided to introduce this workaround in `FilterQueryBuilder` which essentially uses a different `FilterStrategy` for the `is_empty` filter while reusing the existing filter query parameter.
OPIK-1226
Changed the existing tests so that each test will contain one entry with no feedback score at all. This reproduces the issue we noticed during integration.
Made sure the tests were failing as expected (empty feedback score is filtered out although it shouldn't) and fixed the code so the …
=> [OPIK-1226] fix feedback scores `is_empty` filter

apps/opik-frontend/src/plugins/comet/UserMenu.tsx, apps/opik-frontend/src/plugins/comet/WorkspacePreloader.tsx, apps/opik-frontend/src/plugins/comet/types.ts, apps/opik-frontend/src/plugins/comet/useAllUserWorkspaces.ts, apps/opik-frontend/src/plugins/comet/useUserInvitedWorkspaces.ts
The issue is that in the EM we have removed `getTeams` from the `auth` endpoint to get it more optimal. Now, we have to rely on a `/workspace` endpoint. What I did was I split the logic of loading workspaces into 2: with the change, there are workspaces a user has been invited to and all accessible to a user. We should release it before EM.
Resolves #
=> [OPIK-1266]: use workspaces instead of getTeams;

apps/opik-frontend/src/components/pages/ExperimentsPage/ExperimentsPage.tsx, apps/opik-frontend/src/components/pages/ExperimentsShared/table.tsx, apps/opik-frontend/src/components/pages/PromptPage/ExperimentsTab/ExperimentsTab.tsx, apps/opik-frontend/src/components/shared/DataTable/DataTable.tsx, apps/opik-frontend/src/components/shared/DataTable/utils.tsx
In the version of Chrome Version 134.0.6998.89 (Official Build) (arm64)
was introduced an issue that the border (from row) for sticky cells is not presented on some displays
this workaround checks if the table can be scrolled and only then allows the library to set the  position sticky for cells
Resolves #
=> [OPIK-1252] [FE] No bottom border on pinned columns

apps/opik-frontend/src/plugins/comet/UserMenu.tsx, apps/opik-frontend/src/plugins/comet/WorkspacePreloader.tsx, apps/opik-frontend/src/plugins/comet/useAdminOrganizationWorkspaces.ts, apps/opik-frontend/src/plugins/comet/useAllWorkspaces.ts, apps/opik-frontend/src/plugins/comet/useUserInvitedWorkspaces.ts
the probem is that we can't get access to all potential workspaces of a user. if they are not an admin of an org, it is not possible to get the list of all org workspaces, so we need to show all workapces as the combination of `all to which a user has been invited` + `all workspaces where a user is an admin`
Resolves #
=> [OPIK-1266]: fix the bug with the workspaces where a user is not an admin;

apps/opik-frontend/src/plugins/comet/UserMenu.tsx
it took the default workspace from the entire list before, now it takes the default from the ones that a user has been invited to
Resolves #
=> [OPIK-1266]: change the logic of a default workspace when changing an organization;

apps/opik-frontend/src/components/pages-shared/experiments/ExperimentsFeedbackScoresSelect/ExperimentsFeedbackScoresSelect.tsx, apps/opik-frontend/src/components/pages-shared/traces/TracesOrSpansFeedbackScoresSelect/TracesOrSpansFeedbackScoresSelect.tsx, apps/opik-frontend/src/components/shared/FiltersButton/rows/DictionaryRow.tsx, apps/opik-frontend/src/constants/filters.ts, apps/opik-frontend/src/lib/filters.ts, apps/opik-frontend/src/types/filters.ts
=> [OPIK-1061] [FE] Add support for `is_empty` in the feedback scores

deployment/docker-compose/docker-compose.yaml, opik.sh
- Make health check backward compatible
- Remove timeout since to void dependencies
- Use `docker compose up -d` do to ensure compatibility
=> OPIK-1260: Fix health check

apps/opik-python-backend/Dockerfile
Image was copied to root folder `/images/` but `./entrypoint.sh` refers to it from `./image/`, which is actually `/opt/opik-python-backend/images/`.
I aligned it by following the general convention of copying resources within the work directory: `./image` or `/opt/opik-python-backend/images`.
N/A
- I will deploy to dev or stg and check for logs `Successfully loaded the Opik Sandbox Executor Python image`
N/A
=> NO-JIRA: Fix images path in Python backend

sdks/python/src/opik/evaluation/metrics/llm_judges/g_eval/metric.py
Fixes #1635 
Manually tested:
Ran the example from the docs about 10 times and got the following output in one of the runs:
```
{"token": "10", "bytes": [49, 48], "logprob": -9999.0, "top_logprobs": [{"token": "\":", "bytes": [34, 58], "logprob": 0.0}, {"token": "\":\n\n", "bytes": [34, 58, 10, 10], "logprob": -21.125}, {"token": "\"", "bytes": [34], "logprob": -22.5}, {"token": "\":\n", "bytes": [34, 58, 10], "logprob": -24.75}, {"token": "\":\r\n", "bytes": [34, 58, 13, 10], "logprob": -26.25}, {"token": "\"\n\n", "bytes": [34, 10, 10], "logprob": -27.8125}, {"token": "\"\n", "bytes": [34, 10], "logprob": -31.8125}, {"token": "\"\r\n", "bytes": [34, 13, 10], "logprob": -35.1875}, {"token": "\"\n\n\n", "bytes": [34, 10, 10, 10], "logprob": -36.5625}, {"token": "\"\r\n\r\n", "bytes": [34, …
```
=> Fix issue with parsing log_probs

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/OpenTelemetryResource.java, sdks/code_generation/fern/fern.config.json, sdks/code_generation/fern/generators.yml, sdks/code_generation/fern/openapi/overrides-global-headers.yaml
Excluded the `OpenTelemetryResource` from the Open API spec. The existing definition was wrong and not containing the latest changes from: https://github.com/comet-ml/opik/pull/1394, so there's no risk of breaking users anyway.
The issue is that request object `ExportTraceServiceRequest` creates an explosion of generated classes.
This PR fixes the issue. Another PR will follow updating the Fern classes and the Open API specs.
Additionally:
- Updated Fern and SDK generation versions to latest.
- Removed fern ignore clauses, which were not really working.
OPIK-1130
- Verified locally by generating classes.
- I'll verify that tests pass in the CI.
- https://github.com/fern-api/fern
=> OPIK-1130: Exclude Otel resource from Open API spec

apps/opik-backend/src/main/java/com/comet/opik/domain/OpenTelemetryMapper.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/OpenTelemetryResourceTest.java
Currently the default behaviour of otel integration was to keep only mapped attributes, but now we will only drop values we've mapped to drop; if there's no matching rule, keep the value as part of `input` section.
OPIK-1234
OPIK-1344
=> [OPIK-1234] OpenTelemetry integration shouldn't drop attributes by default

apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx
Now, when a sidebar is collapsed, the button is now shown by defualt;
Resolves #
=> [OPIK-1336]: expand button change the behavior;

apps/opik-backend/pom.xml
By fixing this, we could enable the configuration of virtual threads. This configuration will allow Reactor to work with virtual threads. 
The backend supports it via the `ENABLE_VIRTUAL_THREADS` environment variable, which affects the Reactor scheduler and Dropwizard Jetty’s thread pool.  
This configuration is disabled by default.
https://issues.apache.org/jira/browse/MSHADE-385?focusedCommentId=17567674&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17567674
=> NA: Fix fat jar manifest definition to allow the use of virtual threads

sdks/typescript/src/opik/index.ts
ts-node running, complains that it imports the type without pointing it out
Resolves #
=> [NA]: sashaa/add type sdk

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDataViewer/InputOutputTab.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsViewer.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/DataTab/ExperimentDatasetItems.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/CompareExperimentsOutputCell.tsx, apps/opik-frontend/src/components/shared/SyntaxHighlighter/SyntaxHighlighter.tsx
We preserve selected mode  for StyleHighlighter for next places:
Trace sidebar -> input
Trace sidebar -> output
Experiments sidebar -> Dataset input
Experiments sidebar -> Experiment item output [index]
Resolves #1677
Manually
=> [ISSUE-1677] [FR]: Remember pretty/JSON/YAML preference for experiment item view

apps/opik-backend/src/main/java/com/comet/opik/domain/pythonevaluator/PythonEvaluatorService.java, apps/opik-python-backend/src/opik_backend/docker_runner.py
Fixed a known dependency injection issue with `@Config` which only reproduces inside the JAR (or Docker), which caused the Python evaluator URL to be null.
Fixed failed Python evaluations in Kubernetes due to Docker `137 out of memory error`.
Added missing logs. 
N/A
- Successful Python evaluation in dev.
- Successful Python evaluation in local Docker.
N/A
=> NO-JIRA: Fixing Python Evaluator URI and service

apps/opik-frontend/src/components/layout/PageBodyScrollContainer/PageBodyScrollContainer.tsx, apps/opik-frontend/src/components/layout/PageLayout/PageLayout.tsx, apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsPanel/CompareExperimentsViewer.tsx, apps/opik-frontend/src/components/shared/NoDataPage/NoDataPage.tsx, apps/opik-frontend/src/hooks/useProjectWithStatisticsList.ts, apps/opik-frontend/src/plugins/comet/RetentionBanner.tsx, apps/opik-frontend/src/plugins/comet/api/useWorkspaceQuotas.ts, apps/opik-frontend/src/plugins/comet/types/quotas.ts, apps/opik-frontend/src/store/AppStore.ts, apps/opik-frontend/src/store/PluginsStore.ts
Added the retention banner based on a workspace
Resolves #
The way I tested it was that I overrode the endpoint:
```
api/organizations/quotas?workspaceName=check-quotas
```
with 
```
{
"quotas" :[
{
"limit": 25000,
"used": 25000,
"type": "OPIK_SPAN_COUNT"
}   
]}
or
{
"quotas" :[
{
"limit": 25000,
"used": 22500,
"type": "OPIK_SPAN_COUNT"
}   
]}
```
=> [OPIK-1277]: price retention banner init;

apps/opik-documentation/documentation/fern/docs/evaluation/metrics/heuristic_metrics.mdx, sdks/python/src/opik/evaluation/metrics/__init__.py, sdks/python/src/opik/evaluation/metrics/heuristics/rouge.py, sdks/python/tests/unit/evaluation/metrics/test_heuristics.py, sdks/python/tests/unit/test_requirements.txt
Introduces a new class ROUGE to implement ROUGE heuristic metric using the `rouge-score` [library](https://pypi.org/project/rouge-score/)
Resolves https://github.com/comet-ml/opik/issues/979
- Includes unit tests covering various argument types and error scenarios.
- Ensures compliance with linting and code quality standards.
Adds documentation for ROUGE in `fern/docs/evaluation/metrics/heuristic_metrics.mdx` including an introduction, dependencies, usage examples, and references.
I am still gaining familiarity with pytest and the ROUGE metric. Feedback and suggestions are welcome! I referred to @kadamrahul18's PR https://github.com/comet-ml/opik/pull/1006 as a reference
=> Implements ROUGE score with unit tests and documentation

apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentStreamRequest.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/CommentAssertionUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/ExperimentResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
Deprecated old unused `getExperimentByName` by a proper implementation for the SDK:
- Returning multiple results.
- Name match as in find endpoint (partial and case insensitive).
- Stream based.
- Cursor based pagination.
Refactored the experiments service and DAO for reusability and tech debt reduction:
- Centralise all the logic in a single query and removed duplication.
- Centralise enrichment process in the service: dataset name and prompt resolution.
OPIK-1119
- Added automation test for all potential scenarios:
-- Pagination.
-- Retrieval of all fields: scores, prompt versions and comments.
- Passed CI regression for refactored parts.
=> OPIK-1119: Add stream experiments by name endpoint

apps/opik-python-backend/entrypoint.sh
Wait for the Docker daemon increased to 30s, which is around our usual wait for Kubernetes probes and docker compose health checks. 
Previous value of 5 was too aggressive and cause the container to fail sometimes when setting `PYTHON_CODE_EXECUTOR_STRATEGY= docker`.
Minor logs improvements.
N/A
- Locally tested with:
`PYTHON_CODE_EXECUTOR_STRATEGY= docker`
and
`docker compose up -d --build `
N/A
=> NO-JIRA: Increased Python backend Docker daemon wait

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringSampler.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AutomationRuleEvaluatorsResourceTest.java
Fixed a bug introduced here: https://github.com/comet-ml/opik/pull/1611#discussion_r2008000736
After adding parallelism when processing the evaluators stream.
That caused the following automation rule logs to disappear and showed the following example error:
```
com.comet.opik.infrastructure.log.ClickHouseAppender: UserLog marker is not set for events: The traceId '0195fadf-e5c3-7f85-a268-a5f8df5f3a4e' was skipped for rule: 'json' and per the sampling rate '0.5'
```
The issue only reproduces when having multiple rules for a project. 
N/A
- Added a test that reproduces the issue before the fix and ensures it doesn't happen after the fix.
- Reproduced and fixed locally.
N/A
=> NO-JIRA: Fix Online Scoring Sampler logs

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDetailsPanel.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx
- added falback in case in state selected span that doesn't exist in trace
- added cleaning of selected stan when closing trace sidebar on Experiments page
Resolves #1744
=> [ISSUE-1744] [Bug]: No data state when navigating between traces from the experiment page

.github/workflows/test_docs_links.yml, tests_end_to_end/tests/Documentation/output.csv, tests_end_to_end/tests/Documentation/test_links.py
Uses linkinator npm package to parse the documentation, recursively checking all the links. Creates a csv file of the output which is then parsed by a Python test that displays the broken links if any and sends the result to TestOps. Set to run daily at noon UTC
=> OPIK-1346 Automated tests for checking the docs for broken links

apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreService.java
During the investigation I realized this error is logged per every feedback score batch that is processed, even when everything goes well.
Removing the `switchIfEmpty` fixed the issue which suggests that the error is timing-related or some reactive propagation issue.
In addition, `NotFoundException` seems strange in this case, I changed it to an `InternalServerErrorException` instead. In addition, added some logging.
OPIK-1010
Ran feedback scores related tests prior to the fix and after it and made sure the error disappears.
=> [OPIK-1010] fix `Error while processing scores batch` error in log

apps/opik-backend/config.yml
Disabling for next open source release, while testing finalises.
N/A
- Tested by building and running the service locally with docker compose.
- Verified all usages, including env vars in Helm configuration.
N/A
=> NO-JIRA: Disable python evaluator

apps/opik-frontend/Dockerfile
Migrate Opik Frontend to Amazon Linux 2023, whose Linux packages are patched often for vulnerabilities.
OPIK-1439
- Tested locally by successfully running building and running with `docker compose up -d --build`.
- I will deploy and test.
- https://hub.docker.com/_/amazonlinux
- https://nginx.org/en/linux_packages.html#Amazon-Linux
=> OPIK-1439: Migrate Opik backend to Amazon Linux 2023

apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java
- The idea of this optimization is to reduce the resultset before the joins
Before:
After:
=> OPIK-1393: Reduce result before join

sdks/opik_optimizer/src/opik_optimizer/integrations/dspy/dspy_optimizer.py
This PR adds Opik's LiteLLM callback to the calls in dspy-based optimizers.
=> Optimizer: add Opik's callback to dspy/LiteLLM

apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/ClickHouseContainerUtils.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/bi/DailyUsageReportJobTest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/bi/OpikGuiceyLifecycleEventListenerTest.java
Due to the need to create a network to link zookeepers, clickhouse containers cannot be reused between different test executions. That is because the way the Network object from the test container (which uses UUID as the network name) is implemented. 
This makes it hard to reuse the network, as every run generates a new network. For this reason, we close the network after all runs.
=> NA: Remove containers after use

apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/MinIOContainerUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/MySQLContainerUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/RedisContainerUtils.java
Since a new version of MySQL was recently published, our tests were broken because we used the latest tag instead of a specific one. To prevent this from happening again, we are defining the version tag to be the same as the ones used on the Docker compose file.
=> NA: Fix docker image versions

apps/opik-python-backend/entrypoint.sh
I noticed py backends metrics were messy on Grafana, like as there we multiple instances being hit on /metrics at random, which is explained by the multiple workers (individual processes) in gunicorn. So for now is much easier to us to reduce to a single worker, but with multithread support.
Also, this much easier to control actual parallelism, as we were actually supporting 4 * PYTHON_CODE_EXECUTOR_PARALLEL_NUM, which was wrong and limiting us to only mutiples of 4.
Finally, I noticed with 4 workers, we were limiting our parallelism to... 4, even with 4 * 10 = 40 containers pre-allocated. So now we will support as many threads as the request parallelism.
Resolves OPIK-1433.
=> [OPIK-1433] Optimize Python OnlineEval parallelism

.github/workflows/backend_tests.yml
Re-running failed test up to 3 times, as we have some flakiness due to infrastructure or programmatic failures.
This will improve the CI experience, by preventing the need to run the whole test action again when experiencing flakiness.
The test report should show this information, which will allow us to debug flaky tests and actually fix them.
N/A
- https://github.com/comet-ml/opik/actions/runs/14490158332
- https://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html
=> NO-JIRA: Handle backend flaky tests

apps/opik-documentation/documentation/fern/docs.yml
As per fern docs we should ommit the `https://`, current main docs are not being indexed by google. Likley fern is rejecting this custom domain which creates redirect/canonical tags.
Google has de-indexed live comet.com domain docs pages.
Resolves #
https://buildwithfern.com/learn/docs/building-and-customizing-your-docs/custom-domain#subdomain
=> fix: valid custom domain for opik docs

sdks/python/setup.py
Latest release of `pydantic-settings` (2.9.0) is broken. It has mistakenly removed public export of `ConfigFileSourceMixin` which Opik uses.
Looking into GitHub repository it looks like the situation will be fixed in next release of `pydantic-settings` https://github.com/pydantic/pydantic-settings/commit/e973d9afc8fbfeaaddca466f10d56e7671e67abd
Right now we exclude version 2.9.0 of `pydantic-settings` to mitigate the issue.
Resolves #
=> [NA] Fixed `pydantic-settings` dependency which was broken

apps/opik-python-backend/requirements.txt
`pydantic-settings` version `2.9.0` is broken (see #1886 for more information). This PR excludes the broken version from `requirements.txt`
Ran the following command:
```
docker compose -f docker-compose.yaml -f docker-compose.override.yaml up python-backend -d --build
```
Once with a requirements file that contains:
```
pydantic-settings==2.9.0
```
And another time with a requirements file that contain:
```
pydantic-settings>=2.0.0,<3.0.0,!=2.9.0
```
Made sure the container crashes during startup for the first and not crashing for the second.
Note that in order to test properly, `no_cache` must be set to `true` in the docker compose file.
=> [NA] Fixed `pydantic-settings` broken dependency in python-backend

.github/workflows/sdks_generate_openapi_spec_and_fern_code.yml
The action fails if no files to commit. This has no other consequences, but it's confusing. 
Added `--allow-empty` flag to handle this and to delegate this case to the push PR action.
N/A
- https://github.com/comet-ml/opik/actions/runs/14597563840
N/A
=> NO-JIRA: Not fail empty commit SDKs spec action

deployment/docker-compose/docker-compose.yaml
When starting the backend service like so:
```
docker compose -f docker-compose.yaml -f docker-compose.override.yaml up backend -d
```
it could not become healthy since its health rely on redis. This PR fixes it.
Ran the following command before and after this change:
```
docker compose -f docker-compose.yaml -f docker-compose.override.yaml up backend -d
```
**Before:**
```
docker ps -a
CONTAINER ID   IMAGE                                           COMMAND                   CREATED          STATUS                      PORTS                                                      NAMES
84e34e0a002d   ghcr.io/comet-ml/opik/opik-backend:latest       "bash -c './run_db_m…"    48 seconds ago   Up 41 seconds (unhealthy)   0.0.0.0:3003->3003/tcp, 0.0.0.0:8080->8080/tcp             opik-backend-1 …
```
=> [NA] fix backed service depends on redis

.github/workflows/backend_tests.yml, .github/workflows/python_backend_tests.yml, .github/workflows/python_sdk_unit_tests.yml, .github/workflows/sdk-e2e-tests.yaml, apps/opik-backend/Dockerfile, apps/opik-frontend/Dockerfile, apps/opik-guardrails-backend/Dockerfile, apps/opik-sandbox-executor-python/Dockerfile
update Dockefiles to run as non-root user
implement changes required to run NGINX as an unprivileged user in opik-frontend
small workflows update - update name for test results for different workflows
Resolves #
=> [OPIK-1457]Run docker images with non root user

apps/opik-backend/src/main/java/com/comet/opik/api/Project.java, apps/opik-backend/src/main/java/com/comet/opik/api/Trace.java, apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java, apps/opik-backend/src/main/java/com/comet/opik/utils/JsonUtils.java, apps/opik-backend/src/test/java/com/comet/opik/TestComparators.java
Client side timestamps in Python, TypeScript and also server side in Java, only support up to microseconds. Whereas ClickHouse timestamps support up to nanoseconds.
In order to add support of ingestion for long running jobs, we'll use a client side `last_updated_at` for conflict resolution. See in progress work in branch:
- https://github.com/comet-ml/opik/tree/andrescrz/OPIK-1332-trace-support-ingestion-long-running-jobs
In preparation for that, reducing the precision of that field to microseconds as it will be ingested from the client and nanoseconds precision isn't possible in that case. 
A PR will follow to actually truncate the ClickHouse field, which in turn should also optimise disk usage and performance.
OPIK-1332
- Covered by tests.
- Will be deployed and tested …
=> OPIK-1332: Reduce view to micro secs of trace last updated at

apps/opik-backend/Dockerfile
moving from `21.0.6-al2023` to  `21.0.7-al2023`
to resolve 
`CVE-2025-21893`
Resolves #
=> [NA] - bump opik-backend base image version

apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000019_reduce_trace_last_updated_at_to_micros.sql
Reducing the precision of `trace.last_updated_at` field to microseconds (6) in the ClickHouse DB field. 
No rollback in the migration, as nanoseconds data will be lost forever once the migration is applied.
Per my testing, the size of the DB table won't change as still uses a int64 under the hood. Less precision just leaves more run for a longer range of values (see documentation).
OPIK-1332
- Applied migration locally in table with about 330K traces.
- Manually tested API responses and UI.
- Manually tested thread filter.
- Passed CI tests.
- https://clickhouse.com/docs/sql-reference/data-types/datetime64
=> OPIK-1332: Reduce trace last updated at to microseconds

apps/opik-backend/src/main/java/com/comet/opik/api/Span.java, apps/opik-backend/src/main/java/com/comet/opik/api/SpanSearchCriteria.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/DatasetsResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ProjectsResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/validate/ParamsValidator.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/SpanResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/spans/SpanAssertions.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/spans/SpansTestAssertion.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
- Add new `exclude` query param that accepts a list like `exclude=["input", "output"]` to remove fields from the response body.
Note: To enable sorting with the capability, when sorting by an excluded column, the column is included in the query but excluded from the returned DTO.
=> OPIK-1476: Add ability to exclude fields from find spans response

sdks/python/tests/e2e/verifiers.py, sdks/python/tests/testlib/assert_helpers.py
Now tags are compared as sets, not lists.
The issue with ordering was detected [here](https://github.com/comet-ml/opik/actions/runs/14661217494/job/41145927115)
=> [NA] Ignore tags order in e2e tests

apps/opik-backend/src/main/java/com/comet/opik/domain/attachment/AttachmentService.java
Fix excessive encoding for attachment urls.
UriBuilder applies encoding to queryParams by default. No need to encode them one more time, it leads incorrect file names
=> [NA] Fix excessive encoding for attachment urls

apps/opik-backend/src/main/java/com/comet/opik/api/Project.java, apps/opik-backend/src/main/java/com/comet/opik/api/Trace.java, apps/opik-backend/src/main/java/com/comet/opik/api/TraceUpdate.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java, apps/opik-backend/src/main/java/com/comet/opik/utils/JsonUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/DurationUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/traces/TraceAssertions.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ProjectsResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/domain/TraceServiceImplTest.java, apps/opik-backend/src/test/java/com/comet/opik/podam/PodamFactoryUtils.java
In preparation for trace ingestion for long-running jobs, made the following changes.
Reduced the required fields for ingestion to the minimum by making `name` optional. That leaves only as required:
- `start_time`: non-nullable, non updatable and desirable to have from the very beginning.
Any other field doesn't require ingestion, as either is optional or is resolved/generated by the service internally.
For consistency, I made `name` an updatable field now through `update` trace endpoint.
Updated trace batch ingestion endpoint as an `upsert` endpoint which uses `last_updated_at` field as client side resolution. This field can be ingested now for this purpose. When not provided, it's resolved internally with the usual behaviour.
Reviewed and updated all the affected trace endpoints:
- …
=> OPIK-1332: Support trace ingestion for long-running jobs

apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
Currently, the find experiments seem to be becoming one of our most expensive endpoints:
Before:
After:
Resolves #
=> NA: Improve find experiment query

sdks/python/src/opik/integrations/dspy/callback.py, sdks/python/src/opik/integrations/dspy/graph.py, sdks/python/src/opik/integrations/dspy/utils.py
LangGraph could add Agent Graphs. But DSPy modules did not. So I added them for DSPy
Need to add tests.
The logging of graph data is only activated when you also pass in a module to the DSPy callback, so there are no backward incompatibilities.
=> [FEAT] Added mermaid graphs for DSPy modules

sdks/python/src/opik/integrations/dspy/callback.py
This PR is a better DSPy callback graph API
Previously, the module was provided at the time of creating the callback. But that was incorrect. The Graph changes for each module. 
Now, the graph is created dynamically.
TODO: Testing will need a variety of DSPy programs
The Callback signature changes from:
```python
OpikCallback(project_name, module)
```
to:
```python
OpikCallback(project_name, log_graph)
```
The default is False, so that one needs to opt-in at this time.
=> [FIX] Better DSPy Graph API

sdks/python/src/opik/message_processing/batching/sequence_splitter.py, sdks/python/tests/unit/message_processing/batching/test_sequence_splitter.py
New algorithm is as fast but takes minimal memory versus the old algorithm
I tested against a 30 MB spans batch.
In term of speed, this is equivalent if not slightly faster:
main branch:
```
654 ms ± 3.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
this branch:
```
620 ms ± 22.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
In term of memory, I measure a spike of 20MB in the main branch and couldn't measure any memory spike in the new branch (versus reading just the data in memory).
=> Improve batch item size estimation

sdks/python/src/opik/config.py, sdks/python/src/opik/guardrails/guardrail.py
The Topic classification takes up to 23s on my CPU throttled at 1Ghz, the new default timeout at 30s seems reasonable.
Resolves #
=> [OPIK-1531] Bump default Guardrails timeout to 30s and make it configurable

sdks/python/src/opik/integrations/adk/adk_decorators.py, sdks/python/tests/e2e_library_integration/adk/test_opik_tracer.py
Add ADK provider determination logic and update tests.
Introduced `get_adk_provider` to determine the LLM provider based on environment variables. Updated `ADKLLMTrackDecorator` to include the provider in span parameters and extended integration tests to validate this behavior.
Fixed integration test to check for provider field value.
=> [OPIK-1552]: [SDK] Add provider field to the span usage in ADK integration

sdks/opik_optimizer/src/opik_optimizer/few_shot_bayesian_optimizer/few_shot_bayesian_optimizer.py
This PR allows the FewShotBayesianOptimizer.evaluate_prompt() to take a string. The one downside is that it then requires task_config.
=> Optimizer: allow string prompts for few-shot

apps/opik-documentation/documentation/fern/docs/quickstart.mdx
Fix typo reported by Chase Fortier
Typescript docs typo:
https://www.comet.com/docs/opik/quickstart
const client = new Opik({
apiKey: "<your-api-key>",
host: "https://www.comet.com/opik/api",
projectName: "<your-project-name>",
workspaceName: "<your-workspace-name>",
});
Should actually be apiUrl instead of host
=> fix docs: correct 'host' to 'apiUrl' in TypeScript quickstart example

apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000024_add_output_input_pre_computed_columns_to_spans_and_traces.sql
We are adding new materialized columns so that later, the stats endpoints will use them rather than calculating the values on the fly.
Until the column materializes, Clickhouse will continue calculating the values on the fly. However, for new rows, the values will be calculated on ingestion or update. Later, probably out of peak hours, we can run the `MATERIALIZE COLUMN` command and backfill all history.
=> OPIK-1547: Add pre-computed column on ingestion to reduce overhead on aggregations

opik.ps1, opik.sh
Added a check in the Opik start up scripts, both sh and ps1, to check if `bake` is available or not. If available, enable it for docker compose with `COMPOSE_BAKE=true`.
There's a bug in Windows and relative paths can't be resolved. Left the code ready to be enabled and annotated with a TODO.
OPIK-1544
- Manually tested both paths on both scripts.
- https://docs.docker.com/build/bake/
- https://docs.docker.com/compose/how-tos/dependent-images/
Windows issue:
- https://github.com/docker/for-win/issues/14761
- https://github.com/docker/buildx/issues/1028
- https://github.com/docker/compose/issues/12669
=> OPIK-1555: Add bake build check to opik sh and ps1 scripts

apps/opik-backend/config.yml, apps/opik-backend/pom.xml, apps/opik-backend/src/main/java/com/comet/opik/OpikApplication.java, apps/opik-backend/src/main/java/com/comet/opik/api/LlmProvider.java, apps/opik-backend/src/main/java/com/comet/opik/api/ProviderApiKey.java, apps/opik-backend/src/main/java/com/comet/opik/domain/LlmProviderApiKeyDAO.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/LlmProviderClientConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/LlmProviderClientApiConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/LlmProviderFactoryImpl.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/gemini/LlmProviderGemini.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/LlmProviderVertexAI.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/VertexAIClientGenerator.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/VertexAIGenerator.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/VertexAIMapper.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/VertexAIModelName.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/VertexAIModule.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/VertextAILlmServiceProvider.java, apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000017_add_provider_config_to_ll_provider_api_key.sql, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/LlmProviderApiKeyResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/auth/AuthServiceImplTest.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/llm/LlmProviderFactoryTest.java, apps/opik-backend/src/test/java/com/comet/opik/podam/manufacturer/ProviderApiKeyManufacturer.java
This PR adds support for Vertex AI from Google on the playground. As the initial scope, we will support Genimi only models, and later add more models. 
- Setup tests 
- Provider resolution
- E2E test will be done manually
- Playground config via API
- Prompt chat request
=> OPIK-1565: Add support for Vertex AI (Gemini) on Playground

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/LlmProviderVertexAI.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/VertexAIClientGenerator.java
- Mapping missing fields from request
- Avoid error "contents can't be null or empty." on `com.google.cloud.vertexai.generativeai.GenerativeModel.buildGenerateContentRequest line 597`
Resolves #
=> OPIK-1569: Vertex AI integration fix to avoid 500 due to missing user or ai message

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/LlmProviderFactoryImpl.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/vertexai/VertexAIClientGenerator.java
- When no location is set, we should use the default one from the Vertex AI langchain framework
=> OPIK-1565: Fix handling of no location set

sdks/python/src/opik/integrations/openai/openai_chat_completions_decorator.py, sdks/python/src/opik/integrations/openai/openai_responses_decorator.py
This pull request addresses an issue where a `NoneType` object was erroneously treated as a mapping while building OpikUsage object
=> [OPIK-1381] [SDK] Fix error 'NoneType' object is not a mapping

apps/opik-backend/src/main/java/com/comet/opik/api/Span.java
Client side timestamps in Python, TypeScript and also many JVMs, only support up to microseconds, whereas ClickHouse timestamps support up to nanoseconds.
In order to add support of ingestion for long running jobs, we'll use a client side `last_updated_at` for conflict resolution.
In preparation for that, reducing the precision of that field to microseconds as it will be ingested from the client and nanoseconds precision isn't possible in that case. 
A PR will follow to actually truncate the ClickHouse field.
See previous PR for traces: https://github.com/comet-ml/opik/pull/1923
OPIK-1510
- Covered by tests.
- Will be deployed and tested.
N/A
=> OPIK-1510: Reduce view to micro secs of span last updated at

apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000025_reduce_span_last_updated_at_to_micros.sql
Reducing the precision of `span.last_updated_at` field to microseconds (6) in the ClickHouse DB field. 
No rollback in the migration, as nanoseconds data will be lost forever once the migration is applied.
See previous PRs:
- https://github.com/comet-ml/opik/pull/2130
- https://github.com/comet-ml/opik/pull/1930
OPIK-1510
- Covered by tests.
- Will be deployed and tested.
- https://clickhouse.com/docs/sql-reference/data-types/datetime64
=> OPIK-1510: Reduce span last updated at to microseconds

apps/opik-backend/src/main/java/com/comet/opik/api/Span.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/RandomTestUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/spans/SpanAssertions.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
In preparation for trace ingestion for long-running jobs:
- Updated span batch ingestion endpoint as an `upsert` endpoint which uses `last_updated_at` field as client side resolution. 
- This field can be ingested now for this purpose. 
- When not provided, it's resolved internally with the usual behaviour.
Reverted previous view changes to reduce `last_updated_at` to microseconds, as this is already enforced on the DB.
Reduced tech debt in the code and in the tests.
See related PR for traces: https://github.com/comet-ml/opik/pull/1992 
- OPIK-1510
- Reviewed, updated and extended test coverage for the related endpoint.
N/A
=> OPIK-1510: Add client side last_updated_at resolution for Span

sdks/python/src/opik/api_objects/experiment/experiment.py, sdks/python/src/opik/integrations/openai/agents/span_data_parsers.py, sdks/python/src/opik/integrations/openai/openai_responses_decorator.py, sdks/python/src/opik/llm_usage/opik_usage_factory.py
Refactoring Usage Logic for LLM Providers:
- Updated _PROVIDER_TO_OPIK_USAGE_BUILDER in opik_usage_factory.py to support multiple build functions per provider.
- Improved error handling by iterating through all potential build functions before raising exceptions.
- Removed outdated comments
Tests are already existing for the refactored code.
=> [OPIK-1407] [SDK] Update Provider-to-OpikUsageBuilder logic

apps/opik-frontend/src/components/pages/CompareExperimentsPage/ExperimentItemsTab/ExperimentItemsTab.tsx, apps/opik-frontend/src/components/pages/CompareTrialsPage/TrialsItemsTab/TrialItemsTab.tsx, apps/opik-frontend/src/components/pages/ConfigurationPage/FeedbackDefinitionsTab/FeedbackDefinitionsTab.tsx, apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx, apps/opik-frontend/src/components/pages/DatasetsPage/DatasetsPage.tsx, apps/opik-frontend/src/components/pages/OnlineEvaluationPage/OnlineEvaluationPage.tsx, apps/opik-frontend/src/components/pages/ProjectsPage/ProjectsPage.tsx, apps/opik-frontend/src/components/pages/PromptPage/CommitsTab/CommitsTab.tsx, apps/opik-frontend/src/components/pages/PromptsPage/PromptsPage.tsx, apps/opik-frontend/src/components/pages/TracesPage/RulesTab/RulesTab.tsx, apps/opik-frontend/src/components/pages/TracesPage/ThreadsTab/ThreadsTab.tsx, apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesSpansTab.tsx, apps/opik-frontend/src/hooks/useQueryParamAndLocalStorageState.ts
- height is stored for all places where it is used
- pagination is saved only for tables
https://github.com/comet-ml/opik/issues/1279
https://github.com/comet-ml/opik/issues/549
Resolves #
=> [OPIK-1027] Persist table pagination settings using query parameters and local storage.

apps/opik-frontend/src/api/datasets/useDatasetItemByName.ts, apps/opik-frontend/src/api/datasets/useExperimentsFeedbackScoresNames.ts, apps/opik-frontend/src/api/traces/useSpanCommentsBatchDeleteMutation.ts, apps/opik-frontend/src/api/traces/useSpansFeedbackScoresNames.ts, apps/opik-frontend/src/api/traces/useTraceCommentsBatchDeleteMutation.ts
The endpoint URL ${SPANS_REST_ENDPOINT}/feedback-scores/names had an issue where two consecutive slashes (//) were formed because the SPANS_REST_ENDPOINT already ends with a slash (/). This was causing an incorrect URL format.
The endpoint URL was incorrectly formed due to double slashes (//) in the URL.
Resolves #2184  
Verified that the correct endpoint URL is now formed without consecutive slashes.
Checked the functionality to ensure the API call works as expected after fixing the URL.
No changes to external documentation required.
=> Fix(api): remove unnecessary slash in endpoint URL

apps/opik-frontend/src/components/shared/MarkdownPreview/MarkdownPreview.tsx, apps/opik-frontend/src/main.scss
=> [OPIK-1542] Fix formating for markdown with extra spaces

apps/opik-documentation/documentation/fern/docs/evaluation/metrics/custom_model.mdx, sdks/python/src/opik/evaluation/models/base_model.py, sdks/python/src/opik/evaluation/models/litellm/litellm_chat_model.py
Simplify the `OpikBaseModel` class, since we don't use the `async` methods in the code I've made these optional. I've also cleaned up the `generate_provider_response` class to explicitly require the messages object
=> Simplify OpikBaseModel class

sdks/opik_optimizer/src/opik_optimizer/evolutionary_optimizer/evolutionary_optimizer.py, sdks/opik_optimizer/src/opik_optimizer/few_shot_bayesian_optimizer/few_shot_bayesian_optimizer.py, sdks/opik_optimizer/src/opik_optimizer/meta_prompt_optimizer.py, sdks/opik_optimizer/src/opik_optimizer/mipro_optimizer/mipro_optimizer.py, sdks/python/src/opik/api_objects/opik_client.py
This PR sends the optimizer name (`MiproOptimizer`, `MetaPromptOptimizer`, etc.) in the metadata when creating an optimization.
The goal is to have the FE display the name in Optimization rows:
@alexkuzmik I'm not sure about making the Python Typings match. 
Once this is merged, then the frontend can get the name out of the metadata to display in the rows.
=> Optimizer: add optimizer name in "Optimization runs"

apps/opik-backend/src/main/java/com/comet/opik/api/Span.java, apps/opik-backend/src/main/java/com/comet/opik/api/SpanUpdate.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/spans/SpanAssertions.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/podam/PodamFactoryUtils.java
In preparation for trace ingestion for long-running jobs, reduced the required fields for ingestion to the minimum by making `name` optional.
For consistency, I made `name` an updatable field now through `update` trace endpoint.
Reduced tech debt by a lot in the DAO code and specially in the tests.
- OPIK-1510
- OPIK-1509
- Reviewed, updated and extended test coverage for all related endpoints.
N/A
=> OPIK-1510: Minimal Span field ingestion

apps/opik-backend/src/main/java/com/comet/opik/infrastructure/auth/RequestContext.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimitInterceptor.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimitResponseFilter.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/ratelimit/RateLimitE2ETest.java
As discussed, we will use the header `RateLimit-Reset` to flag the required wait time. Such a header will contain the amount of time in seconds (integer, non-negative value).
- Same coverage, just added the assert to verify the new header
=> OPIK-1628: Add new RateLimit-Reset header

apps/opik-backend/src/main/java/com/comet/opik/domain/llm/ChatCompletionService.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/LlmProviderError.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/LlmProviderLangChainMapper.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/gemini/GeminiErrorObject.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/openai/OpenAiErrorMessage.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/llm/openrouter/OpenRouterErrorMessage.java
Add error handling to the following scenarios:
- Error before making the request
- Error coming from Vertex AI API
- Error coming from OpenAiClient HTTP Call
```json
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: dev.langchain4j.exception.InternalServerException: {
"error": {
"message": "Internal server error",
"type": "auth_subrequest_error",
"param": null,
"code": "internal_error"
}
}
at dev.langchain4j.internal.ExceptionMapper$DefaultExceptionMapper.mapHttpStatusCode(ExceptionMapper.java:56)
at dev.langchain4j.internal.ExceptionMapper$DefaultExceptionMapper.mapException(ExceptionMapper.java:44)
at dev.langchain4j.internal.ExceptionMapper.withExceptionMapper(ExceptionMapper.java:3 …
```
=> OPIK-1660: Show proper messages on playground

apps/opik-frontend/src/lib/traces.ts
The new OpenAI parsing logic was trying to `in` on a string rather than object which is not supported causing a full page crash.
Resolves #2238
=> Fix OpenAI parsing logic

apps/opik-backend/src/main/java/com/comet/opik/api/Span.java, apps/opik-backend/src/main/java/com/comet/opik/api/SpanUpdate.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanType.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java
In preparation for trace ingestion for long-running jobs, reduced the required fields for ingestion to the minimum by making `type` optional.
For consistency, I made `type` an updatable field now through `type` trace endpoint.
Fixed minor bug with `totalEstimatedCostVersion`.
Reduced some tech debt in the tests.
- OPIK-1510
- #1610
- Reviewed, updated and extended test coverage for all related endpoints.
N/A
=> OPIK-1510: Make span type optional and updatable

apps/opik-frontend/src/components/shared/CalloutAlert/CalloutAlert.tsx, apps/opik-frontend/src/components/shared/ExplainerIcon/ExplainerIcon.tsx
fix: correct typo in "Read more" link text
Fixed a typo where "Raad more" was incorrectly spelled instead of "Read more" in the link text for two components:
- CalloutAlert component
- ExplainerIcon component
No documentation changes required - this is a simple text correction.
=> fix: correct 'Raad more' typo to 'Read more'

apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentItemBulkRecord.java, apps/opik-backend/src/main/java/com/comet/opik/api/validate/ExperimentItemBulkRecordValidation.java, apps/opik-backend/src/main/java/com/comet/opik/api/validate/ExperimentItemBulkRecordValidator.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemBulkIngestionService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
- Add a new column called evaluation task result 
- Add validation to allow either none, only one, or never both columns to be filled
- Test to cover all scenarios
=> OPIK-1734: Add evaluate task result column and validation

apps/opik-python-backend/src/opik_backend/executor_docker.py
- Add warm-up 
- Add a new container to the pool quickly so new requests can be processed
- Remove the container async in the background
Context:
- It takes an average of 1.5 to stop the container that served the request.
=> OPIK-1679: Add warm up and async release of containers

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
No longer needed validation removed.
As batch creation endpoints for spans and traces work as an upsert endpoint, if items with the same ID are sent, the one with the highest `last_updated_at` wins.
For the original use case where `last_updated_at` is not sent from the client side, as the items in the request are defined in a `list`, the last one in the list wins.
- OPIK-1332
- #1610 
- Passed CI tests.
N/A
=> OPIK-1332: Remove duplicate ID validation batch create trace and span

sdks/opik_optimizer/setup.py
dspy versions greater than 2.6.24 have a bug that crashes opik-optimizer
See also: https://github.com/stanfordnlp/dspy/pull/8314
=> Optimizer: pin max dspy version

apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java
- Although a lack of available memory caused the error, checking the explain plan, we could spot an excessive scan of the spans table data.
```
2025.06.04 06:37:42.397010 [ 9717 ] {1160b2e4-94f6-4a34-9c63-32ea464a29de} <Error> executeQuery: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 57.05 GiB (attempt to allocate chunk of 4971071 bytes), maximum: 54.00 GiB. OvercommitTracker decision: Waiting timeout for memory to be freed is reached.: While executing ReplacingSorted. (MEMORY_LIMIT_EXCEEDED) (version 24.3.5.47.altinitystable (altinity build)) 
```
Before:
---------------------------------------------------------------------------------------------------
After:
=> OPIK-1797: Reduce span table index scan

apps/opik-documentation/documentation/fern/docs.yml, apps/opik-documentation/documentation/fern/docs/evaluation/evaluate_with_rest_api.mdx
This guide introduces a step-by-step walkthrough for evaluating LLM applications using the Experiments REST API. It’s especially useful for teams working outside the Python and JavaScript SDKs — such as those using Java, Go, Kotlin, or Ruby.
The guide covers:
•	How to use the PUT /api/v1/private/experiments/items/bulk endpoint to log experiment results in bulk
•	Minimum and optional fields for rich evaluation (e.g., feedback scores, traces, spans)
•	Example requests for common use cases
•	Full working examples in Python and Java (with Jackson and HttpClient)
•	Authentication instructions for both Open-Source and Opik Cloud setups
•	Best practices for using environment variables
This makes it easier for language-agnostic teams to programmatically integrate with Opik and gain visibility …
=> [Docs] Add REST API bulk evaluation docs and navigation entry

.github/workflows/python_sdk_unit_tests.yml, .github/workflows/sdk-e2e-library-tests.yaml, .github/workflows/sdk-e2e-tests.yaml
The `ref` added to the `checkout` action in the workflow resulted in testing code of PR against parent branch - the master in most cases. This PR removes this `ref` from Python SDK workloads.
Resolves #
=> [NA]: Removed ref from checkout actions in Python SDK tests.

.github/workflows/documentation_codeblock_tests.yml, .github/workflows/documentation_image_optimizer.yml, .github/workflows/documentation_preview_link.yml, .github/workflows/end2end_suites.yml
Removed the `ref` parameter from all instances of the `checkout` action in the workflows to avoid performing workflow actions against parent branch (i.e., `master`) instead of current branch.
Resolves #
=> [NA]: Removed the `ref` parameter from all instances of the `checkout` action in the workflows.

apps/opik-documentation/documentation/fern/docs/production/production_monitoring.mdx
Adding documentation for retrieving trace content and updating traces.
Some documentation for get_trace_content() already exists in the langchain integration section but uses the Opik tracer and was confusing if this was a method specific to Langchain.
=> adding documentation for retrieving trace content and updating traces

sdks/python/setup.py, sdks/python/src/opik/evaluation/metrics/heuristics/levenshtein_ratio.py
Replaced Levenshtein dependency with rapidfuzz, which is used under the hood of levenshtein but has a better license.
No new tests were added, unit tests for LevenshteinRatio still pass after replacing one library call with another.
=> [NA] Replace levenshtein dependency with rapidfuzz

apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000028_add_trace_threads_table.sql, apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000018_project_threads_table.sql
- Create the `trace_threads` table to hold all primary data related to threads
- Create the `project_trace_threads` table, which will guarantee unique and consistent ID mapping between  `project_id`, `thread_id`, and the creation of a **trace thread ID** (Opik's internal ID for the thread)
=> OPIK-1765: Create trace thread tables

sdks/typescript/tsconfig.json
This reverts commit 86f9251f9b4f55f7646ed3a9b6a37ab2bdfb1e1a.
And PR: https://github.com/comet-ml/opik/pull/2561
The fix didn't work. There's a follow-up conversation for this. Not a blocker in the meantime.
N/A
N/A
N/A
=> Revert "NO-JIRA: Exclude TypeScript Fern classes from typecheck (#2561)"

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/traces/TraceDBUtils.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
During final tests, we found that the user was unable to close a thread that was created before the entity was introduced. For this reason, we are adding this. So that the user can close the thread manually, and if it doesn't exist, it gets created.
Next, we can think better about what to do in those cases.
=> NA: Create trace thread if it doesn't exist upon closure

apps/opik-frontend/src/lib/file.ts
=> [OPIK-2064] [Dataset upload CSV] CSV with `\r\n` is not parsing correctly

apps/opik-python-backend/Dockerfile, apps/opik-sandbox-executor-python/Dockerfile
Added `--no-cache-dir` flag to pip install in Dockerfile when missing, in order to optimised image size.
N/A
- Built both images locally, with 5% to 12% image size reduction.
- https://pip.pypa.io/en/stable/topics/caching/#disabling-caching
=> NO-JIRA: Add pip cache to all docker images

apps/opik-frontend/src/components/pages-shared/llm/LLMPromptMessagesVariables/LLMPromptMessagesVariable.tsx, apps/opik-frontend/src/components/pages/CompareExperimentsPage/CompareExperimentsDetails/CompareExperimentsDetails.tsx, apps/opik-frontend/src/components/pages/CompareTrialsPage/CompareTrialsDetails/CompareTrialsDetails.tsx, apps/opik-frontend/src/components/shared/ColoredTag/ColoredTag.tsx, apps/opik-frontend/src/components/shared/DataTableCells/ListCell.tsx, apps/opik-frontend/src/components/shared/DataTableCells/TagCell.tsx, apps/opik-frontend/src/components/shared/DateTag/DateTag.tsx, apps/opik-frontend/src/components/shared/RemovableTag/RemovableTag.tsx, apps/opik-frontend/src/components/shared/ResourceLink/ResourceLink.tsx, apps/opik-frontend/src/components/shared/TagListRenderer/TagListRenderer.tsx
=> [OPIK-1270] Make tag component smaller

apps/opik-backend/src/main/java/com/comet/opik/api/filter/FiltersFactory.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/SpansResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
**Steps to reproduce:**
Open the traces page, try adding a filter that contains the % character in the filter value
**Expected result:**
Traces table filters according to the filter input
**Actual result:**
Request fails with 500 error code
**Details:**
The filters string is decoded initially by invoking:
```
filters = JsonUtils.readValue(queryParam, valueTypeRef);
```
Then, the value is decoded again by invoking:
```
filter = filter.build(URLDecoder.decode(filter.value(), StandardCharsets.UTF_8));
```
The reason for the secondary decode seems to be more complex data structures, such as `LIST` and `DICTIONARY`. When trying to decode a string that contains `%`, the decode fails.
This is fixed by not having the second decode for STRING filters. In addition, a `try...catch` logic is applied …
=> [OPIK-2074] Filter crashes for values that contain `%`

apps/opik-backend/config.yml, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/SpansResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ratelimit/RateLimited.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/SpanResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/ratelimit/RateLimitE2ETest.java
This PR implements a new rate limiting configuration specifically for single tracing operations (individual spans and traces creation/updates). The implementation adds a dedicated `singleTracingOps` rate limit bucket that applies to high-frequency single operation endpoints.
**What this change does:**
- Adds a new `singleTracingOps` rate limit configuration to `config.yml` (3 requests per second, 1 second duration)
- Applies `@RateLimited(limit = "singleTracingOps")` annotation to span and trace individual operation endpoints
- Ensures isolation from existing rate limits (workspace and user limits remain unaffected)
**Why this was made:**
- Provides granular control over single tracing operations without affecting batch operations
- Allows different rate limiting strategies for different …
=> OPIK-2163: Add single tracing operations rate limiting

sdks/python/src/opik/rest_client_configurator/retry_decorator.py
Tenacity retry decorator used in our REST API calls now re-raises the original error from the last try instead of always raising RetryError, which wraps the original error.
=> [NA] Reraise instead of retry errors

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDetailsActionsPanel.tsx, apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/helpers.test.ts, apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceTreeViewer/helpers.ts, apps/opik-frontend/src/components/pages/TracesPage/TracesSpansTab/TracesSpansTab.tsx, apps/opik-frontend/src/components/shared/Autocomplete/Autocomplete.tsx, apps/opik-frontend/src/components/shared/FiltersButton/FilterRow.tsx, apps/opik-frontend/src/lib/filters.ts, apps/opik-frontend/src/types/filters.ts, apps/opik-frontend/src/types/shared.ts
=> [OPIK-2160] Traces - filter on specific input keys

apps/opik-documentation/documentation/fern/docs.yml
This PR removes a navigation entry for a missing Vertex AI documentation page from the documentation configuration. The change cleans up the documentation structure by removing a broken link reference.
- Removes the Vertex AI cookbook page entry from the navigation configuration
N/A
N/A
=> [NA] Remove missing doc links for vertexai.mdx

apps/opik-backend/src/main/java/com/comet/opik/api/ExperimentItemBulkUpload.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/ExperimentsResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemBulkIngestionService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
The purpose of this change is to support adding experiment items to existing experiments by specifying an experiment id to the experiment items bulk request payload.
To preserve consistency, experiment name and dataset are validated to be the same as the original experiment (if exists).
OPIK-2213
Added the following resources tests:
- Happy path: add experiment items in 2 bulks
- Dataset consistency: second bulk request with a different dataset will result in `409`
- Experiment name consistency: second bulk request with a different name will result in `409`
=> [OPIK-2213] Add `experimentId` to experiment items bulk

apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackScoreMapper.java, apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsDAO.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/FeedbackScoreAssertionUtils.java
This PR continues the effort from #2935. It adds multi-value feedback scores capabilities to all entities that weren't covered by the previous PR.
**Comment:** Changes were not applied to `WorkspaceMetricsDAO` as its related resource is currently not in use, and it is not clear whether it will be used any time soon.
OPIK-2205
Regression is covered by existing tests.
Tested manually for inserting entries to `authored_feedback_scores`:
- `ProjectMetricsDAO`: made sure results are aggregated in the project metrics page
- `ExperimentDAO`: made sure results are aggregated in the experiments page
- `ExperimentItemDAO`: invoked `http://localhost:8080/v1/private/experiments/items/stream` using `curl` and made sure results are aggregated
- `DatasetItemDAO`: drilled down an experiment and made sure …
=> [OPIK-2205] [BE] apply multi-value feedback scores changes to all entities

apps/opik-documentation/documentation/fern/docs/evaluation/log_experiments_with_rest_api.mdx
Add documentation to the functionality introduced in #2977 which allows to include the `experiment_id` to bulk experiment items upload request and by so add experiment items to an existing experiments.
OPIK-2241
Tested the script added to the documentation locally to make sure it works properly.
=> [OPIK-2241] [DOCS] document bulk experiment item upload in batches

apps/opik-backend/config.yml, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/UsageReportConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/bi/InstallationReportService.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/bi/OpikGuiceyLifecycleEventListenerTest.java, deployment/docker-compose/docker-compose.yaml, opik.ps1, opik.sh
Implements a persistent anonymous ID across installation and backend events to enable consistent analytics:
- Export OPIK_ANONYMOUS_ID from installers and pass it via Docker Compose
- Backend reads OPIK_ANONYMOUS_ID (via usageReport.anonymousId), persists it in MySQL metadata, and uses it for opik_os_startup_be
- opik_os_install_started and opik_os_install_completed now include event_ver: "1"
- Add test to ensure startup event uses and persists the configured anonymous ID
- Resolves #
- OPIK-2252
- OpikGuiceyLifecycleEventListenerTest generates a UUID, configures usageReport.anonymousId, verifies WireMock receives the same anonymous_id, and that UsageReportService persisted it
=> [OPIK-2252] [BE] Consistent anonymous ID across install and backend events

apps/opik-frontend/src/plugins/comet/Logo.tsx
This pull request removes support for plugin-provided custom logos in the application layout. All references to a plugin-provided `Logo` component have been removed, and the default logo component is now used everywhere. This simplifies the logo rendering logic and cleans up related plugin store code.
- Resolves #
- OPIK-2253
=> [OPIK-2253] opik logo for cloud version

apps/opik-backend/src/test/resources/config-test.yml
Optimized ClickHouse async insert parameters in test configuration to reduce wait times for inserts and avoid test flakiness. 
Updated queryParameters to include:
- `async_insert_busy_timeout_max_ms=60`
- `async_insert_busy_timeout_min_ms=50`
- `async_insert=1`
- `wait_for_async_insert=1`
- `async_insert_use_adaptive_busy_timeout=1`
- `async_insert_deduplicate=1`
- NA (Performance optimization)
This change modifies the test configuration to enhance insert performance and minimize test flakiness in ClickHouse operations.
NA
=> [NA] [BE] Optimize ClickHouse async insert parameters to reduce wait times and avoid flakiness

apps/opik-documentation/documentation/fern/docs/evaluation/metrics/custom_metric.mdx
This update adds a section to the Custom Metric documentation on how to create a custom metrics with multiple scores.
=> Add multi-score custom metric example

apps/opik-frontend/src/components/pages/TracesPage/MetricsTab/MetricChart/MetricLineChart.tsx
Fix the issue when the line in the chart has space, the filled area below was black
- Resolves #
- OPIK-2291
Manual testing
=> [OPIK-2291] [FE] Line gradient in feedback scores in metrics tab is black

apps/opik-frontend/src/plugins/comet/InviteUsersForm.tsx
This pull request updates the username validation logic in the `InviteUsersForm` component to allow a wider range of characters, improving flexibility.
Validation improvements:
* Expanded the allowed characters in usernames by updating the `usernameRegex` to permit `.`, `+`, and `-` in addition to letters, numbers, and underscores in 
- Resolves #
- OPIK-2292
=> [OPIK-2292] [FE] fix username regex Invite member

sdks/python/tests/conftest.py, sdks/python/tests/e2e/evaluation/test_threads_evaluate.py, sdks/python/tests/testlib/environment.py
Currently thread evaluation is the only test that requires LLM API key to run, which makes e2e tests jobs red for every external contribution, let’s improve it and try keep e2e tests not requiring any external API keys.
This PR refactors the thread evaluation test to separate concerns around external API dependencies. The changes extract OpenAI API key validation logic into a reusable utility function and update test skip conditions to use this centralized approach.
- Creates a new utility function to check for required OpenAI environment variables
- Updates thread evaluation tests to use the new validation function
- Centralizes the logic for checking external API dependencies
- OPIK-2315
Fixed related test case
No documentation changes
=> [OPIK-2315] [P SDK] Move thread evaluation e2e test requiring real LLM calls to e2e-integration workflow

sdks/python/src/opik/integrations/adk/patchers/adk_otel_tracer/opik_adk_otel_tracer.py, sdks/python/tests/library_integration/adk/test_adk_sync.py
Fixed the bug when OpikTracer interfered with ADK error processing.
- Resolves #
- NA
Updated existing integration test and added a new one.
-
=> [NA] [SDK] alexkuzmik / Fix tests and integration, now error are propagated correctly

sdks/python/CLAUDE.md, sdks/python/src/opik/decorator/base_track_decorator.py, sdks/python/src/opik/decorator/inspect_helpers.py, sdks/python/src/opik/decorator/tracker.py, sdks/python/tests/unit/decorator/test_inspect_helpers.py, sdks/python/tests/unit/decorator/test_tracker_outputs.py
**Problem**: The error handling code in the decorator was trying to access `func.__name__` directly, but `functools.partial` objects don't have this attribute, causing `AttributeError`: `functools.partial` object has no attribute `__name__`.
1. Created a safe helper function: Added `get_function_name()` in `src/opik/decorator/inspect_helpers.py:50-57` that safely handles `functools.partial` objects by
accessing the underlying function's `__name__` attribute.
2. Fixed all usages: Updated 9 instances in `src/opik/decorator/base_track_decorator.py` and 1 instance in `src/opik/decorator/tracker.py` to use the safe helper instead
of direct `func.__name__` access.
3. Added comprehensive tests: created unit tests for the helper function and an integration test that verifies partial functions …
=> [OPIK-937] [P SDK] Opik Evaluate crash when task is wrapped in functools.partial

apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/ExperimentsResourceTest.java
Add new operators support for dictionary type filter
- Resolves #
- OPIK-2317
Added corresponding integration tests
NA
=> [OPIK-2317] [BE] Add new operators support for dictionary type filter

.cursor/commands/comet/address-github-pr-comments.md
This PR adds a new Cursor command `address-github-pr-comments` that helps developers efficiently address pending GitHub PR comments and review feedback. The command follows Opik's established patterns for cursor commands and integrates with the GitHub MCP to provide actionable feedback on PR reviews.
- OPIK-2322
- Will test in next PRs with comments.
- https://docs.cursor.com/en/agent/chat/commands
=> [OPIK-2322] [DOCS] Add address-github-pr-comments cursor command

apps/opik-frontend/package-lock.json, apps/opik-frontend/package.json, apps/opik-frontend/src/components/layout/SideBar/SideBar.tsx, apps/opik-frontend/src/components/pages-shared/experiments/CompareExperimentsConfigCell/CompareExperimentsConfigCell.tsx
This pull request adds support for automatic link detection and rendering in the experiment comparison config cell, and introduces the necessary dependencies for this feature. The most significant changes include updating dependencies, enhancing the config cell UI, and a minor fix for a sidebar component.
**Dependencies:**
* Added `linkify-react` and `linkifyjs` as new dependencies in `package.json` and `package-lock.json` to enable link detection and rendering in React components.
**UI Enhancements:**
* Updated `CompareExperimentsConfigCell.tsx` to wrap cell content in a `Linkify` component, automatically converting URLs in the config data to clickable links with appropriate styling and security attributes. 
**Component Fixes:**
* Added a `key` prop to the `SidebarInviteDevButton` in the …
=> [OPIK-2309] [FE] show links in the experiment config tab

apps/opik-frontend/src/api/playground/createLogPlaygroundProcessor.ts, apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundOutputs/PlaygroundOutputActions/usePromptDatasetItemCombination.ts, apps/opik-frontend/src/lib/playground.ts
This PR fixes an issue where experiment runs triggered via the playground would fail without providing a clear reason to users when AI providers return empty responses.
**Changes made:**
- **Added `parseCompletionOutput` utility function** in `lib/playground.ts` that provides a fallback message when AI providers return empty responses
- **Updated error handling** in `usePromptDatasetItemCombination.ts` to check for empty results and provide meaningful error messages
- **Enhanced trace logging** in `createLogPlaygroundProcessor.ts` to use the new parsing function for consistent output handling
The fix ensures that when an AI provider returns an empty response, users see the message "Empty response was received from AI provider, please try again" instead of experiencing a silent failure.
- …
=> [OPIK-2143] Experiment runs triggered via playground fail without reason

.cursor/commands/comet/create-and-run-tests.md
Added a comprehensive Cursor command for creating and running tests across all Opik components (Backend, Frontend, Python SDK, TypeScript SDK). The command provides automated test creation and execution that integrates seamlessly with daily development workflows, optimizing for large project environments.
The new command (`cursor create-and-run-tests`) includes:
- Project type detection and testing framework verification
- Relevant test execution (only new, updated, or modified tests)
- Comprehensive test creation following component-specific patterns
- Test failure analysis and systematic fixes
- Quality assurance and coverage review
- Integration with Opik testing conventions and rules
- OPIK-2178
- Manually tested.
- https://docs.cursor.com/en/agent/chat/commands
=> [OPIK-2178] [DOCS] Add create and run tests Cursor command

apps/opik-documentation/documentation/fern/docs/prompt_engineering/prompt_management.mdx, sdks/python/src/opik/api_objects/opik_client.py, sdks/python/tests/e2e/test_prompt.py
Remove obsolete name parameter from search_prompts method.
- Resolves #
- OPIK-NA
Updated e2e tests
Updated docs
=> [NA] [SDK] alexkuzmik / Improve API of search_prompts, remove name param

apps/opik-frontend/src/components/shared/ChartHorizontalLegendContent/ChartHorizontalLegendContent.tsx
- Add max-h-20 overflow-y-auto to horizontal chart legends
- Constrains legends to ~80px height with scrollbar when needed
- Fixes overwhelming UI when charts have 25+ legend items
- Resolves #
- OPIK-1487
=> [OPIK-1487] [FE] Fix long legends in Metrics tab charts with scrollbar

apps/opik-frontend/src/components/pages-shared/traces/TraceDetailsPanel/TraceDetailsActionsPanel.tsx
Changed the agent graph toggle button from `variant="secondary"` to `variant="default"` to make it more prominent and discoverable in the traces sidebar. This simple styling change makes the "Show/Hide agent graph" button stand out more, improving user experience when working with agent workflows.
The change affects only the button styling - all existing functionality remains unchanged.
- Resolves #
- OPIK-2238
=> [OPIK-2238] [FE] Make agent graph button more discoverable by using primary variant

apps/opik-backend/config.yml, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/ServiceTogglesConfig.java, apps/opik-backend/src/test/resources/config-test.yml
- Add humanAnnotationEnabled field to ServiceTogglesConfig.java
- Add TOGGLE_HUMAN_ANNOTATION_ENABLED to config.yml with default false
- Add configuration to test config file
- Feature flag will be accessible via /v1/private/toggles/ API endpoint
- Resolves #
- OPIK-2350
=> [OPIK-2350] [BE] Add TOGGLE_HUMAN_ANNOTATION_ENABLED feature flag

apps/opik-backend/src/main/java/com/comet/opik/api/FeedbackDefinition.java, apps/opik-backend/src/main/java/com/comet/opik/domain/CategoricalFeedbackDefinitionDefinitionModel.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackDefinitionDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/FeedbackDefinitionModel.java, apps/opik-backend/src/main/java/com/comet/opik/domain/NumericalFeedbackDefinitionDefinitionModel.java, apps/opik-backend/src/main/resources/liquibase/db-app-state/migrations/000024_add_description_field_to_feedback_definitions.sql, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FeedbackDefinitionResourceTest.java
- Add description MEDIUMTEXT column to feedback_definitions table via Liquibase migration
- Update FeedbackDefinitionModel interface and implementations to include description field
- Add description field to FeedbackDefinition API DTOs
- Update DAO SQL queries to handle description field in INSERT/UPDATE operations
- Extend existing tests to validate description field functionality in create/update workflows
- Resolves #
- OPIK-2351
NA
=> [OPIK-2351] [BE] Add description field for feedback-definition resource

apps/opik-frontend/src/components/pages/ConfigurationPage/FeedbackDefinitionsTab/FeedbackDefinitionsTab.tsx, apps/opik-frontend/src/components/shared/AddEditFeedbackDefinitionDialog/AddEditFeedbackDefinitionDialog.tsx, apps/opik-frontend/src/types/feedback-definitions.ts
This PR adds an optional description field to the feedback definition creation and editing dialog. Users can now provide additional context and details when creating or editing feedback definitions to help clarify their purpose and usage.
**Key Changes:**
- Added `description` field to `CreateFeedbackDefinition` TypeScript interface as an optional property
- Enhanced `AddEditFeedbackDefinitionDialog` component with a `Textarea` input for description
- Added proper form state management for the description field
- Included character limit validation (255 characters max)
- Added description field to the composed feedback definition object when creating/updating
- OPIK-2357 
- Manual testing of feedback definition creation dialog with description field
- Validation of character limit …
=> [OPIK-2357] [FE] Add description field to feedback definition dialog

apps/opik-documentation/documentation/fern/docs/evaluation/evaluate_threads.mdx, apps/opik-documentation/documentation/fern/docs/prompt_engineering/prompt_management.mdx, apps/opik-documentation/documentation/fern/docs/tracing/export_data.mdx, sdks/python/src/opik/api_objects/opik_client.py, sdks/python/src/opik/api_objects/threads/threads_client.py, sdks/python/src/opik/evaluation/threads/evaluator.py
Enhanced filter_string documentation across SDK and user documentation with comprehensive Opik Query Language (OQL) reference. Added complete field and operator support tables for all search methods (search_traces, search_spans, search_prompts, search_threads, and evaluate_threads). Verified all documented fields and operators against actual SDK implementation to ensure 100% accuracy.
- Resolves # 
- NA 
- Verified all documented fields exist in opik_query_language.py COLUMNS dictionary
- Verified all documented operators exist in SUPPORTED_OPERATORS dictionary  
- Tested examples against actual OQL parser implementation
- Confirmed consistency across all search methods
- Updated SDK docstrings for 5 methods: search_traces, search_spans, search_prompts, search_threads, evaluate_threads
- …
=> [NA] [DOCS] Improve filter_string parameter documentation

apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsActionsPanel.tsx, apps/opik-frontend/src/components/pages/DatasetItemsPage/DatasetItemsPage.tsx
Added export functionality to dataset items page similar to traces, spans, and experiment items:
- Enhanced DatasetItemsActionsPanel with ExportToButton component
- Added CSV/JSON export support for dataset items with proper data mapping
- Implemented columnsToExport calculation for dynamic dataset columns
- Fixed data mapping to handle nested data fields in dataset items
- Added proper filename generation following project conventions
Implements OPIK-2348: Add download button for Dataset items export
- [] Documentation update
- Resolves #
- OPIK-2348
Manually tested.
NA
=> [OPIK-2348] [FE] Add dataset items download functionality

.cursor/mcp.json
Added "issues" to the GITHUB_TOOLSETS environment variable in `.cursor/mcp.json` to enable GitHub issues functionality in the MCP server configuration. This allows the GitHub MCP server to access and manage GitHub issues in addition to repositories and pull requests.
- OPIK-2405 
- https://github.com/github/github-mcp-server?tab=readme-ov-file#available-toolsets
=> [OPIK-2405] [CONFIG] Add issues to toolset to Github MCP server

apps/opik-backend/src/main/java/com/comet/opik/api/AnnotationQueue.java, apps/opik-backend/src/main/java/com/comet/opik/api/AnnotationQueueBatch.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/AnnotationQueuesResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AnnotationQueueDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/AnnotationQueueService.java, apps/opik-backend/src/main/resources/liquibase/db-app-analytics/migrations/000037_add_annotation_queues_table.sql, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/AnnotationQueuesResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/AnnotationQueuesResourceTest.java
Implements the foundational annotation queue endpoint for human annotation workflows. This adds a new private API endpoint for creating annotation queues that can be associated with projects and configured for different annotation scopes.
**Key Implementation:**
- **AnnotationQueue API Model**: Record-based data model with JsonView patterns, validation annotations, and AnnotationScope enum (TRACE/THREAD)
- **REST Endpoint**: POST `/v1/private/annotation-queues` with proper OpenAPI documentation, rate limiting, and error handling
- **Data Access Layer**: Reactive R2DBC implementation for ClickHouse with proper context binding and array handling
- **Business Logic**: Service layer with UUID v7 generation, default value setting, and OpenTelemetry instrumentation
- **Database Migration**: …
=> [OPIK-2352] [BE] Add annotation queues table and create endpoint

apps/opik-python-backend/src/opik_backend/demo_data_generator.py, apps/opik-python-backend/tests/test_demo_data_generator.py
Since its launch, we have seen spikes on threads related to endpoints. This PR aims to reduce concurrence to minimize overhead on the backend side. Additionally, we have removed the call to get the threads, as it could cause even more contention. 
- Resolves #
OPIK-2240
NA
NA
=> [OPIK-2240] [BE] Fix demo data issue with threads

.github/workflows/documentation_preview_link.yml, apps/opik-documentation/documentation/fern/docs/changelog/2025-07-18.mdx, apps/opik-documentation/documentation/fern/docs/production/gateway.mdx, apps/opik-documentation/documentation/fern/docs/self-host/backup.mdx
This PR fixes several broken links in the Opik documentation that were returning 404 errors. The changes ensure users have access to appropriate resources and support channels by updating private repository references and fixing broken GitHub links.
- Resolves # 
- NA 
Manual verification of all fixed links to ensure they resolve correctly and provide appropriate user guidance.
Updated documentation links in:
- `apps/opik-documentation/documentation/fern/docs/production/gateway.mdx` - Fixed Kong plugin references
- `apps/opik-documentation/documentation/fern/docs/changelog/2025-07-18.mdx` - Fixed GitHub compare link
- `apps/opik-documentation/documentation/fern/docs/self-host/backup.mdx` - Fixed GitHub discussions link
- **Kong Plugin Link** (gateway.mdx): Updated private repo reference …
=> [NA] [DOCS] Fix broken links in Opik documentation

.github/workflows/publish_cursor_extension.yml
This PR updates the GitHub Actions workflow for publishing the Cursor extension to allow manual triggering instead of automatic triggering on release creation.
Replaces automatic release-based triggering with manual workflow dispatch
Enables on-demand publishing of the Cursor extension for testing and deployment flexibility
- Resolves #
- OPIK-0000
Will be tested manually by doing a release
N/A
=> [NA] [DevOps] Allow cursor extension publish action to be run manually

apps/opik-backend/config.yml, apps/opik-backend/pom.xml, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/RedisConfig.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/aws/AwsIamCredentialsResolver.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/aws/IamAuthTokenRequestV2.java, apps/opik-backend/src/test/java/com/comet/opik/infrastructure/RedisConfigIntegrationTest.java
- Introduces AWS IAM auth for ElastiCache Redis using Redisson's credentials resolver
- Adds `RedisConfig` toggle `awsIamAuth.enabled` to keep backward compatibility
- Implements `AwsIamCredentialsResolver` + `IamAuthTokenRequestV2` for IAM token generation
- Adds `RedisConfigIntegrationTest` (conditional via env) 
- OPIK-2400
- Integration test runs conditionally with env vars; verified handshake and signing;
NA
=> [OPIK-2400] [BE] Add Redis ElastiCache IAM auth via Redisson + integration test

extensions/cursor/package.json, extensions/cursor/src/cursor/cursorService.ts, extensions/cursor/src/cursor/sessionManager.ts, extensions/cursor/src/extension.ts, extensions/cursor/src/mcp/mcpService.ts, extensions/cursor/src/opik.ts, extensions/cursor/src/sentry.ts, extensions/cursor/src/utils.ts
Due to the way that Sentry was initialized, we were capturing errors across multiple extensions rather than just the Opik. This was addressed as part of this PR.
- Resolves #
- OPIK-000
Manually tested
N/A
=> [NA] [Cursor Ext] Improved Sentry error logging

apps/opik-frontend/package-lock.json, apps/opik-frontend/package.json, apps/opik-frontend/src/components/shared/SyntaxHighlighter/CodeMirrorHighlighter.tsx
This pull request introduces the `@uiw/codemirror-extensions-hyper-link` package to the project and integrates hyperlink support into the `CodeMirrorHighlighter` component. The main focus is to enhance the code editor with clickable hyperlink functionality.
- Resolves #
- OPIK-2309
=> [OPIK-2309] [FE] Add clickable links in trace metadata

.github/workflows/trigger_test_env_on_label.yaml, deployment/helm_chart/opik/README.md, deployment/helm_chart/opik/values.yaml
- Use binami legacy images for minio and mysql in default values
- update trigger-opik-adhok-env workflow not to build guardrail image
- [V] User facing
- Resolves #3305
=> [issue-3305] [HELM] Use binami legacy images for minio and mysql in default values

apps/opik-backend/src/main/java/com/comet/opik/domain/AnnotationQueueDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/DatasetItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ExperimentItemDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/OptimizationDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/ProjectMetricsDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/SpanDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/MultiValueFeedbackScoresE2ETest.java
This PR fixes a bug in the feedback scores query where entries for the same author would appear twice if they had scores in both the legacy `feedback_scores` table and the new `authored_feedback_scores` table. The issue occurred because the original query used `UNION ALL` without proper deduplication logic.
When a user had a feedback score in the legacy table and then wanted to override it with a new score (creating an entry in the new table), both entries would appear in the results instead of the newer one overriding the older one.
Refactored the TraceDAO query to use a 3-CTE approach:
1. **`feedback_scores_combined_raw`**: Performs `UNION ALL` of both tables
2. **`feedback_scores_with_ranking`**: Applies `ROW_NUMBER()` window function partitioned by `workspace_id`, `project_id`, …
=> [OPIK-2424] [BE] Fix duplicate feedback scores when same author exists in both legacy and authored tables

apps/opik-documentation/documentation/fern/docs/quickstart.mdx
Updated the Vercel AI SDK tab in the quickstart page to replace the "Coming Soon" message with complete integration instructions. The integration is actually implemented and documented, but the quickstart page wasn't updated to reflect this.
- NA
- Updated quickstart.mdx with complete Vercel AI SDK integration guide
- Links to detailed integration documentation at /tracing/integrations/vercel-ai-sdk
=> [NA] [DOCS] Update Vercel AI SDK integration in quickstart page

.github/workflows/clickhouse_migration_cluster_check.yml
Fixes a critical issue in the ClickHouse migration cluster check workflow where pushes to main would fail to detect changed migration files due to shallow clone limitations.
**Problem**: The workflow used `git diff HEAD~1..HEAD` for pushes to main, but with `fetch-depth: 1`, the `HEAD~1` commit doesn't exist in the shallow clone, causing the workflow to fail or return no changed files.
**Solution**: Replace git-based file detection with GitHub API calls for both pull requests and pushes to main. This approach:
- Works reliably regardless of fetch-depth settings
- Uses consistent data source (GitHub API) for both scenarios  
- Maintains the same filtering logic and performance benefits
- Handles edge cases better (like merge commits)
**Changes Made**:
- Updated the file detection logic for …
=> [OPIK-2414] [CI] Fix ClickHouse workflow fetch-depth issue for pushes to main

.github/workflows/clickhouse_migration_cluster_check.yml
This PR fixes compatibility issues in the ClickHouse migration validation workflow that were causing failures in GitHub Actions environments.
**Root Cause**: The workflow was using the `mapfile` command which is not available in all shell environments, including GitHub Actions. This caused the validation script to receive no arguments, leading to unexpected behavior.
**Solution**: Replaced `mapfile` with `xargs` for reliable cross-platform file list processing. The new approach uses `echo "$MIGRATION_FILES" | xargs ./scripts/check_clickhouse_migrations_cluster.sh` to properly handle both single and multiple migration files.
**Implementation Changes**:
- Removed dependency on `mapfile` command
- Simplified file processing logic using standard `xargs` utility
- Ensured proper handling of …
=> [OPIK-2414] [CI] Fix ClickHouse migration workflow compatibility with GitHub Actions

apps/opik-backend/src/main/java/com/comet/opik/api/filter/Field.java, apps/opik-backend/src/main/java/com/comet/opik/api/filter/TraceField.java, apps/opik-backend/src/main/java/com/comet/opik/api/filter/TraceThreadField.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterQueryBuilder.java, apps/opik-backend/src/main/java/com/comet/opik/domain/filter/FilterStrategy.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java
This implementation adds annotation queue filtering support to both trace and trace thread endpoints. The enhancement allows users to filter traces and trace threads based on annotation queue IDs, enabling more precise querying and organization of annotated data.
Key changes include:
• Added `ANNOTATION_QUEUE_IDS` field to `TraceField` and `TraceThreadField` enums for filter support
• Updated `FilterQueryBuilder` to map the new field to analytics database queries
• Introduced `ANNOTATION_AGGREGATION` filter strategy for proper query building and execution
• Enhanced filter mapping to support both trace and trace thread filtering scenarios
- OPIK-2356
Added comprehensive test coverage in `TracesResourceTest` including:
• Parameterized tests for annotation queue ID filtering functionality
• …
=> [OPIK-2356] [BE] Update trace and thread related endpoint to support filtering by annotation queue id

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/PromptResource.java, apps/opik-backend/src/main/java/com/comet/opik/domain/PromptService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/PromptResourceTest.java, apps/opik-documentation/documentation/fern/docs/faq.mdx, apps/opik-frontend/src/api/prompts/useRestorePromptVersionMutation.ts, apps/opik-frontend/src/components/pages/PromptPage/PromptTab/CommitHistory.tsx, apps/opik-frontend/src/components/pages/PromptPage/PromptTab/PromptTab.tsx, apps/opik-frontend/src/components/pages/PromptPage/PromptTab/RestoreVersionDialog.tsx
Enables the restoration of previous prompt versions by creating new versions with content from selected versions.
Backend changes:
- Add restorePromptVersion method to PromptService
- Add POST /prompts/{promptId}/versions/{versionId}/restore endpoint
- Add a comprehensive integration test for restore functionality
Frontend changes:
- Add useRestorePromptVersionMutation API hook
- Add restore button with Undo-2 icon to CommitHistory component
- Add confirmation modal for restore action
- Add a tooltip with 'Restore this version' message
Implements issue-2232: Add revert to previous version feature for prompts
- Resolves #
- OPIK-2232
=> [issue-2232] [BE] [FE] Add prompt version restore functionality

apps/opik-backend/src/main/java/com/comet/opik/api/TraceThreadBatchIdentifier.java, apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/priv/TracesResource.java, apps/opik-backend/src/main/java/com/comet/opik/api/validation/TraceThreadBatchIdentifierValidation.java, apps/opik-backend/src/main/java/com/comet/opik/api/validation/TraceThreadBatchIdentifierValidator.java, apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadService.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/resources/TraceResourceClient.java, apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/TracesResourceTest.java, apps/opik-backend/src/test/java/com/comet/opik/api/validation/TraceThreadBatchIdentifierValidatorTest.java
- Add support for multi-thread closure so we can reduce the number of individual calls to close threads on Demo Data. The endpoint remains the same; we only added the `threadIds` property, which accepts a list of thread IDs. 
- Resolves #
- NA
NA
NA
=> [NA] [BE] Add support to multi thread closure

apps/opik-frontend/src/components/pages-shared/experiments/AddExperimentDialog/AddExperimentDialog.tsx
The boilerplate code for creating a new experiment does not set the OPENAI_API_KEY environment variable, which causes errors if the variable hasn’t already been configured in the user’s environment. We need to fix this by adding a hint to inform users that this variable must be set beforehand.
```python
os.environ["OPIK_URL_OVERRIDE"] = "http://localhost:5173/api"
```
This PR adds a commented environment variable hint for OPENAI_API_KEY in the experiment creation boilerplate code to help users avoid errors when the key isn't already configured in their environment.
- Adds a commented line showing how to set the OPENAI_API_KEY environment variable
- Improves the boilerplate code template with better guidance for users
- OPIK-2506
No tests affected
Create experiment boilerplate code …
=> [OPIK-2506] [FE] Add OPENAI_API_KEY environment variable to the experiment creation boilerplate code

apps/opik-frontend/src/components/pages/SMEFlowPage/AnnotationView/CommentAndScoreViewer.tsx, apps/opik-frontend/src/components/pages/SMEFlowPage/AnnotationView/ThreadDataViewer.tsx
Fixed two issues in the SME Flow Page annotation view:
1. **Feedback scores state management**: Added `currentItem` to context and `key` prop to `FeedbackScoresEditor` to ensure proper state reset when switching between annotation items
2. **Thread trace ordering**: Fixed trace ordering in thread view by sorting traces by ID and using the last trace instead of the first one for display
- Resolves # 
- OPIK-2363 
- NA 
- Verified feedback scores reset properly when switching between annotation items
- Confirmed thread traces are displayed in correct order
- Tested annotation workflow end-to-end
N/A - No documentation changes required for these bug fixes
=> [OPIK-2363] [FE] Fix SME Flow annotation issues

apps/opik-documentation/documentation/fern/docs/tracing/integrations/openai.mdx, apps/opik-documentation/documentation/fern/docs/tracing/log_chat_conversations.mdx, apps/opik-documentation/documentation/fern/docs/tracing/log_traces.mdx, sdks/python/tests/library_integration/genai/test_genai.py, sdks/python/tests/library_integration/openai/test_openai_chat_completions.py, sdks/python/tests/library_integration/openai/test_openai_responses.py
The current docs are very focused on the technicalities of change rather than the user value. It's also going to be quite hard for users to find this functionality through search or by reading through the docs.Would be great if we could:
In "Log traces":
- Merge most of the content to the Logging additional data section, this is essentially an alternative to the update_current_trace method
- Add a new section that is focused on the passing of the thread_id that focuses on the log trace to a conversation user value
- Add this way of logging conversations to the [Log conversation](https://opik-preview-8daaead1-2f84-47ce-ae31-a228a87efa4d.docs.buildwithfern.com/docs/opik/tracing/log_chat_conversations#logging-conversations) page
Add this to each of the relevant integration documentation …
=> [OPIK-2455] [P SDK] Update SDK documentation to provide more details about `opik_args` feature

apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/OnlineScoringBaseScorer.java, apps/opik-backend/src/main/java/com/comet/opik/infrastructure/OnlineScoringStreamConfigurationAdapter.java, apps/opik-backend/src/test/resources/config-test.yml
This PR refactors the Redis stream event listeners in the `apps/opik-backend/src/main/java/com/comet/opik/api/resources/v1/events/` package to eliminate code duplication and improve maintainability.
- **Refactored OnlineScoringBaseScorer** to extend `BaseRedisSubscriber` instead of duplicating Redis stream functionality
- **Created OnlineScoringStreamConfigurationAdapter** to bridge `OnlineScoringConfig` with the `StreamConfiguration` interface
- **Added missing stream configurations** in test config for trace thread scorers (`trace_thread_llm_as_judge` and `trace_thread_user_defined_metric_python`)
- **Eliminated ~100+ lines of duplicated code** while preserving all existing functionality
- All Redis stream listeners now consistently extend `BaseRedisSubscriber`
- Common stream handling …
=> [OPIK-2095] [BE] Refactor Redis stream listeners to extend BaseRedisSubscriber

sdks/python/tests/library_integration/aisuite/test_aisuite.py, sdks/python/tests/library_integration/anthropic/test_anthropic.py, sdks/python/tests/library_integration/bedrock/test_converse.py, sdks/python/tests/library_integration/genai/test_genai.py, sdks/python/tests/library_integration/litellm/test_litellm_completion.py
We need to verify that all supported integrations are compatible with the opik_args parameter when making direct calls to their respective wrapped clients. This should be done by adding integration tests for each library. Similar tests already exist for OpenAI and GenAI.
This PR adds integration tests to verify that all supported LLM provider integrations are compatible with the `opik_args` parameter when making direct calls to their wrapped clients. The purpose is to ensure consistent behavior across all integrations for passing custom span and trace metadata.
Key changes:
- Added `opik_args` compatibility tests for LiteLLM (sync and async), GenAI (sync and async), Bedrock, Anthropic, and AISuite integrations
- Tests verify that custom `tags`, `metadata`, and `thread_id` are properly …
=> [OPIK-2516] [P SDK] Check all supported integrations for compatibility with `opik_args`

apps/opik-frontend/src/components/pages-shared/onboarding/FrameworkIntegrations/quickstart-integrations.ts, apps/opik-frontend/src/components/pages-shared/onboarding/IntegrationExplorer/components/QuickInstallDialog.tsx, apps/opik-frontend/src/constants/integrations.ts
This PR updates the integration documentation links throughout the frontend UI to reflect the new URL structure. The integration documentation has been reorganized from `/tracing/integrations/[integration]` to `/integrations/[integration]`, and this change ensures all UI components point to the correct URLs.
- Updated documentation links in quickstart integrations configuration
- Fixed integration explorer dialog reference 
- Updated all integration constants to use the new URL pattern
The changes ensure users can successfully navigate to integration documentation from:
- Framework integrations onboarding flow
- Integration explorer dialog
- Integration cards and quick install dialogs
- Resolves #NA 
- NA 
1. Navigate to the onboarding flow and click on any integration documentation link …
=> [NA] [FE] Fix integration documentation links in UI

apps/opik-frontend/src/plugins/comet/posthog/index.ts
This pull request makes a small change to the PostHog analytics initialization in the frontend plugin. The configuration now removes explicit settings for capturing pageviews and page leaves, likely reverting to default PostHog behavior. No other functionality is affected.
- Removed `capture_pageview` and `capture_pageleave` options from the `posthog.init` configuration in `index.ts`.
- Resolves #
- OPIK-2437
=> [OPIK-2437] [FE] Clean up PostHog configuration

scripts/dev-runner.sh
This change configures the frontend to communicate with the local backend by setting the `VITE_BASE_API_URL` environment variable in the `scripts/dev-runner.sh` script. This ensures the frontend correctly points to the backend API when running in local development mode.
**What was changed:**
- Added `export VITE_BASE_API_URL="http://localhost:8080"` to the `start_frontend()` function in `scripts/dev-runner.sh`
- Added informational logging to indicate the API base URL being used
**Why this change was made:**
- Improves local development setup by ensuring frontend can communicate with the local backend
- Provides clear configuration and logging for troubleshooting development environment issues
- Makes the development workflow more reliable
- OPIK-2175
- Manually tested locally: `start`, …
=> [OPIK-2175] [SCRIPTS] Add FE to local BE API endpoints URL

sdks/python/src/opik/api_objects/opik_client.py, sdks/python/src/opik/api_objects/trace/trace_client.py, sdks/python/tests/e2e/test_tracing.py, sdks/python/tests/unit/api_objects/test_opik_client.py
Now it is a bit complicated to update the trace from user script which leads to confusing errors like saving parts of the trace in the different workspaces.
This PR implements a new update_trace() method for the Opik client to simplify trace updates and prevent workspace confusion. The implementation adds validation, documentation, and comprehensive test coverage.
- Introduced `update_trace` function in `OpikClient` for updating trace attributes such as metadata, tags, input, output, and more.
- Updated `trace_client` with `update_trace` implementation to handle and stream trace update messages.
- [ x] User facing
- OPIK-2569
Implemented unit and E2E test
Created docstring for new function
=> [OPIK-2569] [P SDK] Implement `Opik.update_trace()` method to make it easier to update trace

apps/opik-frontend/src/components/pages-shared/annotation-queues/AnnotationQueueProgress.tsx, apps/opik-frontend/src/components/pages-shared/annotation-queues/AnnotationQueueProgressCell.tsx, apps/opik-frontend/src/components/pages/AnnotationQueuePage/AnnotationQueuePage.tsx, apps/opik-frontend/src/components/pages/AnnotationQueuePage/AnnotationQueueProgressTag.tsx, apps/opik-frontend/src/components/pages/AnnotationQueuePage/CopySMELinkButton.tsx, apps/opik-frontend/src/components/pages/AnnotationQueuePage/EditAnnotationQueueButton.tsx, apps/opik-frontend/src/components/pages/AnnotationQueuePage/ExportAnnotatedDataButton.tsx, apps/opik-frontend/src/components/pages/AnnotationQueuePage/OpenSMELinkButton.tsx, apps/opik-frontend/src/components/pages/SMEFlowPage/SMEFlowContext.tsx, apps/opik-frontend/src/lib/annotation-queues.ts
This PR adds a comprehensive export functionality for annotated data in annotation queues, allowing users to export traces and threads with reviewer-specific annotations to CSV or JSON formats.
1. **Export Annotated Data Button**
- New dropdown button with "Export as CSV" and "Export as JSON" options
- Disabled when no reviewers are assigned to the queue
- Added tooltip: "Export annotated data"
2. **Per-Reviewer Data Export**
- CSV format: Creates columns per reviewer (`[reviewer_name].comment`, `[reviewer_name].[feedback_score_name]`, `[reviewer_name].[feedback_score_name].reason`)
- JSON format: Creates nested objects per reviewer with comments and feedback scores
- Handles multiple reviewers and their individual annotations
3. **CSV Export Enhancements**
- Integrates `json2csv` library …
=> [OPIK-2584] [FE] Add export annotated data button to annotation queue page

sdks/python/tests/e2e/test_tracing.py
Restores SDK E2E tests disabled in comet-ml/opik#3516, as tests are not flaky after https://github.com/comet-ml/opik/pull/3502
=> [NA] Revert "[SDK] Disable flaky test update span attachments"

apps/opik-backend/src/main/java/com/comet/opik/domain/TraceDAO.java, apps/opik-backend/src/main/java/com/comet/opik/domain/TraceService.java, apps/opik-backend/src/main/java/com/comet/opik/domain/threads/TraceThreadService.java
To reduce the cost of thread existence checks from the close threads endpoint, we've created a new query that returns the minimal data needed to check it and makes it if necessary. This should reduce the overhead caused by the current query.
- Resolves #
- NA
Current tests should validate the functionality.
NA
=> [NA] [BE] Reduce cost of thread exists check from close threads endpoint

apps/opik-frontend/src/components/pages-shared/automations/AddEditRuleDialog/RuleFilteringSection.tsx, apps/opik-frontend/src/components/pages/OnlineEvaluationPage/OnlineEvaluationPage.tsx, apps/opik-frontend/src/components/pages/TracesPage/RulesTab/RulesTab.tsx, apps/opik-frontend/src/components/shared/SliderInputControl/SliderInputControl.tsx
Changed the sampling rate display from decimal format (0 to 1) to percentage format (0% to 100%) in the Online Evaluation rules to improve user experience and reduce confusion.
1. **SliderInputControl Component** (`SliderInputControl.tsx`)
- Added optional `suffix` prop to display text next to input (e.g., "%")
- Suffix is rendered as a separate element, not part of the input value
- Component remains generic and reusable for other use cases
2. **RuleFilteringSection** (`RuleFilteringSection.tsx`)
- Changed slider range from 0-1 to 0-100
- Changed step from 0.01 to 1
- Encapsulated conversion logic: Display (0-100%) ↔ Storage (0.0-1.0)
- Backend continues to receive decimal values (0.0 to 1.0) - no breaking changes
3. **Table Columns** (OnlineEvaluationPage & RulesTab)
- Updated …
=> [OPIK-2613] [FE] Change sampling rate display from "0 to 1" to "0 to 100%" in Online Evaluation rules

apps/opik-documentation/documentation/fern/docs/tracing/integrations/crewai.mdx
Added a new section "Grouping traces into conversational threads using `thread_id`" to the CrewAI integration documentation. This section explains how to use the `thread_id` parameter to group CrewAI traces into conversational threads, matching the pattern used in other integrations like OpenAI.
The section includes:
- Clear explanation of threads in Opik
- Code example showing how to pass `thread_id` via `opik_args` parameter
- Reference link to the detailed "Log conversations" documentation
- Resolves # NA
- OPIK- NA
- Verified the documentation renders correctly with proper markdown formatting
- Checked that code examples follow the established pattern from test files
- Confirmed no linting errors in the updated documentation file
- Updated …
=> [NA] [DOCS] Add conversation logging section to CrewAI integration documentation
